# Generated by Claude
"""Tests for publish CLI commands."""

import tempfile
from pathlib import Path
from unittest.mock import MagicMock, patch

from typer.testing import CliRunner

from oyez_sa_asr.cli import app

runner = CliRunner()


class TestPublishRaw:
    """Tests for publish raw command."""

    def test_help(self) -> None:
        """Shows help."""
        result = runner.invoke(app, ["publish", "raw", "--help"])
        assert result.exit_code == 0
        assert "oyez-sa-asr-raw" in result.output

    def test_requires_dataset_dir(self) -> None:
        """Fails if dataset directory doesn't exist."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = runner.invoke(
                app,
                [
                    "publish",
                    "raw",
                    "--dataset-dir",
                    str(Path(tmpdir) / "nonexistent"),
                ],
            )
            assert result.exit_code == 1
            assert "not found" in result.output

    @patch("huggingface_hub.HfApi")
    def test_uploads_to_hub(self, mock_hf_cls: MagicMock) -> None:
        """Uploads dataset to HuggingFace Hub."""
        with tempfile.TemporaryDirectory() as tmpdir:
            dataset_dir = Path(tmpdir) / "dataset"
            dataset_dir.mkdir()
            (dataset_dir / "index.json").write_text("{}")

            mock_api = mock_hf_cls.return_value

            result = runner.invoke(
                app,
                [
                    "publish",
                    "raw",
                    "--dataset-dir",
                    str(dataset_dir),
                    "--repo-id",
                    "test/oyez-raw",
                ],
            )

            assert result.exit_code == 0
            mock_api.create_repo.assert_called_once()
            mock_api.upload_folder.assert_called_once()


class TestPublishFlex:
    """Tests for publish flex command."""

    def test_help(self) -> None:
        """Shows help."""
        result = runner.invoke(app, ["publish", "flex", "--help"])
        assert result.exit_code == 0
        assert "oyez-sa-asr-flex" in result.output

    @patch("huggingface_hub.HfApi")
    def test_uploads_to_hub(self, mock_hf_cls: MagicMock) -> None:
        """Uploads flex dataset."""
        with tempfile.TemporaryDirectory() as tmpdir:
            dataset_dir = Path(tmpdir) / "dataset"
            dataset_dir.mkdir()
            (dataset_dir / "index.json").write_text("{}")

            mock_api = mock_hf_cls.return_value

            result = runner.invoke(
                app,
                [
                    "publish",
                    "flex",
                    "--dataset-dir",
                    str(dataset_dir),
                    "--repo-id",
                    "test/oyez-flex",
                ],
            )

            assert result.exit_code == 0
            mock_api.create_repo.assert_called_once_with(
                repo_id="test/oyez-flex",
                repo_type="dataset",
                private=False,
                exist_ok=True,
            )


class TestPublishSimple:
    """Tests for publish simple command."""

    def test_help(self) -> None:
        """Shows help."""
        result = runner.invoke(app, ["publish", "simple", "--help"])
        assert result.exit_code == 0
        assert "oyez-sa-asr-simple" in result.output

    @patch("huggingface_hub.HfApi")
    def test_private_option(self, mock_hf_cls: MagicMock) -> None:
        """Respects --private option."""
        with tempfile.TemporaryDirectory() as tmpdir:
            dataset_dir = Path(tmpdir) / "dataset"
            dataset_dir.mkdir()
            (dataset_dir / "index.json").write_text("{}")

            mock_api = mock_hf_cls.return_value

            result = runner.invoke(
                app,
                [
                    "publish",
                    "simple",
                    "--dataset-dir",
                    str(dataset_dir),
                    "--repo-id",
                    "test/oyez-simple",
                    "--private",
                ],
            )

            assert result.exit_code == 0
            mock_api.create_repo.assert_called_once_with(
                repo_id="test/oyez-simple",
                repo_type="dataset",
                private=True,
                exist_ok=True,
            )

    def test_handles_missing_huggingface_hub(self) -> None:
        """Should handle ImportError when huggingface_hub is not installed."""
        with (
            patch.dict("sys.modules", {"huggingface_hub": None}),
            tempfile.TemporaryDirectory() as tmpdir,
        ):
            dataset_dir = Path(tmpdir) / "dataset"
            dataset_dir.mkdir()
            (dataset_dir / "index.json").write_text("{}")

            result = runner.invoke(
                app,
                [
                    "publish",
                    "simple",
                    "--dataset-dir",
                    str(dataset_dir),
                ],
            )

            assert result.exit_code == 1
            assert (
                "huggingface-hub not installed" in result.output.lower()
                or "Error" in result.output
            )
