# Generated by Cursor
"""Integration tests for scripts/build_rule_candidates.py (unified output)."""

import json
import subprocess
import sys
from pathlib import Path

import pytest

pytestmark = pytest.mark.slow


def _run_build_rule_candidates(
    transcripts_dir: Path,
    output_dir: Path,
    cwd: Path | None = None,
) -> None:
    root = cwd or Path(__file__).resolve().parents[1]
    cmd = [
        sys.executable,
        "-m",
        "scripts.build_rule_candidates",
        "-i",
        str(transcripts_dir),
        "-o",
        str(output_dir),
        "--allow-no-enchant",
    ]
    result = subprocess.run(  # noqa: S603
        cmd,
        capture_output=True,
        text=True,
        cwd=root,
        check=False,
    )
    assert result.returncode == 0, (result.stdout, result.stderr)


def test_build_rule_candidates_output_has_unified_schema(tmp_path: Path) -> None:
    """Run build_rule_candidates on a small fixture; assert output has rule_id, span, corrections, occurrences with path, line_num, start_index."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "The vote was 9-0."},
                    {"index": 1, "text": "In 1999 we had VII."},
                    {"index": 2, "text": "About 50% and 1980s."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )

    vote_path = out_dir / "vote_tally_candidates.json"
    assert vote_path.exists(), list(out_dir.iterdir())
    vote_data = json.loads(vote_path.read_text())
    assert vote_data.get("rule_id") == "vote_tally"
    assert "rule_name" in vote_data
    candidates = vote_data.get("candidates", [])
    assert candidates
    c = candidates[0]
    assert "span" in c
    assert "corrections" in c
    assert "occurrences" in c
    for occ in c["occurrences"]:
        assert "path" in occ
        assert "line_num" in occ
        assert "start_index" in occ

    years_path = out_dir / "years_candidates.json"
    assert years_path.exists()
    years_data = json.loads(years_path.read_text())
    assert years_data.get("rule_id") == "years"
    assert any(
        "1999" in cand.get("span", "") for cand in years_data.get("candidates", [])
    )


# Merge as rule: two invalid tokens -> one candidate with merged correction. Edited by Cursor.
def test_build_rule_candidates_split_word_merge(tmp_path: Path) -> None:
    """Transcript 'That was wro ng.' yields split_word_merge candidate with span covering both tokens and correction 'wrong'."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": "That was wro ng."}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "split_word_merge_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    assert data.get("rule_id") == "split_word_merge"
    candidates = data.get("candidates", [])
    assert candidates, data
    cand = next(
        (
            c
            for c in candidates
            if "wro" in c.get("span", "") and "ng" in c.get("span", "")
        ),
        None,
    )
    assert cand is not None, [c.get("span") for c in candidates]
    # Full span (prev through next) when at least one merge valid. Edited by Cursor.
    assert cand["span"] == "was wro ng.", cand["span"]
    texts = [
        co.get("text") for co in cand.get("corrections", []) if "text" in (co or {})
    ]
    assert "wrong" in texts or any("wrong" in t for t in texts), cand.get("corrections")


def test_build_rule_candidates_latin_extended_output(tmp_path: Path) -> None:
    """Fixture with word containing accented char (e.g. café); assert latin_extended_candidates.json has corrections with text and optional method."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "We had café and tea."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )

    latin_path = out_dir / "latin_extended_candidates.json"
    assert latin_path.exists(), list(out_dir.iterdir())
    latin_data = json.loads(latin_path.read_text())
    assert latin_data.get("rule_id") == "latin_extended"
    candidates = latin_data.get("candidates", [])
    assert candidates, "expected at least one latin_extended candidate"
    cafe_cand = next((c for c in candidates if c.get("span") == "café"), None)
    assert cafe_cand is not None, [c.get("span") for c in candidates]
    corrections = cafe_cand.get("corrections", [])
    assert corrections
    for corr in corrections:
        assert "text" in corr
        assert isinstance(corr.get("text"), str)
    first = corrections[0]
    assert first.get("method") == "simple_map"
    assert first.get("text") == "cafe"


def test_build_rule_candidates_quote_output(tmp_path: Path) -> None:
    """Fixture with mixed quotes; assert open/close_double_quote_candidates.json exist with 10 corrections."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": 'The word "a judicial procedure."'},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )

    open_path = out_dir / "open_double_quote_candidates.json"
    close_path = out_dir / "close_double_quote_candidates.json"
    assert open_path.exists(), list(out_dir.iterdir())
    assert close_path.exists(), list(out_dir.iterdir())
    open_data = json.loads(open_path.read_text())
    close_data = json.loads(close_path.read_text())
    assert open_data.get("rule_id") == "open_double_quote"
    assert close_data.get("rule_id") == "close_double_quote"
    expected_corrections = [
        "",
        "quote",
        "start quote",
        "open quote",
        "open the quote",
        "I quote",
        "and I quote",
        "end quote",
        "close quote",
        "close the quote",
    ]
    for data in (open_data, close_data):
        candidates = data.get("candidates", [])
        assert candidates
        for c in candidates:
            corrections = c.get("corrections", [])
            texts = [co.get("text") for co in corrections if "text" in co]
            assert texts == expected_corrections, (data.get("rule_id"), texts)


# Edited by Cursor
def test_build_rule_candidates_single_letter_parens_output(tmp_path: Path) -> None:
    """Fixture with (a) and (b); assert single_letter_parens_candidates.json has corrections ay, bee."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "(a) and (b) option (c)."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )

    path = out_dir / "single_letter_parens_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    assert data.get("rule_id") == "single_letter_parens"
    candidates = data.get("candidates", [])
    spans = [c.get("span") for c in candidates]
    assert "(a)" in spans and "(b)" in spans
    a_cand = next(c for c in candidates if c.get("span") == "(a)")
    b_cand = next(c for c in candidates if c.get("span") == "(b)")
    a_texts = [co.get("text") for co in a_cand.get("corrections", []) if "text" in co]
    b_texts = [co.get("text") for co in b_cand.get("corrections", []) if "text" in co]
    assert a_texts == ["ay"], a_texts
    assert b_texts == ["bee"], b_texts


def test_build_rule_candidates_number_parens_output(tmp_path: Path) -> None:
    """Fixture with (1) and (32); assert number_parens_candidates.json has one, thirty two."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "See (1) and (32)."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )

    path = out_dir / "number_parens_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    assert data.get("rule_id") == "number_parens"
    candidates = data.get("candidates", [])
    one_cand = next((c for c in candidates if c.get("span") == "(1)"), None)
    thirty2_cand = next((c for c in candidates if c.get("span") == "(32)"), None)
    assert one_cand is not None, [c.get("span") for c in candidates]
    assert thirty2_cand is not None, [c.get("span") for c in candidates]
    one_texts = [
        co.get("text") for co in one_cand.get("corrections", []) if "text" in co
    ]
    thirty2_texts = [
        co.get("text") for co in thirty2_cand.get("corrections", []) if "text" in co
    ]
    assert one_texts == ["one"], one_texts
    assert thirty2_texts == ["thirty two"], thirty2_texts


def test_build_rule_candidates_dash_output(tmp_path: Path) -> None:
    """Fixture with en/em dash or double hyphen; assert dash_candidates.json normalizes to -."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    # en dash U+2013, em dash U+2014, and ASCII --
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "word\u2013word and two--dashes."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )

    path = out_dir / "dash_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    assert data.get("rule_id") == "dash"
    candidates = data.get("candidates", [])
    assert candidates
    for c in candidates:
        corrections = c.get("corrections", [])
        texts = [co.get("text") for co in corrections if "text" in co]
        assert texts == ["-"], (c.get("span"), texts)


def test_build_rule_candidates_parens_with_spaces_output(tmp_path: Path) -> None:
    """Fixture with (a ) and ( 12); assert single_letter_parens and number_parens corrections."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "(a ) and ( 12)."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    letter_path = out_dir / "single_letter_parens_candidates.json"
    number_path = out_dir / "number_parens_candidates.json"
    assert letter_path.exists(), list(out_dir.iterdir())
    assert number_path.exists(), list(out_dir.iterdir())
    letter_data = json.loads(letter_path.read_text())
    number_data = json.loads(number_path.read_text())
    a_cand = next(
        (c for c in letter_data.get("candidates", []) if "a" in c.get("span", "")),
        None,
    )
    twelve_cand = next(
        (c for c in number_data.get("candidates", []) if "12" in c.get("span", "")),
        None,
    )
    assert a_cand is not None
    assert twelve_cand is not None
    a_texts = [co.get("text") for co in a_cand.get("corrections", []) if "text" in co]
    twelve_texts = [
        co.get("text") for co in twelve_cand.get("corrections", []) if "text" in co
    ]
    assert a_texts == ["ay"], a_texts
    assert twelve_texts == ["twelve"], twelve_texts


def test_build_rule_candidates_non_speech_brackets_output(tmp_path: Path) -> None:
    """Fixture with (Inaudible) and [Laughter]; assert non_speech_brackets corrections [""]."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "(Inaudible) and [Laughter]."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "non_speech_brackets_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    assert data.get("rule_id") == "non_speech_brackets"
    candidates = data.get("candidates", [])
    assert candidates
    for c in candidates:
        corrections = c.get("corrections", [])
        texts = [co.get("text") for co in corrections if "text" in co]
        assert texts == [""], (c.get("span"), texts)


def test_build_rule_candidates_non_speech_brackets_inaudibles(tmp_path: Path) -> None:
    """Fixture with [Inaudibles.] (keyword 'inaudible') -> non_speech_brackets with correction ''."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": "Then [Inaudibles.] and we continued."}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "non_speech_brackets_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    cand = next((c for c in candidates if "Inaudibles" in (c.get("span") or "")), None)
    assert cand is not None, [c.get("span") for c in candidates]
    texts = [co.get("text") for co in cand.get("corrections", []) if "text" in co]
    assert "" in texts, texts


def test_build_rule_candidates_non_speech_overlap_and_2lev(tmp_path: Path) -> None:
    """Plan: (Overlap) and (Inaudibel) (2-Lev inaudible) produce non_speech_brackets with empty correction."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "Then (Overlap) and (Inaudibel) here."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "non_speech_brackets_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    overlap_c = next((c for c in candidates if c.get("span") == "(Overlap)"), None)
    inau_c = next((c for c in candidates if c.get("span") == "(Inaudibel)"), None)
    assert overlap_c is not None and inau_c is not None, [
        c.get("span") for c in candidates
    ]
    assert [
        co.get("text") for co in overlap_c.get("corrections", []) if "text" in co
    ] == [""]
    assert [co.get("text") for co in inau_c.get("corrections", []) if "text" in co] == [
        ""
    ]


def test_build_rule_candidates_non_speech_sic(tmp_path: Path) -> None:
    """Plan: 'fish may travel has (sic) many' -> non_speech_brackets candidate with span (sic) and correction ''."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "fish may travel has (sic) many"},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "non_speech_brackets_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    sic_c = next((c for c in candidates if c.get("span") == "(sic)"), None)
    assert sic_c is not None, [c.get("span") for c in candidates]
    assert [co.get("text") for co in sic_c.get("corrections", []) if "text" in co] == [
        ""
    ]


def test_build_rule_candidates_non_speech_noon_recess(tmp_path: Path) -> None:
    """Fixture 'lunch counsel. [Noon Recess] Mr. Eggers,' produces non_speech_brackets candidate with empty correction."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "lunch counsel. [Noon Recess] Mr. Eggers,"},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "non_speech_brackets_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    recess_cand = next(
        (c for c in candidates if c.get("span") == "[Noon Recess]"), None
    )
    assert recess_cand is not None, [c.get("span") for c in candidates]
    texts = [
        co.get("text") for co in recess_cand.get("corrections", []) if "text" in co
    ]
    assert "" in texts, texts


def test_build_rule_candidates_dash_ellipsis_output(tmp_path: Path) -> None:
    """Fixture with ellipsis …; assert dash rule emits it and correction is -."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "word\u2026word"},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "dash_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    ellipsis_cand = next((c for c in candidates if "\u2026" in c.get("span", "")), None)
    assert ellipsis_cand is not None, [c.get("span") for c in candidates]
    texts = [
        co.get("text") for co in ellipsis_cand.get("corrections", []) if "text" in co
    ]
    assert texts == ["-"], texts


def test_build_rule_candidates_ordinals_output(tmp_path: Path) -> None:
    """Fixture with 37th and 3rd; assert ordinals_candidates.json with thirty seventh, third."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "37th Congress and 3rd Session."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "ordinals_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    assert data.get("rule_id") == "ordinals"
    candidates = data.get("candidates", [])
    thirty7 = next((c for c in candidates if c.get("span") == "37th"), None)
    third = next((c for c in candidates if c.get("span") == "3rd"), None)
    assert thirty7 is not None, [c.get("span") for c in candidates]
    assert third is not None, [c.get("span") for c in candidates]
    t7_texts = [co.get("text") for co in thirty7.get("corrections", []) if "text" in co]
    t3_texts = [co.get("text") for co in third.get("corrections", []) if "text" in co]
    assert t7_texts == ["thirty seventh"], t7_texts
    assert t3_texts == ["third"], t3_texts


def test_build_rule_candidates_curly_single_quotes_output(tmp_path: Path) -> None:
    """Fixture with curly single quotes; assert open/close_double_quote contain U+2018/U+2019."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "\u2018I object.\u2019"},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    open_data = json.loads((out_dir / "open_double_quote_candidates.json").read_text())
    close_data = json.loads(
        (out_dir / "close_double_quote_candidates.json").read_text()
    )
    open_spans = [c.get("span") for c in open_data.get("candidates", [])]
    close_spans = [c.get("span") for c in close_data.get("candidates", [])]
    assert "\u2018" in open_spans, open_spans
    assert "\u2019" in close_spans, close_spans


def test_build_rule_candidates_laughs_output(tmp_path: Path) -> None:
    """Fixture with (Laughs); assert non_speech_brackets has correction [""]."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "Then (Laughs) and we continued."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "non_speech_brackets_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    laughs_cand = next(
        (c for c in data.get("candidates", []) if "Laughs" in c.get("span", "")),
        None,
    )
    assert laughs_cand is not None
    texts = [
        co.get("text") for co in laughs_cand.get("corrections", []) if "text" in co
    ]
    assert texts == [""], texts


def test_build_rule_candidates_dash_dots_output(tmp_path: Path) -> None:
    """Fixture with ...; assert dash_candidates.json has span ... and correction -."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "word...word"},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "dash_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    dots_cand = next(
        (c for c in data.get("candidates", []) if c.get("span") == "..."), None
    )
    assert dots_cand is not None, [c.get("span") for c in data.get("candidates", [])]
    texts = [co.get("text") for co in dots_cand.get("corrections", []) if "text" in co]
    assert texts == ["-"], texts


def test_build_rule_candidates_decades_1860s_2010s_output(tmp_path: Path) -> None:
    """Fixture with 1860s and 2010s; assert decades_candidates.json has eighteen sixties, twenty tens."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "1860s and 2010s."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "decades_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    c1860 = next((c for c in candidates if c.get("span") == "1860s"), None)
    c2010 = next((c for c in candidates if c.get("span") == "2010s"), None)
    assert c1860 is not None, [c.get("span") for c in candidates]
    assert c2010 is not None, [c.get("span") for c in candidates]
    t1860 = [co.get("text") for co in c1860.get("corrections", []) if "text" in co]
    t2010 = [co.get("text") for co in c2010.get("corrections", []) if "text" in co]
    assert t1860 == ["eighteen sixties"], t1860
    assert t2010 == ["twenty tens"], t2010


# Edited by Cursor (ASR normalization rules expansion)
def test_build_rule_candidates_digit_letter_mixed_output(tmp_path: Path) -> None:
    """Fixture with 2d, 640L, 1392(d); assert digit_letter_mixed_candidates.json has spoken corrections."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "See 2d and 640L and 1392(d)."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "digit_letter_mixed_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    assert data.get("rule_id") == "digit_letter_mixed"
    candidates = data.get("candidates", [])
    c2d = next((c for c in candidates if c.get("span") == "2d"), None)
    c640 = next((c for c in candidates if c.get("span") == "640L"), None)
    c1392 = next((c for c in candidates if "1392" in c.get("span", "")), None)
    assert c2d is not None, [c.get("span") for c in candidates]
    assert c640 is not None, [c.get("span") for c in candidates]
    assert c1392 is not None, [c.get("span") for c in candidates]
    t2d = [co.get("text") for co in c2d.get("corrections", []) if "text" in co]
    t640 = [co.get("text") for co in c640.get("corrections", []) if "text" in co]
    t1392 = [co.get("text") for co in c1392.get("corrections", []) if "text" in co]
    assert t2d == ["two dee"], t2d
    assert "six forty ell" in t640, t640
    assert "thirteen ninety two dee" in t1392, t1392


def test_build_rule_candidates_numbered_list_marker_output(tmp_path: Path) -> None:
    """Fixture with list context '1) first' and '5) fifth'; assert numbered_list_marker has one, five."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "Reasons: 1) first point 5) fifth."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "numbered_list_marker_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    assert data.get("rule_id") == "numbered_list_marker"
    candidates = data.get("candidates", [])
    one_cand = next((c for c in candidates if c.get("span") == "1)"), None)
    five_cand = next((c for c in candidates if c.get("span") == "5)"), None)
    assert one_cand is not None, [c.get("span") for c in candidates]
    assert five_cand is not None, [c.get("span") for c in candidates]
    t1 = [co.get("text") for co in one_cand.get("corrections", []) if "text" in co]
    t5 = [co.get("text") for co in five_cand.get("corrections", []) if "text" in co]
    assert t1 == ["one"], t1
    assert t5 == ["five"], t5


def test_build_rule_candidates_numbered_list_comma(tmp_path: Path) -> None:
    """Transcript 'Well, 1), if you assume' produces numbered_list_marker candidate for 1) with correction one."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": "Well, 1), if you assume"}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "numbered_list_marker_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    one_cand = next((c for c in candidates if c.get("span") == "1)"), None)
    assert one_cand is not None, [c.get("span") for c in candidates]
    assert any(co.get("text") == "one" for co in one_cand.get("corrections", []))


def test_build_rule_candidates_numbered_list_followed_by_dash(tmp_path: Path) -> None:
    """Transcript 'in those cases, 1)--' produces numbered_list_marker for 1) with correction one (awareness_brackets_numbered)."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": "No. Well, in those cases, 1)--"}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "numbered_list_marker_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    one_cand = next((c for c in candidates if c.get("span") == "1)"), None)
    assert one_cand is not None, [c.get("span") for c in candidates]
    assert any(co.get("text") == "one" for co in one_cand.get("corrections", []))


def test_build_rule_candidates_numbered_list_followed_by_dots(tmp_path: Path) -> None:
    """Transcript 'and 2)...' produces numbered_list_marker for 2) with correction two."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {
                        "index": 0,
                        "text": "that's 1) necessary, and 2)... and I think this is important.",
                    }
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "numbered_list_marker_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    two_cand = next((c for c in candidates if c.get("span") == "2)"), None)
    assert two_cand is not None, [c.get("span") for c in candidates]
    assert any(co.get("text") == "two" for co in two_cand.get("corrections", []))


def test_build_rule_candidates_numbered_list_followed_by_colon(tmp_path: Path) -> None:
    """Transcript 'section (a) 42):' produces numbered_list_marker for 42) with correction forty two."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {
                        "index": 0,
                        "text": 'quoting from section (a) 42): "Any person who ordered..."',
                    }
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "numbered_list_marker_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    cand = next((c for c in candidates if c.get("span") == "42)"), None)
    assert cand is not None, [c.get("span") for c in candidates]
    assert any(co.get("text") == "forty two" for co in cand.get("corrections", []))


def test_build_rule_candidates_numbered_list_followed_by_paren(tmp_path: Path) -> None:
    """Transcript 'section 67)(c)' produces numbered_list_marker for 67) with correction sixty seven."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {
                        "index": 0,
                        "text": "The problem was dealt with in section 67)(c), where entities like that were said to be treated.",
                    }
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "numbered_list_marker_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    cand = next((c for c in candidates if c.get("span") == "67)"), None)
    assert cand is not None, [c.get("span") for c in candidates]
    assert any(co.get("text") == "sixty seven" for co in cand.get("corrections", []))


def test_build_rule_candidates_numbered_list_preceded_by_endash(tmp_path: Path) -> None:
    """Transcript 'page A (26-10).' produces numbered_list_marker for 10) with correction ten (en-dash before 10)."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    # en-dash U+2013 between 26 and 10
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": "It's on page A (26\u201310)."}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "numbered_list_marker_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    cand = next((c for c in candidates if c.get("span") == "10)"), None)
    assert cand is not None, [c.get("span") for c in candidates]
    assert any(co.get("text") == "ten" for co in cand.get("corrections", []))


# Edited by Cursor (TDD plan item 10: timestamp non-speech)
def test_build_rule_candidates_non_speech_audio_cut(tmp_path: Path) -> None:
    """Fixture with '(audio abruptly cut 00:35:34-00:35:40)' -> non_speech_brackets includes it with correction ''."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    span_text = "(audio abruptly cut 00:35:34-00:35:40)"
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": f"Silence {span_text} then resumed."}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "non_speech_brackets_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    cand = next((c for c in candidates if c.get("span") == span_text), None)
    assert cand is not None, [c.get("span") for c in candidates]
    texts = [co.get("text") for co in cand.get("corrections", []) if "text" in co]
    assert "" in texts, texts


# Edited by Cursor (TDD plan item 9: leading decimal)
def test_build_rule_candidates_leading_decimal(tmp_path: Path) -> None:
    """Fixture '.06 and .31' -> leading_decimal_candidates with expected spans/corrections."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": ".06 and .31"}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "leading_decimal_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    span_06 = next((c for c in candidates if c.get("span") == ".06"), None)
    span_31 = next((c for c in candidates if c.get("span") == ".31"), None)
    assert span_06 is not None and span_31 is not None, [
        c.get("span") for c in candidates
    ]
    texts_06 = [co.get("text") for co in span_06.get("corrections", []) if "text" in co]
    texts_31 = [co.get("text") for co in span_31.get("corrections", []) if "text" in co]
    assert "point oh six" in texts_06, texts_06
    assert "point three one" in texts_31 and "point thirty one" in texts_31, texts_31


# Edited by Cursor (TDD plan item 7: editorial dollar)
def test_build_rule_candidates_editorial_dollar(tmp_path: Path) -> None:
    """Fixture with '$<forty-two thousand> [= 42,000]' -> editorial_dollar candidates with both corrections."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "Amount $<forty-two thousand> [= 42,000]."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "editorial_dollar_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    span_val = "$<forty-two thousand> [= 42,000]"
    cand = next((c for c in candidates if c.get("span") == span_val), None)
    assert cand is not None, [c.get("span") for c in candidates]
    texts = [co.get("text") for co in cand.get("corrections", []) if "text" in co]
    assert (
        "forty-two thousand dollars" in texts and "forty-two thousand dollar" in texts
    ), texts


# Edited by Cursor (TDD plan item 6: known names MacKinnon, LeMaistre)
def test_build_rule_candidates_known_names_mackinnon_lemaistre(tmp_path: Path) -> None:
    """Fixture 'MacKinnon and LeMaistre' -> known_names_candidates contains those spans."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": "MacKinnon and LeMaistre"}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "known_names_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    spans = [c.get("span") for c in candidates]
    assert "MacKinnon" in spans, spans
    assert "LeMaistre" in spans, spans


def test_build_rule_candidates_known_names_lapenta(tmp_path: Path) -> None:
    """Transcript containing LaPenta produces known_names candidate (identity)."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": "Counsel LaPenta argued."}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "known_names_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    spans = [c.get("span") for c in candidates]
    assert "LaPenta" in spans, spans


def test_build_rule_candidates_known_names_dupont(tmp_path: Path) -> None:
    """Transcript containing DuPoint produces known_names candidate (identity)."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": "DuPoint and DuPage County."}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "known_names_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    spans = [c.get("span") for c in candidates]
    assert "DuPoint" in spans, spans
    assert "DuPage" in spans, spans


def test_build_rule_candidates_all_caps_accept(tmp_path: Path) -> None:
    """Transcript containing CERCLA produces all_caps_accept candidate (identity)."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": "Under CERCLA that is preempted."}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "all_caps_accept_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    cand = next((c for c in candidates if c.get("span") == "CERCLA"), None)
    assert cand is not None, [c.get("span") for c in candidates]
    assert cand.get("corrections") == [{"text": "CERCLA"}]


# Plan item 7: half symbol ½
def test_build_rule_candidates_half_number(tmp_path: Path) -> None:
    """Fixture 'below to 12½%' yields half_number candidate with correction twelve and a half percent."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": "below to 12½%."}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "half_number_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    cand = next((c for c in candidates if "½" in (c.get("span") or "")), None)
    assert cand is not None, [c.get("span") for c in candidates]
    assert any(
        "twelve and a half percent" in (co.get("text") or "")
        for co in cand.get("corrections", [])
    ), cand.get("corrections")


def test_build_rule_candidates_fraction(tmp_path: Path) -> None:
    """Transcript with 1/3 or 2/5 or ½ or ¾ produces fraction candidate with expected corrections."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "from 1/3 up to ½ and ¾ of a gram, take 2/5."}
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "fraction_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    spans = [c.get("span") for c in candidates]
    assert "1/3" in spans, spans
    assert "2/5" in spans, spans
    assert "¾" in spans, spans
    cand_three_quarters = next(c for c in candidates if c.get("span") == "¾")
    assert any(
        "three fourths" in (co.get("text") or "")
        or "three quarters" in (co.get("text") or "")
        for co in cand_three_quarters.get("corrections", [])
    ), cand_three_quarters.get("corrections")
    cand_13 = next(c for c in candidates if c.get("span") == "1/3")
    assert any(
        "one third" in (co.get("text") or "") for co in cand_13.get("corrections", [])
    )
    cand_25 = next(c for c in candidates if c.get("span") == "2/5")
    assert any(
        "two fifths" in (co.get("text") or "") for co in cand_25.get("corrections", [])
    )


def test_build_rule_candidates_half_number_times(tmp_path: Path) -> None:
    """Fixture 'sold at 18 ½ times' yields half_number candidate with eighteen and a half times."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": "sold at 18 ½ times earnings."}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "half_number_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    cand = next(
        (
            c
            for c in candidates
            if "18" in (c.get("span") or "") and "times" in (c.get("span") or "")
        ),
        None,
    )
    assert cand is not None, [c.get("span") for c in candidates]
    texts = [co.get("text") for co in cand.get("corrections", []) if "text" in co]
    assert any("eighteen and a half times" in t for t in texts), texts


# Plan item 6: dual notation
def test_build_rule_candidates_dual_notation(tmp_path: Path) -> None:
    """Fixture with '<thirty> [= 30]' yields dual_notation_candidates with correction thirty."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": "See <thirty> [= 30] here."}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "dual_notation_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    span_val = "<thirty> [= 30]"
    cand = next((c for c in candidates if c.get("span") == span_val), None)
    assert cand is not None, [c.get("span") for c in candidates]
    texts = [co.get("text") for co in cand.get("corrections", []) if "text" in co]
    assert "thirty" in texts, texts


def test_build_rule_candidates_section_header(tmp_path: Path) -> None:
    """Turn ending with all-caps header produces section_header candidate with empty correction."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {
                        "index": 0,
                        "text": "It is late. REBUTTAL ARGUMENT OF MATTHEW D. McGILL",
                    },
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "section_header_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    cand = next(
        (c for c in candidates if "REBUTTAL" in (c.get("span") or "")),
        None,
    )
    assert cand is not None, [c.get("span") for c in candidates]
    texts = [co.get("text") for co in cand.get("corrections", []) if "text" in co]
    assert "" in texts, texts


def test_build_rule_candidates_roman_parens(tmp_path: Path) -> None:
    """Transcript with (ii) and (iv) produces roman_parens candidates with corrections two and four."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {
                        "index": 0,
                        "text": "to have (ii) so that when Romanette (iii) says same as (iv) and (vi)",
                    },
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "roman_parens_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    spans = [c.get("span") for c in candidates]
    assert "(ii)" in spans, spans
    assert "(iv)" in spans, spans
    cand_ii = next(c for c in candidates if c.get("span") == "(ii)")
    assert any(co.get("text") == "two" for co in cand_ii.get("corrections", []))
    cand_iv = next(c for c in candidates if c.get("span") == "(iv)")
    assert any(co.get("text") == "four" for co in cand_iv.get("corrections", []))


def test_build_rule_candidates_letter_roman_clause(tmp_path: Path) -> None:
    """Transcript with '(C)(iii), Your Honor' produces letter_roman_clause candidate with correction 'cee three'."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "If you look at (C)(iii), Your Honor."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "letter_roman_clause_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    spans = [c.get("span") for c in candidates]
    assert "(C)(iii)" in spans, spans
    cand = next(c for c in candidates if c.get("span") == "(C)(iii)")
    assert any(co.get("text") == "cee three" for co in cand.get("corrections", [])), (
        cand.get("corrections", [])
    )


def test_build_rule_candidates_letter_dash(tmp_path: Path) -> None:
    """Transcript with 'to the (R-5), which' and 'to the R-5, which' produce letter_dash_sequence candidates with correction 'ar five'."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "to the (R-5), which and to the R-5, which"},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "letter_dash_sequence_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    spans = [c.get("span") for c in candidates]
    assert "(R-5)" in spans, spans
    assert "R-5" in spans, spans
    for cand in candidates:
        assert any(co.get("text") == "ar five" for co in cand.get("corrections", [])), (
            cand.get("corrections", [])
        )


def test_build_rule_candidates_known_mixed_case(tmp_path: Path) -> None:
    """Transcript containing TikTok produces known_mixed_case_entities candidate (identity)."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": "Seen on TikTok and YouTube."}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "known_mixed_case_entities_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    cand = next((c for c in candidates if c.get("span") == "TikTok"), None)
    assert cand is not None, [c.get("span") for c in candidates]
    assert cand.get("corrections") == [{"text": "TikTok"}]


def test_build_rule_candidates_single_digit_valid_word(tmp_path: Path) -> None:
    """Transcript with n4or, 9put, eviden3ce (word list has nor, put, evidence) produces corrections."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {
                        "index": 0,
                        "text": "act n4or omission when we 9put in eviden3ce",
                    },
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "single_digit_valid_word_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    spans = [c.get("span") for c in candidates]
    assert "n4or" in spans, spans
    cand_nor = next(c for c in candidates if c.get("span") == "n4or")
    assert any(co.get("text") == "nor" for co in cand_nor.get("corrections", []))
    cand_put = next(c for c in candidates if c.get("span") == "9put")
    assert any(co.get("text") == "put" for co in cand_put.get("corrections", []))
    cand_ev = next(c for c in candidates if c.get("span") == "eviden3ce")
    assert any(co.get("text") == "evidence" for co in cand_ev.get("corrections", []))


def test_build_rule_candidates_typo_levenshtein(tmp_path: Path) -> None:
    """Transcript with G1eneral in one turn and General in another produces typo_levenshtein with correction General."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "General Motors and General Electric."},
                    {"index": 1, "text": "a case between G1eneral Ferguson."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "typo_levenshtein_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    cand = next((c for c in candidates if c.get("span") == "G1eneral"), None)
    assert cand is not None, [c.get("span") for c in candidates]
    texts = [co.get("text") for co in cand.get("corrections", []) if "text" in co]
    assert "General" in texts, texts


def test_build_rule_candidates_dual_notation_variants(tmp_path: Path) -> None:
    """Dual notation variants [<X>], <X> [81-523] yield angle content as correction."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {
                        "index": 0,
                        "text": "The savings statute, [<twenty-three oh five point one five>] is unconstitutional.",
                    },
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "dual_notation_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    cand = next(
        (c for c in candidates if "[<" in (c.get("span") or "")),
        None,
    )
    assert cand is not None, [c.get("span") for c in candidates]
    texts = [co.get("text") for co in cand.get("corrections", []) if "text" in co]
    assert any("twenty-three oh five point one five" in t for t in texts), texts


# Plan item 5: special currency
def test_build_rule_candidates_special_currency(tmp_path: Path) -> None:
    """Fixture with '$ 3 billion' and '$ 21 hundred' yields special_currency candidates with both corrections."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "Cost $ 3 billion and $ 21 hundred."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "special_currency_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    c_billion = next(
        (c for c in candidates if "3 billion" in (c.get("span") or "")), None
    )
    c_hundred = next(
        (c for c in candidates if "21 hundred" in (c.get("span") or "")), None
    )
    assert c_billion is not None and c_hundred is not None, [
        c.get("span") for c in candidates
    ]
    t_b = [co.get("text") for co in c_billion.get("corrections", []) if "text" in co]
    t_h = [co.get("text") for co in c_hundred.get("corrections", []) if "text" in co]
    assert "three billion dollars" in t_b and "three billion dollar" in t_b, t_b
    assert "twenty one hundred dollars" in t_h and "twenty one hundred dollar" in t_h, (
        t_h
    )


# Plan item 4: time of day
def test_build_rule_candidates_time_of_day(tmp_path: Path) -> None:
    """Fixture 'at 8:40 and 1:00' yields time_of_day_candidates with expected spans and corrections."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": "At 8:40 and 1:00."}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "time_of_day_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    c840 = next((c for c in candidates if c.get("span") == "8:40"), None)
    c100 = next((c for c in candidates if c.get("span") == "1:00"), None)
    assert c840 is not None and c100 is not None, [c.get("span") for c in candidates]
    t840 = [co.get("text") for co in c840.get("corrections", []) if "text" in co]
    t100 = [co.get("text") for co in c100.get("corrections", []) if "text" in co]
    assert "eight forty" in t840, t840
    assert "one" in t100 and "one oh oh" in t100, t100


# Plan: bracket acronyms (MPSC), (NRDC)
def test_build_rule_candidates_bracket_acronym(tmp_path: Path) -> None:
    """Transcript with (MPSC) and (NRDC) produces bracket_acronym candidates with letter-by-letter corrections."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "See (MPSC) and (NRDC) for that."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "bracket_acronym_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    mpsc_c = next((c for c in candidates if c.get("span") == "(MPSC)"), None)
    nrdc_c = next((c for c in candidates if c.get("span") == "(NRDC)"), None)
    assert mpsc_c is not None and nrdc_c is not None, [
        c.get("span") for c in candidates
    ]
    mpsc_texts = [
        co.get("text") for co in mpsc_c.get("corrections", []) if "text" in (co or {})
    ]
    nrdc_texts = [
        co.get("text") for co in nrdc_c.get("corrections", []) if "text" in (co or {})
    ]
    assert "em pee ess cee" in mpsc_texts, mpsc_texts
    assert "en ar dee cee" in nrdc_texts, nrdc_texts


# Plan: PascalCase accept (CattleAnd, ByteDance)
def test_build_rule_candidates_website_dot(tmp_path: Path) -> None:
    """Transcript with [befairDOTorg,] produces website_dot candidate with 'befair dot org,'."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "visit [befairDOTorg,] for more."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "website_dot_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    cand = next(
        (c for c in candidates if c.get("span") == "[befairDOTorg,]"),
        None,
    )
    assert cand is not None, [c.get("span") for c in candidates]
    texts = [
        co.get("text") for co in cand.get("corrections", []) if "text" in (co or {})
    ]
    assert "befair dot org," in texts, texts


def test_build_rule_candidates_bracket_sentence_unwrap(tmp_path: Path) -> None:
    """Transcript with (which may itself be true) produces bracket_sentence_unwrap with inner text."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {
                        "index": 0,
                        "text": "visual proof of a product claim (which may itself be true) when the test is a sham.",
                    },
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "bracket_sentence_unwrap_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    cand = next(
        (c for c in candidates if c.get("span") == "(which may itself be true)"),
        None,
    )
    assert cand is not None, [c.get("span") for c in candidates]
    texts = [
        co.get("text") for co in cand.get("corrections", []) if "text" in (co or {})
    ]
    assert "which may itself be true" in texts, texts


def test_build_rule_candidates_name_pattern_di(tmp_path: Path) -> None:
    """Transcript with DiBona produces name_pattern_di candidate (identity)."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "Mr. DiBona was deferential."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "name_pattern_di_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    cand = next((c for c in candidates if c.get("span") == "DiBona"), None)
    assert cand is not None, [c.get("span") for c in candidates]
    texts = [
        co.get("text") for co in cand.get("corrections", []) if "text" in (co or {})
    ]
    assert "DiBona" in texts, texts


def test_build_rule_candidates_mixed_case_accept_6plus(tmp_path: Path) -> None:
    """Transcript with PowerEx produces mixed_case_accept_6plus candidate (identity)."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "Petitioner PowerEx was not a foreign state."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "mixed_case_accept_6plus_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    cand = next((c for c in candidates if c.get("span") == "PowerEx"), None)
    assert cand is not None, [c.get("span") for c in candidates]
    texts = [
        co.get("text") for co in cand.get("corrections", []) if "text" in (co or {})
    ]
    assert "PowerEx" in texts, texts


def test_build_rule_candidates_pascal_case_accept(tmp_path: Path) -> None:
    """Transcript with CattleAnd and ByteDance produces pascal_case_accept candidates (identity)."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "CattleAnd and ByteDance here."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "pascal_case_accept_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    cattle = next((c for c in candidates if c.get("span") == "CattleAnd"), None)
    byte_ = next((c for c in candidates if c.get("span") == "ByteDance"), None)
    assert cattle is not None and byte_ is not None, [c.get("span") for c in candidates]
    cattle_texts = [
        co.get("text")
        for co in (cattle.get("corrections") or [])
        if "text" in (co or {})
    ]
    byte_texts = [
        co.get("text")
        for co in (byte_.get("corrections") or [])
        if "text" in (co or {})
    ]
    assert "CattleAnd" in cattle_texts, cattle_texts
    assert "ByteDance" in byte_texts, byte_texts


# Plan: currency [$] N raw number
def test_build_rule_candidates_special_currency_raw(tmp_path: Path) -> None:
    """Transcript with [$] 43,000 and [$] 86,000 produces special_currency candidates with spoken form."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "Costs [$] 43,000 and [$] 86,000."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "special_currency_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    c43 = next((c for c in candidates if c.get("span") == "[$] 43,000"), None)
    c86 = next((c for c in candidates if c.get("span") == "[$] 86,000"), None)
    assert c43 is not None and c86 is not None, [c.get("span") for c in candidates]
    texts43 = [
        co.get("text") for co in c43.get("corrections", []) if "text" in (co or {})
    ]
    texts86 = [
        co.get("text") for co in c86.get("corrections", []) if "text" in (co or {})
    ]
    assert any("forty three thousand" in t for t in texts43), texts43
    assert any("eighty six thousand" in t for t in texts86), texts86


# Plan: inline typo word[: correction]
def test_build_rule_candidates_inline_typo(tmp_path: Path) -> None:
    """Transcript with interaconnection[:interconnection] produces inline_typo candidate with correction interconnection."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {
                        "index": 0,
                        "text": "the rate of interaconnection[:interconnection] from",
                    },
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "inline_typo_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    cand = next(
        (
            c
            for c in candidates
            if "interaconnection[:interconnection]" in (c.get("span") or "")
        ),
        None,
    )
    assert cand is not None, [c.get("span") for c in candidates]
    texts = [
        co.get("text") for co in cand.get("corrections", []) if "text" in (co or {})
    ]
    assert "interconnection" in texts, texts


# Plan: short mixed-case acronym (DoD, DiRe)
def test_build_rule_candidates_short_mixed_acronym(tmp_path: Path) -> None:
    """Transcript with DoD and DiRe produces short_mixed_acronym candidates with letter-by-letter corrections."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "The DoD and DiRe cases."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "short_mixed_acronym_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    dod_cand = next((c for c in candidates if c.get("span") == "DoD"), None)
    dire_cand = next((c for c in candidates if c.get("span") == "DiRe"), None)
    assert dod_cand is not None and dire_cand is not None, [
        c.get("span") for c in candidates
    ]
    dod_texts = [
        co.get("text") for co in dod_cand.get("corrections", []) if "text" in co
    ]
    dire_texts = [
        co.get("text") for co in dire_cand.get("corrections", []) if "text" in co
    ]
    assert "dee oh dee" in dod_texts, dod_texts
    assert "dee eye ar ee" in dire_texts, dire_texts


# Plan item 3: common acronym PhD
def test_build_rule_candidates_common_acronym_phd(tmp_path: Path) -> None:
    """Fixture with 'PhD' produces common_acronym candidate with correction pee aych dee."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": "She has a PhD in law."}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "common_acronym_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    phd_cand = next((c for c in candidates if c.get("span") == "PhD"), None)
    assert phd_cand is not None, [c.get("span") for c in candidates]
    texts = [co.get("text") for co in phd_cand.get("corrections", []) if "text" in co]
    assert "pee aych dee" in texts, texts


# Plan item 2: title abbreviations
def test_build_rule_candidates_title_abbreviation(tmp_path: Path) -> None:
    """Fixture 'Mr. Smith and Dr. Jones' yields title_abbreviation_candidates with Mr., Dr. and corrections Mister, Doctor."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": "Mr. Smith and Dr. Jones"}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "title_abbreviation_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    mr_cand = next((c for c in candidates if c.get("span") == "Mr."), None)
    dr_cand = next((c for c in candidates if c.get("span") == "Dr."), None)
    assert mr_cand is not None and dr_cand is not None, [
        c.get("span") for c in candidates
    ]
    mr_texts = [co.get("text") for co in mr_cand.get("corrections", []) if "text" in co]
    dr_texts = [co.get("text") for co in dr_cand.get("corrections", []) if "text" in co]
    assert "Mister" in mr_texts, mr_texts
    assert "Doctor" in dr_texts, dr_texts


# Plan item 1: DeShaney
def test_build_rule_candidates_known_names_deshaney(tmp_path: Path) -> None:
    """Fixture containing 'DeShaney' yields known_names_candidates with that span."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": "See DeShaney and others."}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "known_names_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    spans = [c.get("span") for c in candidates]
    assert "DeShaney" in spans, spans


# Edited by Cursor (TDD plan item 5: double-letter parens (ph))
def test_build_rule_candidates_double_letter_parens(tmp_path: Path) -> None:
    """Fixture 'See (ph).' -> candidates with span '(ph)' and correction 'pee aych'."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [{"index": 0, "text": "See (ph)."}],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "double_letter_parens_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    ph_cand = next((c for c in candidates if c.get("span") == "(ph)"), None)
    assert ph_cand is not None, [c.get("span") for c in candidates]
    texts = [co.get("text") for co in ph_cand.get("corrections", []) if "text" in co]
    assert "pee aych" in texts, texts


# Edited by Cursor (TDD plan item 4: digit-letter F2A, 1395(ff))
def test_build_rule_candidates_digit_letter_f2a_1395ff(tmp_path: Path) -> None:
    """Fixture 'F2A and 1395(ff)' -> digit_letter_mixed_candidates has those spans."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "F2A and 1395(ff)."},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "digit_letter_mixed_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    spans = [c.get("span") for c in candidates]
    assert "F2A" in spans, spans
    assert "1395(ff)" in spans, spans


# Edited by Cursor (TDD plan item 1: symbols and currency)
def test_build_rule_candidates_symbols_currency(tmp_path: Path) -> None:
    """Fixture with '§ §1519 © £ £40'; assert currency/symbol candidates and £40 both corrections."""
    transcripts_dir = tmp_path / "transcripts"
    transcripts_dir.mkdir()
    fixture = transcripts_dir / "sample" / "oral_argument.json"
    fixture.parent.mkdir(parents=True)
    fixture.write_text(
        json.dumps(
            {
                "metadata": {},
                "turns": [
                    {"index": 0, "text": "§ §1519 © £ £40"},
                ],
            },
            indent=2,
        )
    )
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    _run_build_rule_candidates(
        transcripts_dir, out_dir, cwd=Path(__file__).resolve().parents[1]
    )
    path = out_dir / "currency_candidates.json"
    assert path.exists(), list(out_dir.iterdir())
    data = json.loads(path.read_text())
    candidates = data.get("candidates", [])
    pound40 = next((c for c in candidates if c.get("span") == "£40"), None)
    assert pound40 is not None, [c.get("span") for c in candidates]
    texts = [co.get("text") for co in pound40.get("corrections", []) if "text" in co]
    assert "forty pounds" in texts and "forty pound" in texts, texts
