# Generated by Claude
"""Tests for HuggingFace loader wrappers.

These tests verify that the HF loader functions correctly delegate to
load_dataset with the appropriate parameters. Uses parquet auto-discovery
for datasets v4.x compatibility.
"""

from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest


class TestLoadSimpleHf:
    """Tests for load_simple_hf function."""

    def test_raises_when_dataset_not_found(self, tmp_path: Path) -> None:
        """Raises FileNotFoundError when dataset doesn't exist."""
        from oyez_sa_asr.loaders import load_simple_hf  # noqa: PLC0415

        with pytest.raises(FileNotFoundError, match="Dataset not found"):
            load_simple_hf("lt1m", data_dir=tmp_path)


class TestLoadRawHf:
    """Tests for load_raw_hf function."""

    def test_calls_load_dataset(self) -> None:
        """Calls load_dataset with correct path."""
        with patch("datasets.load_dataset") as mock_load:
            mock_ds = MagicMock()
            mock_ds.__getitem__ = MagicMock(return_value=MagicMock())
            mock_load.return_value = mock_ds

            from oyez_sa_asr.loaders import load_raw_hf  # noqa: PLC0415

            load_raw_hf()

            mock_load.assert_called_once()

    def test_passes_streaming_parameter(self) -> None:
        """Passes streaming parameter to load_dataset."""
        with patch("datasets.load_dataset") as mock_load:
            mock_ds = MagicMock()
            mock_load.return_value = mock_ds

            from oyez_sa_asr.loaders import load_raw_hf  # noqa: PLC0415

            load_raw_hf(streaming=True)

            call_kwargs = mock_load.call_args.kwargs
            assert call_kwargs.get("streaming") is True


class TestLoadFlexHf:
    """Tests for load_flex_hf function."""

    def test_calls_load_dataset_with_config(self) -> None:
        """Calls load_dataset with config parameter."""
        with patch("datasets.load_dataset") as mock_load:
            mock_load.return_value = MagicMock()

            from oyez_sa_asr.loaders import load_flex_hf  # noqa: PLC0415

            load_flex_hf("recordings")

            args = mock_load.call_args.args
            assert "recordings" in args

    def test_calls_load_dataset_with_utterances_config(self) -> None:
        """Calls load_dataset with utterances config."""
        with patch("datasets.load_dataset") as mock_load:
            mock_load.return_value = MagicMock()

            from oyez_sa_asr.loaders import load_flex_hf  # noqa: PLC0415

            load_flex_hf("utterances")

            args = mock_load.call_args.args
            assert "utterances" in args

    def test_passes_streaming_parameter(self) -> None:
        """Passes streaming parameter to load_dataset."""
        with patch("datasets.load_dataset") as mock_load:
            mock_load.return_value = MagicMock()

            from oyez_sa_asr.loaders import load_flex_hf  # noqa: PLC0415

            load_flex_hf("recordings", streaming=True)

            call_kwargs = mock_load.call_args.kwargs
            assert call_kwargs.get("streaming") is True
