# Generated by Cursor
"""Tests for scripts/typo_distances.py (unified format read/write)."""

import json
import subprocess
import sys
from pathlib import Path


def _run_typo_distances(
    input_path: Path, output_path: Path, cwd: Path | None = None
) -> dict:
    """Run typo_distances.py with -i and -o; return output JSON."""
    root = cwd or Path(__file__).resolve().parents[1]
    cmd = [
        sys.executable,
        "scripts/typo_distances.py",
        "-i",
        str(input_path),
        "-o",
        str(output_path),
    ]
    result = subprocess.run(  # noqa: S603
        cmd,
        capture_output=True,
        text=True,
        cwd=root,
        check=False,
    )
    assert result.returncode == 0, (result.stdout, result.stderr)
    return json.loads(output_path.read_text())


def test_reads_unified_format_preserves_rule_id_and_rule_name(tmp_path: Path) -> None:
    """When input has rule_id and rule_name, output preserves them."""
    inp = tmp_path / "in.json"
    inp.write_text(
        json.dumps(
            {
                "rule_id": "transcription_typos",
                "rule_name": "Transcription typos (Rule 0)",
                "candidates": [
                    {
                        "span": "example",
                        "corrections": [{"text": "example"}],
                        "count": 1,
                        "occurrences": [
                            {"path": "a.json", "line_num": 1, "start_index": 0}
                        ],
                        "occurrences_truncated": False,
                    },
                ],
            },
            indent=2,
        )
    )
    out = tmp_path / "out.json"
    data = _run_typo_distances(inp, out, cwd=Path(__file__).resolve().parents[1])
    assert data.get("rule_id") == "transcription_typos"
    assert "rule_name" in data


def test_written_output_has_span_and_start_index_in_occurrences(tmp_path: Path) -> None:
    """Written output uses span and every occurrence has path, line_num, start_index."""
    inp = tmp_path / "in.json"
    inp.write_text(
        json.dumps(
            {
                "rule_id": "transcription_typos",
                "rule_name": "Transcription typos (Rule 0)",
                "candidates": [
                    {
                        "span": "that",
                        "corrections": [{"text": "that"}],
                        "count": 1,
                        "occurrences": [
                            {"path": "b.json", "line_num": 2, "start_index": 5}
                        ],
                        "occurrences_truncated": False,
                    },
                ],
            },
            indent=2,
        )
    )
    out = tmp_path / "out.json"
    data = _run_typo_distances(inp, out, cwd=Path(__file__).resolve().parents[1])
    assert data["candidates"][0]["span"] == "that"
    occ = data["candidates"][0]["occurrences"][0]
    assert "path" in occ and "line_num" in occ and "start_index" in occ
    assert occ["start_index"] == 5


def test_reads_legacy_format_writes_unified(tmp_path: Path) -> None:
    """When input has typo and correction (legacy), output has span and distances."""
    inp = tmp_path / "in.json"
    inp.write_text(
        json.dumps(
            {
                "candidates": [
                    {
                        "typo": "the",
                        "correction": "the",
                        "count": 1,
                        "occurrences": [{"path": "c.json", "line_num": 1}],
                    },
                ],
            },
            indent=2,
        )
    )
    out = tmp_path / "out.json"
    data = _run_typo_distances(inp, out, cwd=Path(__file__).resolve().parents[1])
    # Output should have span (from typo) and distances
    c = data["candidates"][0]
    assert c.get("span") == "the" or c.get("typo") == "the"
    assert "keyboard_dist" in c or any(
        "keyboard_dist" in corr for corr in c.get("corrections", [])
    )
    # Occurrences should have start_index when written (script may add default)
    occs = c.get("occurrences", [])
    assert occs
    for occ in occs:
        assert "path" in occ and "line_num" in occ
