# Generated by Claude
"""Tests for SpeakerProfile dataclass."""

import tempfile
from pathlib import Path

from oyez_sa_asr.speaker_models import SpeakerProfile


class TestSpeakerProfile:
    """Tests for SpeakerProfile dataclass."""

    def test_create_empty(self) -> None:
        """Create empty profile."""
        profile = SpeakerProfile(id=123, name="John Smith")
        assert profile.id == 123
        assert profile.name == "John Smith"
        assert profile.name_slug == "john_smith"
        assert profile.role == "other"  # Default before finalize
        assert profile.recordings == []
        assert profile.cases == set()

    def test_add_appearance(self) -> None:
        """Add recording appearance."""
        profile = SpeakerProfile(id=123, name="John Smith")
        profile.add_appearance(
            term="2024",
            docket="23-1234",
            case_name="Smith v. Jones",
            transcript_type="oral_argument",
            turns=10,
            duration_seconds=120.5,
            word_count=500,
        )
        assert len(profile.recordings) == 1
        assert profile.recordings[0].term == "2024"
        assert "2024/23-1234" in profile.cases

    def test_totals_aggregation(self) -> None:
        """Aggregate totals correctly."""
        profile = SpeakerProfile(id=123, name="John Smith")
        profile.add_appearance(
            term="2024",
            docket="23-1234",
            case_name="Case 1",
            transcript_type="oral_argument",
            turns=10,
            duration_seconds=100.0,
            word_count=500,
        )
        profile.add_appearance(
            term="2024",
            docket="23-5678",
            case_name="Case 2",
            transcript_type="oral_argument",
            turns=20,
            duration_seconds=200.0,
            word_count=1000,
        )
        totals = profile.get_totals()
        assert totals["recordings"] == 2
        assert totals["cases"] == 2
        assert totals["turns"] == 30
        assert totals["duration_seconds"] == 300.0
        assert totals["word_count"] == 1500
        assert totals["avg_words_per_turn"] == 50.0

    def test_by_term_aggregation(self) -> None:
        """Aggregate by term correctly."""
        profile = SpeakerProfile(id=123, name="John Smith")
        profile.add_appearance(
            term="2023",
            docket="22-1234",
            case_name="Case 1",
            transcript_type="oral_argument",
            turns=10,
            duration_seconds=100.0,
            word_count=500,
        )
        profile.add_appearance(
            term="2024",
            docket="23-5678",
            case_name="Case 2",
            transcript_type="oral_argument",
            turns=20,
            duration_seconds=200.0,
            word_count=1000,
        )
        by_term = profile.get_by_term()
        assert "2023" in by_term
        assert "2024" in by_term
        assert by_term["2023"]["turns"] == 10
        assert by_term["2024"]["turns"] == 20

    def test_first_last_appearance(self) -> None:
        """Track first and last appearance dates."""
        profile = SpeakerProfile(id=123, name="John Smith")
        profile.update_appearance_dates("2020-10-05")
        profile.update_appearance_dates("2024-01-15")
        profile.update_appearance_dates("2022-06-20")

        assert profile.first_appearance == "2020-10-05"
        assert profile.last_appearance == "2024-01-15"

    def test_to_dict(self) -> None:
        """Convert to full dictionary."""
        profile = SpeakerProfile(id=123, name="Test Speaker")
        profile.add_appearance(
            term="2024",
            docket="23-1234",
            case_name="Test Case",
            transcript_type="oral_argument",
            turns=10,
            duration_seconds=100.0,
            word_count=500,
        )
        profile.update_appearance_dates("2024-01-15")
        profile.finalize()

        result = profile.to_dict()
        assert result["id"] == 123
        assert result["name"] == "Test Speaker"
        assert result["name_slug"] == "test_speaker"
        assert result["role"] == "other"
        assert result["first_appearance"] == "2024-01-15"
        assert result["last_appearance"] == "2024-01-15"
        assert "totals" in result
        assert "by_term" in result
        assert "recordings" in result
        assert "cases" in result

    def test_save_to_other_subdir(self) -> None:
        """Save non-justice to other subdirectory."""
        profile = SpeakerProfile(id=123, name="Test Speaker")
        profile.add_appearance(
            term="2024",
            docket="23-1234",
            case_name="Test Case",
            transcript_type="oral_argument",
            turns=10,
            duration_seconds=100.0,
            word_count=500,
        )

        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir)
            saved_path = profile.save(output_dir)

            assert saved_path.exists()
            assert saved_path.parent.name == "other"
            assert saved_path.name == "123_test_speaker.json"

    def test_save_to_justices_subdir(self) -> None:
        """Save justice to justices subdirectory."""
        profile = SpeakerProfile(id=456, name="Justice Test")

        # Add enough appearances to be detected as justice (200+ cases, 5+ terms)
        for term in ["2018", "2019", "2020", "2021", "2022", "2023"]:
            for i in range(40):
                profile.add_appearance(
                    term=term,
                    docket=f"{term[-2:]}-{i}",
                    case_name=f"Case {i}",
                    transcript_type="oral_argument",
                    turns=5,
                    duration_seconds=100.0,
                    word_count=500,
                )

        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir)
            saved_path = profile.save(output_dir)

            assert saved_path.exists()
            assert saved_path.parent.name == "justices"
            assert profile.role == "justice"

    def test_get_filename(self) -> None:
        """Generate correct filename."""
        profile = SpeakerProfile(id=15049, name="John G. Roberts, Jr.")
        assert profile.get_filename() == "15049_john_g_roberts_jr.json"

    def test_update_appearance_dates_with_empty_string(self) -> None:
        """Should return early when date_str is empty (line 134)."""
        profile = SpeakerProfile(id=123, name="Test Speaker")
        profile.update_appearance_dates("2024-01-15")
        original_first = profile.first_appearance
        original_last = profile.last_appearance

        # Update with empty string - should return early
        profile.update_appearance_dates("")
        # Note: update_appearance_dates expects str, not None, so we skip None test

        # Dates should remain unchanged
        assert profile.first_appearance == original_first
        assert profile.last_appearance == original_last

    def test_detect_role_checks_existing_justice_file(self) -> None:
        """Should check for existing justice files (lines 163-165)."""
        profile = SpeakerProfile(id=123, name="Test Speaker")
        # Don't add enough appearances to be auto-detected as justice

        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir)
            justices_dir = output_dir / "justices"
            justices_dir.mkdir()

            # Create an existing justice file for this speaker
            (justices_dir / "123_test_speaker.json").write_text('{"id": 123}')

            # Should detect as justice based on existing file
            role = profile.detect_role(output_dir)
            assert role == "justice"

    def test_save_removes_old_file_when_moving_to_justices(self) -> None:
        """Should remove old file when moving from other/ to justices/ (line 245)."""
        profile = SpeakerProfile(id=123, name="Test Speaker")
        profile.add_appearance(
            term="2024",
            docket="23-1234",
            case_name="Test Case",
            transcript_type="oral_argument",
            turns=10,
            duration_seconds=100.0,
            word_count=500,
        )

        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir)
            other_dir = output_dir / "other"
            other_dir.mkdir()

            # Save to other/ first
            old_path = profile.save(output_dir)
            assert old_path.exists()
            assert old_path.parent.name == "other"

            # Add enough appearances to become a justice
            for term in ["2018", "2019", "2020", "2021", "2022"]:
                for i in range(50):
                    profile.add_appearance(
                        term=term,
                        docket=f"{term[-2:]}-{i}",
                        case_name=f"Case {i}",
                        transcript_type="oral_argument",
                        turns=5,
                        duration_seconds=100.0,
                        word_count=500,
                    )

            # Save again - should move to justices/ and remove old file
            new_path = profile.save(output_dir)
            assert new_path.exists()
            assert new_path.parent.name == "justices"
            # Old file should be removed
            assert not old_path.exists()
