# Generated by Claude
"""TDD tests for audio_utils module using PyAV."""

import math
import tempfile
from pathlib import Path

import numpy as np
import pytest

from oyez_sa_asr.audio_utils import get_audio_metadata, load_audio, save_audio


def make_sine(
    freq: float = 440.0, sr: int = 16000, dur: float = 0.5, ch: int = 1
) -> np.ndarray:
    """Generate a sine wave."""
    t = np.linspace(0, dur, int(sr * dur), dtype=np.float32)
    sine = np.sin(2 * math.pi * freq * t)
    return sine if ch == 1 else np.stack([sine] * ch, axis=0)


def mse(a: np.ndarray, b: np.ndarray) -> float:
    """Compute MSE."""
    return float(np.mean((a - b) ** 2))


class TestFLACRoundTrip:
    """Test FLAC format save/load round-trip."""

    def test_mono(self) -> None:
        """Mono FLAC round-trip."""
        sr, samples = 16000, make_sine(sr=16000, dur=0.5, ch=1)
        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / "mono.flac"
            save_audio(samples, sr, path)
            loaded, loaded_sr = load_audio(path)
            assert loaded_sr == sr and loaded.ndim == 2 and loaded.shape[0] == 1
            assert mse(samples, loaded.squeeze(0)) < 1e-6

    def test_stereo(self) -> None:
        """Stereo FLAC round-trip."""
        sr, samples = 44100, make_sine(sr=44100, dur=0.3, ch=2)
        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / "stereo.flac"
            save_audio(samples, sr, path)
            loaded, loaded_sr = load_audio(path)
            assert loaded_sr == sr and loaded.shape == samples.shape
            assert mse(samples, loaded) < 1e-6

    def test_24bit(self) -> None:
        """24-bit FLAC preserves precision."""
        sr, samples = 48000, make_sine(sr=48000, dur=0.2) * 0.001
        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / "24bit.flac"
            save_audio(samples, sr, path, bits_per_sample=24)
            loaded, _ = load_audio(path)
            assert mse(samples, loaded.squeeze(0)) < 1e-10


class TestMP3RoundTrip:
    """Test MP3 format."""

    def test_mono(self) -> None:
        """MP3 round-trip."""
        sr, samples = 44100, make_sine(sr=44100, dur=0.5, ch=1)
        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / "mono.mp3"
            save_audio(samples, sr, path)
            loaded, loaded_sr = load_audio(path)
            assert abs(loaded_sr - sr) <= 1
            assert mse(samples, loaded.squeeze(0)[: len(samples)]) < 0.01


class TestOGGRoundTrip:
    """Test OGG/Vorbis format."""

    def test_mono(self) -> None:
        """OGG round-trip."""
        sr, samples = 44100, make_sine(sr=44100, dur=0.5, ch=1)
        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / "mono.ogg"
            save_audio(samples, sr, path)
            loaded, loaded_sr = load_audio(path)
            assert loaded_sr == sr
            assert mse(samples, loaded.squeeze(0)[: len(samples)]) < 0.01


class TestEdgeCases:
    """Test edge cases."""

    def test_silence(self) -> None:
        """Silence round-trip."""
        sr, samples = 16000, np.zeros(8000, dtype=np.float32)
        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / "silence.flac"
            save_audio(samples, sr, path)
            loaded, _ = load_audio(path)
            assert np.allclose(loaded, 0.0, atol=1e-6)

    def test_clipping(self) -> None:
        """Values outside [-1, 1] clamped."""
        sr, samples = 16000, np.array([1.5, -1.5, 0.5, -0.5], dtype=np.float32)
        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / "clipped.flac"
            save_audio(samples, sr, path)
            loaded, _ = load_audio(path)
            assert np.all(loaded <= 1.0 + 1e-6) and np.all(loaded >= -1.0 - 1e-6)

    def test_format_inference(self) -> None:
        """Format inferred from extension."""
        sr, samples = 16000, make_sine(sr=16000, dur=0.1)
        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / "inferred.flac"
            save_audio(samples, sr, path)
            loaded, _ = load_audio(path)
            assert loaded.shape[1] == len(samples)


class TestWAVRoundTrip:
    """Test WAV format."""

    def test_mono(self) -> None:
        """WAV round-trip."""
        sr, samples = 44100, make_sine(sr=44100, dur=0.2, ch=1)
        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / "mono.wav"
            save_audio(samples, sr, path)
            loaded, loaded_sr = load_audio(path)
            assert loaded_sr == sr
            assert mse(samples, loaded.squeeze(0)[: len(samples)]) < 1e-4


class TestFLAC16Bit:
    """Test 16-bit FLAC format."""

    def test_16bit(self) -> None:
        """16-bit FLAC round-trip."""
        sr, samples = 16000, make_sine(sr=16000, dur=0.2, ch=1)
        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / "16bit.flac"
            save_audio(samples, sr, path, bits_per_sample=16)
            loaded, loaded_sr = load_audio(path)
            assert loaded_sr == sr
            assert mse(samples, loaded.squeeze(0)) < 1e-4


class TestUnsupportedFormat:
    """Test unsupported format error."""

    def test_raises(self) -> None:
        """Unsupported format raises ValueError."""
        sr, samples = 16000, make_sine(sr=16000, dur=0.1)
        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / "test.xyz"
            with pytest.raises(ValueError, match="Unsupported format"):
                save_audio(samples, sr, path)


class TestAudioMetadata:
    """Test get_audio_metadata() function."""

    def test_mp3_metadata(self) -> None:
        """Extract metadata from MP3 file."""
        sr, samples = 44100, make_sine(sr=44100, dur=0.5, ch=1)
        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / "test.mp3"
            save_audio(samples, sr, path)
            meta = get_audio_metadata(path)
            assert meta["format"] == "mp3"
            assert meta["sample_rate"] == sr
            assert meta["channels"] == 1
            dur = float(meta["duration"])  # type: ignore[arg-type]
            assert 0.4 < dur < 0.6
            assert int(meta["file_size"]) > 0  # type: ignore[arg-type]

    def test_flac_metadata(self) -> None:
        """Extract metadata from FLAC file."""
        sr, samples = 48000, make_sine(sr=48000, dur=0.3, ch=2)
        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / "test.flac"
            save_audio(samples, sr, path)
            meta = get_audio_metadata(path)
            assert meta["format"] == "flac"
            assert meta["sample_rate"] == sr
            assert meta["channels"] == 2
            dur = float(meta["duration"])  # type: ignore[arg-type]
            assert 0.2 < dur < 0.4
            assert int(meta["file_size"]) > 0  # type: ignore[arg-type]

    def test_ogg_metadata(self) -> None:
        """Extract metadata from OGG file."""
        sr, samples = 44100, make_sine(sr=44100, dur=0.5, ch=1)
        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / "test.ogg"
            save_audio(samples, sr, path)
            meta = get_audio_metadata(path)
            assert meta["format"] == "ogg"
            assert meta["sample_rate"] == sr
            assert meta["channels"] == 1


class TestHLSLoading:
    """Test HLS/M3U8 streaming."""

    @pytest.mark.skip(reason="Requires network access")
    def test_hls(self) -> None:
        """HLS URL loading."""
        pass
