# Generated by Claude
"""Unit tests for case detail parser."""

import json
from pathlib import Path

from oyez_sa_asr.scraper.parser_cases import (
    AudioReference,
    Decision,
    ProcessedCase,
    parse_opinion_title,
)


class TestParseOpinionTitle:
    """Tests for parse_opinion_title function."""

    def test_majority_opinion(self) -> None:
        """Standard opinion announcement is majority type."""
        result = parse_opinion_title("Opinion Announcement - June 30, 2023")
        assert result == ("majority", None)

    def test_dissent_new_format(self) -> None:
        """'Dissenting Opinion - Justice - Date' pattern."""
        result = parse_opinion_title("Dissenting Opinion - Sotomayor - June 30, 2023")
        assert result == ("dissent", "Sotomayor")

    def test_dissent_old_format(self) -> None:
        """'Opinion Announcement - Date (Dissent by Justice)' pattern."""
        result = parse_opinion_title(
            "Opinion Announcement - June 19, 2017 (Dissent by Breyer)"
        )
        assert result == ("dissent", "Breyer")

    def test_concurrence_new_format(self) -> None:
        """'Concurring Opinion - Justice - Date' pattern."""
        result = parse_opinion_title("Concurring Opinion - Jackson - June 27, 2024")
        assert result == ("concurrence", "Jackson")

    def test_numbered_part(self) -> None:
        """'Opinion Announcement - Date (Part N)' pattern."""
        result = parse_opinion_title("Opinion Announcement - June 29, 2015 (Part 1)")
        assert result == ("majority", None)

    def test_numbered_part_2(self) -> None:
        """Second part is also majority type."""
        result = parse_opinion_title("Opinion Announcement - June 29, 2015 (Part 2)")
        assert result == ("majority", None)

    def test_dissent_with_full_name(self) -> None:
        """Dissent with full justice name."""
        result = parse_opinion_title("Dissenting Opinion - Roberts - June 26, 2015")
        assert result == ("dissent", "Roberts")


class TestAudioReference:
    """Tests for AudioReference dataclass."""

    def test_from_oral_argument(self) -> None:
        """Parse oral argument audio reference."""
        raw = {
            "id": 19476,
            "title": "Oral Argument - December 06, 1982",
            "public_note": None,
            "unavailable": None,
            "display_title": None,
            "href": "https://example.com/case_media/oral_argument_audio/19476",
        }
        ref = AudioReference.from_oral_argument(raw)
        assert ref.id == 19476
        assert ref.title == "Oral Argument - December 06, 1982"
        assert ref.href == "https://example.com/case_media/oral_argument_audio/19476"
        assert ref.unavailable is False
        assert ref.type == "oral_argument"
        assert ref.speaker is None

    def test_from_oral_argument_unavailable(self) -> None:
        """Parse unavailable oral argument."""
        raw = {
            "id": 123,
            "title": "Oral Argument - January 01, 2000",
            "unavailable": True,
            "href": "https://example.com/case_media/oral_argument_audio/123",
        }
        ref = AudioReference.from_oral_argument(raw)
        assert ref.unavailable is True

    def test_from_opinion_announcement_majority(self) -> None:
        """Parse majority opinion announcement."""
        raw = {
            "id": 25574,
            "title": "Opinion Announcement - June 30, 2023",
            "unavailable": False,
            "href": "https://example.com/case_media/opinion_announcement_audio/25574",
        }
        ref = AudioReference.from_opinion_announcement(raw)
        assert ref.id == 25574
        assert ref.type == "majority"
        assert ref.speaker is None

    def test_from_opinion_announcement_dissent(self) -> None:
        """Parse dissenting opinion announcement."""
        raw = {
            "id": 25583,
            "title": "Dissenting Opinion - Sotomayor - June 30, 2023",
            "unavailable": False,
            "href": "https://example.com/case_media/opinion_announcement_audio/25583",
        }
        ref = AudioReference.from_opinion_announcement(raw)
        assert ref.type == "dissent"
        assert ref.speaker == "Sotomayor"


class TestDecision:
    """Tests for Decision dataclass."""

    def test_from_raw(self) -> None:
        """Parse decision from raw API response."""
        raw = {
            "decision_type": "majority opinion",
            "winning_party": "United States",
            "majority_vote": 9,
            "minority_vote": 0,
        }
        decision = Decision.from_raw(raw)
        assert decision.type == "majority opinion"
        assert decision.winner == "United States"
        assert decision.majority_votes == 9
        assert decision.minority_votes == 0

    def test_from_raw_with_nulls(self) -> None:
        """Parse decision with null values."""
        raw = {
            "decision_type": "per curiam",
            "winning_party": None,
            "majority_vote": 5,
            "minority_vote": 4,
        }
        decision = Decision.from_raw(raw)
        assert decision.type == "per curiam"
        assert decision.winner is None


class TestProcessedCase:
    """Tests for ProcessedCase dataclass."""

    def test_from_raw(self) -> None:
        """Parse case from raw API response."""
        raw = {
            "ID": 12345,
            "name": "Test v. Case",
            "docket_number": "21-476",
            "term": "2022",
            "href": "https://example.com/cases/2022/21-476",
            "timeline": [
                {"event": "Argued", "dates": [1670198400]},
                {"event": "Decided", "dates": [1688083200]},
            ],
            "decisions": [
                {
                    "decision_type": "majority opinion",
                    "winning_party": "Test",
                    "majority_vote": 6,
                    "minority_vote": 3,
                }
            ],
            "oral_argument_audio": [
                {
                    "id": 25123,
                    "title": "Oral Argument - December 05, 2022",
                    "href": "https://example.com/case_media/oral_argument_audio/25123",
                    "unavailable": None,
                }
            ],
            "opinion_announcement": [
                {
                    "id": 25574,
                    "title": "Opinion Announcement - June 30, 2023",
                    "href": "https://example.com/case_media/opinion_announcement_audio/25574",
                    "unavailable": False,
                }
            ],
        }
        case = ProcessedCase.from_raw(raw)
        assert case.id == 12345
        assert case.name == "Test v. Case"
        assert case.docket_number == "21-476"
        assert case.term == "2022"
        assert len(case.timeline) == 2
        assert case.decision is not None
        assert case.decision.winner == "Test"
        assert len(case.oral_arguments) == 1
        assert len(case.opinion_announcements) == 1

    def test_save_creates_file(self, tmp_path: Path) -> None:
        """Save creates JSON file with correct structure."""
        case = ProcessedCase(
            id=123,
            name="Test v. Case",
            docket_number="21-476",
            term="2022",
            href="https://example.com/cases/2022/21-476",
            timeline=[],
            decision=None,
            oral_arguments=[],
            opinion_announcements=[],
        )
        case.save(tmp_path)

        expected_file = tmp_path / "2022" / "21-476.json"
        assert expected_file.exists()

        with expected_file.open() as f:
            data = json.load(f)
        assert data["id"] == 123
        assert data["name"] == "Test v. Case"

    def test_from_raw_no_audio(self) -> None:
        """Parse case with no audio."""
        raw = {
            "ID": 999,
            "name": "No Audio Case",
            "docket_number": "99-999",
            "term": "1999",
            "href": "https://example.com/cases/1999/99-999",
            "timeline": [],
            "decisions": [],
            "oral_argument_audio": None,
            "opinion_announcement": None,
        }
        case = ProcessedCase.from_raw(raw)
        assert len(case.oral_arguments) == 0
        assert len(case.opinion_announcements) == 0
