# Generated by Claude
"""TDD tests for CLI restructure with scrape/process subcommands."""

import json
import re
import tempfile
from pathlib import Path
from unittest.mock import AsyncMock, patch

from typer.testing import CliRunner

from oyez_sa_asr.cli import app

runner = CliRunner()


def strip_ansi(text: str) -> str:
    """Remove ANSI escape codes from text."""
    return re.sub(r"\x1b\[[0-9;]*m", "", text)


class TestCliStructure:
    """Tests for CLI command structure."""

    def test_scrape_subcommand_exists(self) -> None:
        """Should have a scrape subcommand group."""
        result = runner.invoke(app, ["scrape", "--help"])
        assert result.exit_code == 0
        assert "index" in result.output
        assert "cases" in result.output

    def test_process_subcommand_exists(self) -> None:
        """Should have a process subcommand group."""
        result = runner.invoke(app, ["process", "--help"])
        assert result.exit_code == 0
        assert "index" in result.output


class TestScrapeIndex:
    """Tests for scrape index command."""

    def test_scrape_index_help(self) -> None:
        """Should show help for scrape index."""
        result = runner.invoke(app, ["scrape", "index", "--help"])
        assert result.exit_code == 0
        output = strip_ansi(result.output)
        assert "--cache-dir" in output
        assert "--max-pages" in output

    def test_scrape_index_default_cache_dir(self) -> None:
        """Should use .cache/index as default cache directory."""
        with (
            patch("oyez_sa_asr.cli_scrape.AdaptiveFetcher"),
            patch("oyez_sa_asr.cli_scrape.OyezCasesTraverser") as mock_traverser,
        ):
            mock_traverser.return_value.fetch_all = AsyncMock(return_value=[])
            result = runner.invoke(app, ["scrape", "index", "--max-pages", "1"])
            # Check that .cache/index was used
            assert ".cache/index" in result.output or result.exit_code == 0


class TestScrapeCases:
    """Tests for scrape cases command."""

    def test_scrape_cases_help(self) -> None:
        """Should show help for scrape cases."""
        result = runner.invoke(app, ["scrape", "cases", "--help"])
        assert result.exit_code == 0
        output = strip_ansi(result.output)
        assert "--index-file" in output
        assert "--cache-dir" in output

    def test_scrape_cases_requires_index(self) -> None:
        """Should error if index file doesn't exist."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = runner.invoke(
                app,
                [
                    "scrape",
                    "cases",
                    "--index-file",
                    f"{tmpdir}/nonexistent.json",
                ],
            )
            assert result.exit_code != 0 or "not found" in result.output.lower()

    def test_scrape_cases_reads_index_and_fetches(self) -> None:
        """Should read index and fetch case details."""
        with tempfile.TemporaryDirectory() as tmpdir:
            # Create a minimal index file
            index_file = Path(tmpdir) / "cases_index.json"
            index_data = {
                "generated_at": "2026-01-13T00:00:00Z",
                "total_cases": 2,
                "cases": [
                    {"id": 1, "href": "https://api.oyez.org/cases/2020/1"},
                    {"id": 2, "href": "https://api.oyez.org/cases/2020/2"},
                ],
            }
            index_file.write_text(json.dumps(index_data))

            cache_dir = Path(tmpdir) / "cache"

            with patch("oyez_sa_asr.cli_scrape.AdaptiveFetcher") as mock_fetcher_cls:
                mock_fetcher = mock_fetcher_cls.create.return_value
                mock_fetcher.fetch_batch_adaptive = AsyncMock(return_value=[])

                result = runner.invoke(
                    app,
                    [
                        "scrape",
                        "cases",
                        "--index-file",
                        str(index_file),
                        "--cache-dir",
                        str(cache_dir),
                    ],
                )

                assert result.exit_code == 0
                # Should have called fetch_batch_adaptive with 2 requests
                mock_fetcher.fetch_batch_adaptive.assert_called_once()
                call_args = mock_fetcher.fetch_batch_adaptive.call_args[0][0]
                assert len(call_args) == 2


class TestProcessIndex:
    """Tests for process index command."""

    def test_process_index_help(self) -> None:
        """Should show help for process index."""
        result = runner.invoke(app, ["process", "index", "--help"])
        assert result.exit_code == 0
        output = strip_ansi(result.output)
        assert "--cache-dir" in output
        assert "--output" in output

    def test_process_index_default_paths(self) -> None:
        """Should use stage-based default paths."""
        result = runner.invoke(app, ["process", "index", "--help"])
        # Default cache should be .cache/index
        # Default output should be data/index/cases_index.json
        assert result.exit_code == 0


class TestClearCommands:
    """Tests for clear subcommands."""

    def test_clear_subcommand_exists(self) -> None:
        """Should have a clear subcommand group."""
        result = runner.invoke(app, ["clear", "--help"])
        assert result.exit_code == 0
        assert "index" in result.output
        assert "cases" in result.output

    def test_clear_index_help(self) -> None:
        """Should show help for clear index."""
        result = runner.invoke(app, ["clear", "index", "--help"])
        assert result.exit_code == 0
        output = strip_ansi(result.output)
        assert "--cache-dir" in output
        assert "--data-dir" in output
        assert "--force" in output

    def test_clear_cases_help(self) -> None:
        """Should show help for clear cases."""
        result = runner.invoke(app, ["clear", "cases", "--help"])
        assert result.exit_code == 0
        output = strip_ansi(result.output)
        assert "--cache-dir" in output
        assert "--data-dir" in output
        assert "--force" in output

    def test_clear_index_removes_directories(self) -> None:
        """Should remove index cache and data directories."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cache_dir = Path(tmpdir) / "cache" / "index"
            data_dir = Path(tmpdir) / "data" / "index"

            # Create directories with files
            cache_dir.mkdir(parents=True)
            (cache_dir / "test.json").write_text("{}")
            data_dir.mkdir(parents=True)
            (data_dir / "cases_index.json").write_text("{}")

            result = runner.invoke(
                app,
                [
                    "clear",
                    "index",
                    "--cache-dir",
                    str(cache_dir),
                    "--data-dir",
                    str(data_dir),
                    "--force",
                ],
            )

            assert result.exit_code == 0
            assert not cache_dir.exists()
            assert not data_dir.exists()

    def test_clear_cases_removes_directories(self) -> None:
        """Should remove cases cache and data directories."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cache_dir = Path(tmpdir) / "cache" / "cases"
            data_dir = Path(tmpdir) / "data" / "cases"

            # Create directories with files
            cache_dir.mkdir(parents=True)
            (cache_dir / "meta").mkdir()
            (cache_dir / "meta" / "abc.json").write_text("{}")
            data_dir.mkdir(parents=True)
            (data_dir / "case1.json").write_text("{}")

            result = runner.invoke(
                app,
                [
                    "clear",
                    "cases",
                    "--cache-dir",
                    str(cache_dir),
                    "--data-dir",
                    str(data_dir),
                    "--force",
                ],
            )

            assert result.exit_code == 0
            assert not cache_dir.exists()
            assert not data_dir.exists()

    def test_clear_handles_nonexistent_directories(self) -> None:
        """Should handle nonexistent directories gracefully."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cache_dir = Path(tmpdir) / "nonexistent_cache"
            data_dir = Path(tmpdir) / "nonexistent_data"

            result = runner.invoke(
                app,
                [
                    "clear",
                    "index",
                    "--cache-dir",
                    str(cache_dir),
                    "--data-dir",
                    str(data_dir),
                    "--force",
                ],
            )

            assert result.exit_code == 0
            assert "does not exist" in result.output


class TestMainCommand:
    """Tests for main command."""

    def test_main_command(self) -> None:
        """Should execute main command."""
        result = runner.invoke(app, ["main"])
        assert result.exit_code == 0
        output = strip_ansi(result.output)
        # Should print the message from main()
        assert "Replace this message" in output or "Typer" in output
