# Generated by Claude
"""Tests for stats CLI commands - audio stats."""

import json
import re
import tempfile
from pathlib import Path

from typer.testing import CliRunner

from oyez_sa_asr.cli import app

runner = CliRunner()


def _strip_ansi(text: str) -> str:
    """Remove ANSI escape codes from text."""
    return re.sub(r"\x1b\[[0-9;]*m", "", text)


class TestStatsAudioHelp:
    """Tests for help output."""

    def test_help(self) -> None:
        """Show help."""
        result = runner.invoke(app, ["stats", "audio", "--help"])
        assert result.exit_code == 0
        assert "audio" in result.output.lower()


class TestStatsAudioMissingData:
    """Tests for missing data handling."""

    def test_no_recordings(self) -> None:
        """Show message when no recordings found."""
        with tempfile.TemporaryDirectory() as tmpdir:
            data_dir = Path(tmpdir)
            (data_dir / "audio").mkdir()

            result = runner.invoke(app, ["stats", "audio", "--data-dir", str(data_dir)])
            assert result.exit_code == 0
            assert "No recordings found" in result.output

    def test_missing_directory(self) -> None:
        """Fail if audio directory doesn't exist."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = runner.invoke(
                app, ["stats", "audio", "--data-dir", str(Path(tmpdir) / "missing")]
            )
            assert result.exit_code == 1
            assert "not found" in result.output


class TestStatsAudioDisplay:
    """Tests for statistics display."""

    def test_displays_stats(self) -> None:
        """Display audio statistics."""
        with tempfile.TemporaryDirectory() as tmpdir:
            data_dir = Path(tmpdir)
            audio_dir = data_dir / "audio" / "2024" / "22-123"
            audio_dir.mkdir(parents=True)

            meta = {
                "duration": 3600.0,
                "sample_rate": 16000,
                "channels": 1,
                "source_format": "mp3",
                "source_era": "digital",
            }
            (audio_dir / "rec.metadata.json").write_text(json.dumps(meta))
            (audio_dir / "rec.flac").write_bytes(b"fake" * 1000)

            result = runner.invoke(app, ["stats", "audio", "--data-dir", str(data_dir)])
            output = _strip_ansi(result.output)

            assert result.exit_code == 0
            assert "Audio Statistics" in output
            assert "Total recordings: 1" in output
            assert "digital" in output
            assert "mp3" in output

    def test_term_filter(self) -> None:
        """Filter by term."""
        with tempfile.TemporaryDirectory() as tmpdir:
            data_dir = Path(tmpdir)

            for term in ["2023", "2024"]:
                audio_dir = data_dir / "audio" / term / "docket"
                audio_dir.mkdir(parents=True)
                meta = {
                    "duration": 100.0,
                    "source_format": "mp3",
                    "source_era": "digital",
                }
                (audio_dir / "rec.metadata.json").write_text(json.dumps(meta))
                (audio_dir / "rec.flac").write_bytes(b"fake")

            result = runner.invoke(
                app, ["stats", "audio", "--data-dir", str(data_dir), "--term", "2024"]
            )
            output = _strip_ansi(result.output)

            assert result.exit_code == 0
            assert "Total recordings: 1" in output
