# Generated by Claude
"""Tests for ProcessedTranscript and case mapping."""

import json
import tempfile
from pathlib import Path

from oyez_sa_asr.scraper.parser_transcripts import (
    ProcessedTranscript,
    build_transcript_to_case_map,
)


class TestBuildCaseMap:
    """Tests for build_transcript_to_case_map function."""

    def test_builds_map_from_cases(self) -> None:
        """Map transcript IDs to case info."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cases_dir = Path(tmpdir)
            term_dir = cases_dir / "2022"
            term_dir.mkdir()

            case_data = {
                "docket_number": "21-476",
                "term": "2022",
                "oral_arguments": [
                    {"id": 25123, "href": "https://example.com/oral/25123"}
                ],
                "opinion_announcements": [
                    {"id": 25574, "href": "https://example.com/opinion/25574"}
                ],
            }
            (term_dir / "21-476.json").write_text(json.dumps(case_data))

            case_map = build_transcript_to_case_map(cases_dir)

            assert 25123 in case_map
            assert case_map[25123] == ("2022", "21-476")
            assert 25574 in case_map
            assert case_map[25574] == ("2022", "21-476")

    def test_empty_cases_dir(self) -> None:
        """Empty directory returns empty map."""
        with tempfile.TemporaryDirectory() as tmpdir:
            case_map = build_transcript_to_case_map(Path(tmpdir))
            assert case_map == {}


class TestProcessedTranscript:
    """Tests for ProcessedTranscript dataclass."""

    def test_from_raw(self) -> None:
        """Parse full transcript from raw API response."""
        raw = {
            "id": 25123,
            "title": "Oral Argument - December 05, 2022",
            "media_file": [
                {"mime": "audio/mpeg", "href": "https://example.com/audio.mp3"},
                {"mime": "audio/ogg", "href": "https://example.com/audio.ogg"},
            ],
            "transcript": {
                "duration": 100.0,
                "sections": [
                    {
                        "turns": [
                            {
                                "start": 0.0,
                                "stop": 10.0,
                                "speaker": {"ID": 1, "name": "Speaker A"},
                                "text_blocks": [{"text": "Hello world"}],
                            },
                            {
                                "start": 10.0,
                                "stop": 20.0,
                                "speaker": {"ID": 2, "name": "Speaker B"},
                                "text_blocks": [{"text": "Good morning"}],
                            },
                        ]
                    }
                ],
            },
        }
        transcript = ProcessedTranscript.from_raw(raw, "2022", "21-476")

        assert transcript.id == 25123
        assert transcript.case_docket == "21-476"
        assert transcript.term == "2022"
        assert transcript.type == "oral_argument"
        assert transcript.title == "Oral Argument - December 05, 2022"
        assert len(transcript.turns) == 2
        assert transcript.metadata["duration_seconds"] == 100.0
        assert transcript.metadata["turn_count"] == 2

    def test_overlap_detection(self) -> None:
        """Overlapping turns are flagged."""
        raw = {
            "id": 1,
            "title": "Oral Argument - Test",
            "media_file": [],
            "transcript": {
                "duration": 30.0,
                "sections": [
                    {
                        "turns": [
                            {
                                "start": 0.0,
                                "stop": 15.0,
                                "speaker": {"ID": 1, "name": "A"},
                                "text_blocks": [{"text": "First"}],
                            },
                            {
                                "start": 10.0,  # Overlaps with previous
                                "stop": 20.0,
                                "speaker": {"ID": 2, "name": "B"},
                                "text_blocks": [{"text": "Second"}],
                            },
                        ]
                    }
                ],
            },
        }
        transcript = ProcessedTranscript.from_raw(raw, "2022", "test")

        assert transcript.turns[0].is_overlapping is False
        assert transcript.turns[1].is_overlapping is True
        assert transcript.metadata["overlap_count"] == 1

    def test_speaker_stats(self) -> None:
        """Speaker turn counts are computed."""
        raw = {
            "id": 1,
            "title": "Oral Argument - Test",
            "media_file": [],
            "transcript": {
                "duration": 30.0,
                "sections": [
                    {
                        "turns": [
                            {
                                "start": 0.0,
                                "stop": 10.0,
                                "speaker": {"ID": 1, "name": "A"},
                                "text_blocks": [{"text": "First"}],
                            },
                            {
                                "start": 10.0,
                                "stop": 20.0,
                                "speaker": {"ID": 1, "name": "A"},
                                "text_blocks": [{"text": "Second"}],
                            },
                            {
                                "start": 20.0,
                                "stop": 30.0,
                                "speaker": {"ID": 2, "name": "B"},
                                "text_blocks": [{"text": "Third"}],
                            },
                        ]
                    }
                ],
            },
        }
        transcript = ProcessedTranscript.from_raw(raw, "2022", "test")

        speakers = transcript.metadata["speakers"]
        assert len(speakers) == 2
        speaker_a = next(s for s in speakers if s["id"] == 1)
        assert speaker_a["turn_count"] == 2

    def test_audio_urls_extracted(self) -> None:
        """Audio URLs are extracted by format."""
        raw = {
            "id": 1,
            "title": "Oral Argument - Test",
            "media_file": [
                {"mime": "audio/mpeg", "href": "https://example.com/a.mp3"},
                {"mime": "audio/ogg", "href": "https://example.com/a.ogg"},
                {"mime": "application/x-mpegURL", "href": "https://example.com/a.m3u8"},
            ],
            "transcript": {"duration": 10.0, "sections": []},
        }
        transcript = ProcessedTranscript.from_raw(raw, "2022", "test")

        assert transcript.metadata["audio_urls"]["mp3"] == "https://example.com/a.mp3"
        assert transcript.metadata["audio_urls"]["ogg"] == "https://example.com/a.ogg"
        assert transcript.metadata["audio_urls"]["hls"] == "https://example.com/a.m3u8"

    def test_save_creates_file(self) -> None:
        """Save creates JSON file in correct location."""
        raw = {
            "id": 25123,
            "title": "Oral Argument - Test",
            "media_file": [],
            "transcript": {"duration": 10.0, "sections": []},
        }
        transcript = ProcessedTranscript.from_raw(raw, "2022", "21-476")

        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir)
            transcript.save(output_dir)

            expected_file = output_dir / "2022" / "21-476" / "oral_argument.json"
            assert expected_file.exists()

            with expected_file.open() as f:
                data = json.load(f)
            assert data["id"] == 25123

    def test_null_transcript(self) -> None:
        """Handle missing transcript data."""
        raw = {
            "id": 1,
            "title": "Oral Argument - Test",
            "media_file": [],
            "transcript": None,
        }
        transcript = ProcessedTranscript.from_raw(raw, "2022", "test")

        assert len(transcript.turns) == 0
        assert transcript.metadata["duration_seconds"] == 0.0
