# Generated by Claude
"""Tests for case audio references and opinion parsing."""

from oyez_sa_asr.scraper.parser_cases import (
    AudioReference,
    Decision,
    parse_opinion_title,
)


class TestParseOpinionTitle:
    """Tests for parse_opinion_title."""

    def test_majority(self) -> None:
        """Standard announcements are majority."""
        assert parse_opinion_title("Opinion Announcement - June 30, 2023") == (
            "majority",
            None,
        )

    def test_dissent_new(self) -> None:
        """New format dissent with justice name."""
        assert parse_opinion_title(
            "Dissenting Opinion - Sotomayor - June 30, 2023"
        ) == (
            "dissent",
            "Sotomayor",
        )

    def test_dissent_old(self) -> None:
        """Old format dissent in parentheses."""
        result = parse_opinion_title(
            "Opinion Announcement - June 19, 2017 (Dissent by Breyer)"
        )
        assert result == ("dissent", "Breyer")

    def test_concurrence(self) -> None:
        """Concurring opinion format."""
        assert parse_opinion_title("Concurring Opinion - Jackson - June 27, 2024") == (
            "concurrence",
            "Jackson",
        )

    def test_numbered_part(self) -> None:
        """Numbered parts are still majority."""
        assert parse_opinion_title("Opinion Announcement - June 29, 2015 (Part 1)") == (
            "majority",
            None,
        )
        assert parse_opinion_title("Opinion Announcement - June 29, 2015 (Part 2)") == (
            "majority",
            None,
        )


class TestAudioReference:
    """Tests for AudioReference dataclass."""

    def test_from_oral_argument(self) -> None:
        """Parse oral argument audio reference."""
        raw = {
            "id": 19476,
            "title": "Oral Argument - December 06, 1982",
            "public_note": None,
            "unavailable": None,
            "display_title": None,
            "href": "https://example.com/case_media/oral_argument_audio/19476",
        }
        ref = AudioReference.from_oral_argument(raw)
        assert ref.id == 19476
        assert ref.title == "Oral Argument - December 06, 1982"
        assert ref.href == "https://example.com/case_media/oral_argument_audio/19476"
        assert ref.unavailable is False
        assert ref.type == "oral_argument"
        assert ref.speaker is None

    def test_from_oral_argument_unavailable(self) -> None:
        """Parse unavailable oral argument."""
        raw = {
            "id": 123,
            "title": "Oral Argument - January 01, 2000",
            "unavailable": True,
            "href": "https://example.com/case_media/oral_argument_audio/123",
        }
        ref = AudioReference.from_oral_argument(raw)
        assert ref.unavailable is True

    def test_from_opinion_announcement_majority(self) -> None:
        """Parse majority opinion announcement."""
        raw = {
            "id": 25574,
            "title": "Opinion Announcement - June 30, 2023",
            "unavailable": False,
            "href": "https://example.com/case_media/opinion_announcement_audio/25574",
        }
        ref = AudioReference.from_opinion_announcement(raw)
        assert ref.id == 25574
        assert ref.type == "majority"
        assert ref.speaker is None

    def test_from_opinion_announcement_dissent(self) -> None:
        """Parse dissenting opinion announcement."""
        raw = {
            "id": 25583,
            "title": "Dissenting Opinion - Sotomayor - June 30, 2023",
            "unavailable": False,
            "href": "https://example.com/case_media/opinion_announcement_audio/25583",
        }
        ref = AudioReference.from_opinion_announcement(raw)
        assert ref.type == "dissent"
        assert ref.speaker == "Sotomayor"

    def test_to_dict(self) -> None:
        """Test to_dict method (line 76)."""
        ref = AudioReference(
            id=123,
            title="Test Title",
            href="https://example.com/test",
            unavailable=False,
            type="oral_argument",
            speaker=None,
        )
        result = ref.to_dict()
        assert result == {
            "id": 123,
            "title": "Test Title",
            "href": "https://example.com/test",
            "unavailable": False,
            "type": "oral_argument",
            "speaker": None,
        }

    def test_to_dict_with_speaker(self) -> None:
        """Test to_dict with speaker."""
        ref = AudioReference(
            id=456,
            title="Dissenting Opinion - Sotomayor",
            href="https://example.com/dissent",
            unavailable=False,
            type="dissent",
            speaker="Sotomayor",
        )
        result = ref.to_dict()
        assert result["speaker"] == "Sotomayor"


class TestDecision:
    """Tests for Decision dataclass."""

    def test_from_raw(self) -> None:
        """Parse decision from raw API response."""
        raw = {
            "decision_type": "majority opinion",
            "winning_party": "United States",
            "majority_vote": 9,
            "minority_vote": 0,
        }
        decision = Decision.from_raw(raw)
        assert decision.type == "majority opinion"
        assert decision.winner == "United States"
        assert decision.majority_votes == 9
        assert decision.minority_votes == 0

    def test_from_raw_with_nulls(self) -> None:
        """Parse decision with null values."""
        raw = {
            "decision_type": "per curiam",
            "winning_party": None,
            "majority_vote": 5,
            "minority_vote": 4,
        }
        decision = Decision.from_raw(raw)
        assert decision.type == "per curiam"
        assert decision.winner is None
