# Generated by Claude
"""Tests for scrape audio command and extract_audio_urls."""

import json
import re
import tempfile
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

from typer.testing import CliRunner

from oyez_sa_asr.cli import app
from oyez_sa_asr.scraper.parser_transcripts import extract_audio_urls


def strip_ansi(text: str) -> str:
    """Strip ANSI escape codes from text."""
    return re.sub(r"\x1b\[[0-9;]*m", "", text)


runner = CliRunner()


class TestExtractAudioUrls:
    """Tests for extract_audio_urls function."""

    def test_extracts_all_formats(self) -> None:
        """Extract mp3, ogg, and hls URLs from transcripts."""
        with tempfile.TemporaryDirectory() as tmpdir:
            transcripts_dir = Path(tmpdir) / "transcripts"
            term_dir = transcripts_dir / "2022" / "21-476"
            term_dir.mkdir(parents=True)

            transcript = {
                "metadata": {
                    "audio_urls": {
                        "mp3": "https://s3.amazonaws.com/bucket/audio.mp3",
                        "ogg": "https://s3.amazonaws.com/bucket/audio.ogg",
                        "hls": "https://s3.amazonaws.com/bucket/audio.m3u8",
                    }
                }
            }
            (term_dir / "oral_argument.json").write_text(json.dumps(transcript))

            urls = extract_audio_urls(transcripts_dir)

            assert len(urls) == 3
            assert "https://s3.amazonaws.com/bucket/audio.mp3" in urls
            assert "https://s3.amazonaws.com/bucket/audio.ogg" in urls
            assert "https://s3.amazonaws.com/bucket/audio.m3u8" in urls

    def test_empty_directory(self) -> None:
        """Return empty list for empty directory."""
        with tempfile.TemporaryDirectory() as tmpdir:
            transcripts_dir = Path(tmpdir) / "transcripts"
            transcripts_dir.mkdir()

            urls = extract_audio_urls(transcripts_dir)
            assert urls == []

    def test_nonexistent_directory(self) -> None:
        """Return empty list for nonexistent directory."""
        urls = extract_audio_urls(Path("/nonexistent/path"))
        assert urls == []

    def test_deduplicates_urls(self) -> None:
        """Deduplicate URLs across multiple transcripts."""
        with tempfile.TemporaryDirectory() as tmpdir:
            transcripts_dir = Path(tmpdir) / "transcripts"
            term_dir = transcripts_dir / "2022" / "21-476"
            term_dir.mkdir(parents=True)

            # Same URL in multiple files
            transcript = {
                "metadata": {
                    "audio_urls": {
                        "mp3": "https://s3.amazonaws.com/bucket/shared.mp3",
                    }
                }
            }
            (term_dir / "file1.json").write_text(json.dumps(transcript))
            (term_dir / "file2.json").write_text(json.dumps(transcript))

            urls = extract_audio_urls(transcripts_dir)
            assert len(urls) == 1


class TestScrapeAudioCommand:
    """Tests for scrape audio CLI command."""

    def test_help(self) -> None:
        """Show help for scrape audio command."""
        result = runner.invoke(app, ["scrape", "audio", "--help"])
        assert result.exit_code == 0
        output = strip_ansi(result.output)
        assert "--transcripts-dir" in output
        assert "--cache-dir" in output
        assert "--max-parallelism" in output

    def test_empty_transcripts(self) -> None:
        """Handle empty transcripts directory gracefully."""
        with tempfile.TemporaryDirectory() as tmpdir:
            transcripts_dir = Path(tmpdir) / "transcripts"
            transcripts_dir.mkdir()
            cache_dir = Path(tmpdir) / "cache"

            result = runner.invoke(
                app,
                [
                    "scrape",
                    "audio",
                    "--transcripts-dir",
                    str(transcripts_dir),
                    "--cache-dir",
                    str(cache_dir),
                ],
            )

            assert result.exit_code == 0
            assert "No audio URLs found" in result.output

    @patch("oyez_sa_asr.cli_scrape_audio.AdaptiveFetcher")
    @patch("oyez_sa_asr.cli_scrape_audio.extract_audio_urls")
    def test_fetches_urls(
        self, mock_extract: MagicMock, mock_fetcher_cls: MagicMock
    ) -> None:
        """Extract URLs and use AdaptiveFetcher to download them."""
        with tempfile.TemporaryDirectory() as tmpdir:
            transcripts_dir = Path(tmpdir) / "transcripts"
            transcripts_dir.mkdir()
            cache_dir = Path(tmpdir) / "cache"

            # Mock URL extraction
            mock_extract.return_value = [
                "https://s3.amazonaws.com/bucket/audio1.mp3",
                "https://s3.amazonaws.com/bucket/audio2.mp3",
            ]

            # Mock fetcher
            mock_fetcher = mock_fetcher_cls.create_s3.return_value
            mock_fetcher.fetch_batch_adaptive = AsyncMock(return_value=[])

            result = runner.invoke(
                app,
                [
                    "scrape",
                    "audio",
                    "--transcripts-dir",
                    str(transcripts_dir),
                    "--cache-dir",
                    str(cache_dir),
                ],
            )

            assert result.exit_code == 0
            mock_extract.assert_called_once_with(transcripts_dir)
            mock_fetcher_cls.create_s3.assert_called_once()
            mock_fetcher.fetch_batch_adaptive.assert_called_once()
