# Generated by Claude
"""Tests for stats transcripts command."""

import json
import re
import tempfile
from pathlib import Path

from typer.testing import CliRunner

from oyez_sa_asr.cli import app
from oyez_sa_asr.cli_stats_transcripts import _get_speaker_bucket

runner = CliRunner()


def _strip_ansi(text: str) -> str:
    """Remove ANSI escape codes from text."""
    return re.sub(r"\x1b\[[0-9;]*m", "", text)


class TestStatsTranscriptsHelp:
    """Tests for help output."""

    def test_help(self) -> None:
        """Show help."""
        result = runner.invoke(app, ["stats", "transcripts", "--help"])
        assert result.exit_code == 0
        assert "transcript" in result.output.lower()


class TestStatsTranscriptsMissingData:
    """Tests for missing data handling."""

    def test_no_transcripts(self) -> None:
        """Show message when no transcripts found."""
        with tempfile.TemporaryDirectory() as tmpdir:
            data_dir = Path(tmpdir)
            (data_dir / "transcripts").mkdir()

            result = runner.invoke(
                app, ["stats", "transcripts", "--data-dir", str(data_dir)]
            )
            assert result.exit_code == 0
            assert "No transcripts found" in result.output

    def test_missing_directory(self) -> None:
        """Fail if transcripts directory doesn't exist."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = runner.invoke(
                app,
                ["stats", "transcripts", "--data-dir", str(Path(tmpdir) / "missing")],
            )
            assert result.exit_code == 1
            assert "not found" in result.output


class TestStatsTranscriptsDisplay:
    """Tests for statistics display."""

    def test_displays_stats(self) -> None:
        """Display transcript statistics."""
        with tempfile.TemporaryDirectory() as tmpdir:
            data_dir = Path(tmpdir)
            trans_dir = data_dir / "transcripts" / "2024" / "22-123"
            trans_dir.mkdir(parents=True)

            transcript = {
                "type": "argument",
                "turns": [
                    {
                        "is_valid": True,
                        "duration": 10.0,
                        "word_count": 50,
                        "speaker_name": "John Roberts",
                    },
                    {
                        "is_valid": True,
                        "duration": 15.0,
                        "word_count": 75,
                        "speaker_name": "Elena Kagan",
                    },
                ],
            }
            (trans_dir / "argument.json").write_text(json.dumps(transcript))

            result = runner.invoke(
                app, ["stats", "transcripts", "--data-dir", str(data_dir)]
            )
            output = _strip_ansi(result.output)

            assert result.exit_code == 0
            assert "Transcript Statistics" in output
            assert "Total transcripts: 1" in output
            assert "Total turns: 2" in output
            assert "John Roberts" in output
            assert "argument" in output

    def test_term_filter(self) -> None:
        """Filter by term."""
        with tempfile.TemporaryDirectory() as tmpdir:
            data_dir = Path(tmpdir)

            for term in ["2023", "2024"]:
                trans_dir = data_dir / "transcripts" / term / "docket"
                trans_dir.mkdir(parents=True)
                transcript = {"type": "argument", "turns": [{"is_valid": True}]}
                (trans_dir / "arg.json").write_text(json.dumps(transcript))

            result = runner.invoke(
                app,
                ["stats", "transcripts", "--data-dir", str(data_dir), "--term", "2024"],
            )
            output = _strip_ansi(result.output)

            assert result.exit_code == 0
            assert "Total transcripts: 1" in output

    def test_displays_speaker_count_distribution(self) -> None:
        """Display recording distribution by speaker count."""
        with tempfile.TemporaryDirectory() as tmpdir:
            data_dir = Path(tmpdir)
            trans_dir = data_dir / "transcripts" / "2024" / "docket"
            trans_dir.mkdir(parents=True)

            (trans_dir / "one.json").write_text(
                json.dumps(
                    {
                        "type": "opinion",
                        "term": "2024",
                        "case_docket": "docket",
                        "turns": [{"is_valid": True, "speaker_name": "Justice A"}],
                    }
                )
            )
            (trans_dir / "three.json").write_text(
                json.dumps(
                    {
                        "type": "oral_argument",
                        "term": "2024",
                        "case_docket": "docket",
                        "turns": [
                            {"is_valid": True, "speaker_name": "Justice A"},
                            {"is_valid": True, "speaker_name": "Justice B"},
                            {"is_valid": True, "speaker_name": "Advocate C"},
                        ],
                    }
                )
            )

            result = runner.invoke(
                app, ["stats", "transcripts", "--data-dir", str(data_dir)]
            )
            output = _strip_ansi(result.output)

            assert result.exit_code == 0
            assert "Recordings by speaker count" in output
            assert "1 speaker:" in output
            assert "3-5 speakers:" in output

    def test_displays_top_recordings_by_speakers(self) -> None:
        """Display top recordings with most speakers."""
        with tempfile.TemporaryDirectory() as tmpdir:
            data_dir = Path(tmpdir)
            trans_dir = data_dir / "transcripts" / "2024" / "docket"
            trans_dir.mkdir(parents=True)

            many_speakers = [
                {"is_valid": True, "speaker_name": f"Speaker {i}"} for i in range(10)
            ]
            (trans_dir / "many.json").write_text(
                json.dumps(
                    {
                        "type": "oral_argument",
                        "term": "2024",
                        "case_docket": "docket",
                        "turns": many_speakers,
                    }
                )
            )

            result = runner.invoke(
                app, ["stats", "transcripts", "--data-dir", str(data_dir)]
            )
            output = _strip_ansi(result.output)

            assert result.exit_code == 0
            assert "Top 10 recordings by speaker count" in output
            assert "2024/docket (oral_argument) - 10 speakers" in output

    def test_handles_non_directory_entries(self) -> None:
        """Should skip non-directory entries (lines 61, 64)."""
        with tempfile.TemporaryDirectory() as tmpdir:
            data_dir = Path(tmpdir)
            transcripts_dir = data_dir / "transcripts"
            transcripts_dir.mkdir(parents=True)

            # Create a file (not a directory) in transcripts_dir
            (transcripts_dir / "not_a_dir.txt").write_text("test")

            # Create a valid term directory with a file (not a directory) inside
            term_dir = transcripts_dir / "2024"
            term_dir.mkdir()
            (term_dir / "not_a_dir.json").write_text("test")

            # Create a valid docket directory
            docket_dir = term_dir / "22-123"
            docket_dir.mkdir()
            transcript = {"type": "oral_argument", "turns": []}
            (docket_dir / "transcript.json").write_text(json.dumps(transcript))

            result = runner.invoke(
                app, ["stats", "transcripts", "--data-dir", str(data_dir)]
            )
            output = _strip_ansi(result.output)

            assert result.exit_code == 0
            # Should only count the valid transcript, skip non-directories
            assert "Total transcripts: 1" in output

    def test_handles_invalid_json_files(self) -> None:
        """Should handle JSON decode errors gracefully (lines 108-109)."""
        with tempfile.TemporaryDirectory() as tmpdir:
            data_dir = Path(tmpdir)
            trans_dir = data_dir / "transcripts" / "2024" / "22-123"
            trans_dir.mkdir(parents=True)

            # Create invalid JSON file
            (trans_dir / "invalid.json").write_text("{ invalid json }")

            # Create valid transcript
            transcript = {"type": "oral_argument", "turns": []}
            (trans_dir / "valid.json").write_text(json.dumps(transcript))

            result = runner.invoke(
                app, ["stats", "transcripts", "--data-dir", str(data_dir)]
            )
            output = _strip_ansi(result.output)

            assert result.exit_code == 0
            # Should only count the valid transcript
            assert "Total transcripts: 1" in output

    def test_handles_missing_keys_in_transcript_data(self) -> None:
        """Should handle KeyError when transcript data is missing required keys (lines 108-109)."""
        with tempfile.TemporaryDirectory() as tmpdir:
            data_dir = Path(tmpdir)
            trans_dir = data_dir / "transcripts" / "2024" / "22-123"
            trans_dir.mkdir(parents=True)

            # Create transcript file with missing keys
            incomplete_transcript = {"type": "oral_argument"}  # Missing turns
            (trans_dir / "incomplete.json").write_text(
                json.dumps(incomplete_transcript)
            )

            # Create valid transcript
            transcript = {"type": "oral_argument", "turns": []}
            (trans_dir / "valid.json").write_text(json.dumps(transcript))

            result = runner.invoke(
                app, ["stats", "transcripts", "--data-dir", str(data_dir)]
            )
            output = _strip_ansi(result.output)

            assert result.exit_code == 0
            # Should handle KeyError gracefully
            assert "Total transcripts: 1" in output or "Total transcripts: 2" in output

    def test_speaker_bucket_11_plus(self) -> None:
        """Should return '11+' for speakers > 10 (line 34)."""
        assert _get_speaker_bucket(11) == "11+"
        assert _get_speaker_bucket(15) == "11+"
        assert _get_speaker_bucket(100) == "11+"
