# Generated by Claude
"""Tests for load_audio memory efficiency (Option B optimization)."""

import gc
import tempfile
import tracemalloc
from pathlib import Path

import numpy as np

from oyez_sa_asr.audio_utils import load_audio, save_audio


def make_sine(sr: int = 16000, dur: float = 0.5, ch: int = 1) -> np.ndarray:
    """Generate a sine wave for testing."""
    t = np.linspace(0, dur, int(sr * dur), dtype=np.float32)
    sine = np.sin(2 * np.pi * 440 * t)
    return sine if ch == 1 else np.stack([sine] * ch, axis=0)


class TestMemoryEfficiency:
    """Test memory efficiency of load_audio (Option B optimization)."""

    def test_chunked_decode_reduces_peak_memory(self) -> None:
        """Verify chunked decode keeps peak memory close to final array size.

        The optimized load_audio should have peak memory ~1x the final array,
        not 4x as with the original implementation.
        """
        sr = 48000
        duration = 10.0
        samples = make_sine(sr=sr, dur=duration, ch=2)

        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / "large.flac"
            save_audio(samples, sr, path)

            gc.collect()
            tracemalloc.start()

            loaded, loaded_sr = load_audio(path)

            _current, peak = tracemalloc.get_traced_memory()
            tracemalloc.stop()

            final_size = loaded.nbytes
            peak_ratio = peak / final_size
            assert peak_ratio < 2.5, (
                f"Peak memory {peak / (1024**2):.1f}MB is {peak_ratio:.1f}x "
                f"final array size {final_size / (1024**2):.1f}MB (should be <2.5x)"
            )

            assert loaded_sr == sr
            assert loaded.shape == samples.shape

    def test_large_file_memory_stable(self) -> None:
        """Test that processing larger files doesn't cause memory spikes."""
        sr = 44100
        ratios = []

        for duration in [1.0, 5.0]:
            samples = make_sine(sr=sr, dur=duration, ch=1)

            with tempfile.TemporaryDirectory() as d:
                path = Path(d) / f"test_{duration}s.flac"
                save_audio(samples, sr, path)

                gc.collect()
                tracemalloc.start()

                loaded, _ = load_audio(path)

                _, peak = tracemalloc.get_traced_memory()
                tracemalloc.stop()

                ratio = peak / loaded.nbytes
                ratios.append(ratio)

                del loaded
                gc.collect()

        for i, ratio in enumerate(ratios):
            assert ratio < 3.0, f"File {i} has ratio {ratio:.1f}x (should be <3x)"

        ratio_diff = abs(ratios[0] - ratios[1])
        assert ratio_diff < 1.5
