# Generated by Claude
"""Tests for process speakers command."""

import json
import re
import tempfile
from pathlib import Path

from typer.testing import CliRunner

from oyez_sa_asr.cli import app

runner = CliRunner()


def _strip_ansi(text: str) -> str:
    """Strip ANSI escape codes from a string."""
    return re.sub(r"\x1b\[[0-9;]*m", "", text)


def _create_transcript(
    term: str,
    docket: str,
    transcript_type: str = "oral_argument",
    turns: list[dict] | None = None,
) -> dict:
    """Create a mock transcript structure."""
    if turns is None:
        turns = [
            {
                "index": 0,
                "speaker_id": 123,
                "speaker_name": "Justice Smith",
                "start": 0.0,
                "stop": 10.0,
                "duration": 10.0,
                "is_valid": True,
                "word_count": 50,
                "text": "This is a test.",
            },
            {
                "index": 1,
                "speaker_id": 456,
                "speaker_name": "Mr. Jones",
                "start": 10.0,
                "stop": 20.0,
                "duration": 10.0,
                "is_valid": True,
                "word_count": 60,
                "text": "Response to the test.",
            },
        ]
    return {
        "id": 1,
        "case_docket": docket,
        "term": term,
        "type": transcript_type,
        "title": "Oral Argument",
        "metadata": {"duration_seconds": 100.0},
        "turns": turns,
    }


def _create_case(term: str, docket: str, name: str = "Test v. Case") -> dict:
    """Create a mock case structure."""
    return {
        "id": 1,
        "name": name,
        "docket_number": docket,
        "term": term,
        "href": f"https://api.oyez.org/cases/{term}/{docket}",
    }


class TestProcessSpeakersHelp:
    """Tests for help output."""

    def test_help(self) -> None:
        """Shows help message."""
        result = runner.invoke(app, ["process", "speakers", "--help"])
        assert result.exit_code == 0
        assert "speakers" in result.output.lower()


class TestProcessSpeakersMissingData:
    """Tests for missing data handling."""

    def test_missing_transcripts_dir(self) -> None:
        """Fails gracefully when transcripts directory doesn't exist."""
        with tempfile.TemporaryDirectory() as tmpdir:
            result = runner.invoke(
                app,
                [
                    "process",
                    "speakers",
                    "--transcripts-dir",
                    str(Path(tmpdir) / "missing"),
                    "--output-dir",
                    str(Path(tmpdir) / "output"),
                ],
            )
            output = _strip_ansi(result.output)
            assert "not found" in output.lower() or "no transcripts" in output.lower()


class TestProcessSpeakersBasic:
    """Tests for basic speaker processing."""

    def test_processes_speakers_from_transcripts(self) -> None:
        """Aggregates speakers from transcript files."""
        with tempfile.TemporaryDirectory() as tmpdir:
            data_dir = Path(tmpdir)

            # Create transcripts directory structure
            transcripts_dir = data_dir / "transcripts" / "2024" / "23-1234"
            transcripts_dir.mkdir(parents=True)
            transcript = _create_transcript("2024", "23-1234")
            (transcripts_dir / "oral_argument.json").write_text(json.dumps(transcript))

            # Create cases directory for case names
            cases_dir = data_dir / "cases" / "2024"
            cases_dir.mkdir(parents=True)
            case = _create_case("2024", "23-1234", "Smith v. Jones")
            (cases_dir / "23-1234.json").write_text(json.dumps(case))

            output_dir = data_dir / "speakers"

            result = runner.invoke(
                app,
                [
                    "process",
                    "speakers",
                    "--transcripts-dir",
                    str(data_dir / "transcripts"),
                    "--cases-dir",
                    str(data_dir / "cases"),
                    "--output-dir",
                    str(output_dir),
                ],
            )

            assert result.exit_code == 0
            output = _strip_ansi(result.output)
            assert "processed" in output.lower() or "done" in output.lower()

            # Check output files exist
            speaker_files = list(output_dir.glob("*.json"))
            assert len(speaker_files) == 2

            # Check Justice Smith file
            smith_file = output_dir / "123_justice_smith.json"
            assert smith_file.exists()
            with smith_file.open() as f:
                smith_data = json.load(f)
            assert smith_data["id"] == 123
            assert smith_data["name"] == "Justice Smith"
            assert smith_data["role"] == "justice"
            assert smith_data["totals"]["turns"] == 1

            # Check Mr. Jones file
            jones_file = output_dir / "456_mr_jones.json"
            assert jones_file.exists()
            with jones_file.open() as f:
                jones_data = json.load(f)
            assert jones_data["role"] == "advocate"


class TestProcessSpeakersAggregation:
    """Tests for speaker aggregation across multiple recordings."""

    def test_aggregates_across_multiple_transcripts(self) -> None:
        """Combines speaker data from multiple transcripts."""
        with tempfile.TemporaryDirectory() as tmpdir:
            data_dir = Path(tmpdir)
            transcripts_dir = data_dir / "transcripts"
            cases_dir = data_dir / "cases"
            output_dir = data_dir / "speakers"

            # Create two transcripts with same speaker
            for docket in ["23-1234", "23-5678"]:
                t_dir = transcripts_dir / "2024" / docket
                t_dir.mkdir(parents=True)
                transcript = _create_transcript(
                    "2024",
                    docket,
                    turns=[
                        {
                            "index": 0,
                            "speaker_id": 123,
                            "speaker_name": "Justice Smith",
                            "start": 0.0,
                            "stop": 10.0,
                            "duration": 10.0,
                            "is_valid": True,
                            "word_count": 50,
                            "text": "Test.",
                        }
                    ],
                )
                (t_dir / "oral_argument.json").write_text(json.dumps(transcript))

                c_dir = cases_dir / "2024"
                c_dir.mkdir(parents=True, exist_ok=True)
                case = _create_case("2024", docket)
                (c_dir / f"{docket}.json").write_text(json.dumps(case))

            result = runner.invoke(
                app,
                [
                    "process",
                    "speakers",
                    "--transcripts-dir",
                    str(transcripts_dir),
                    "--cases-dir",
                    str(cases_dir),
                    "--output-dir",
                    str(output_dir),
                ],
            )

            assert result.exit_code == 0

            # Check aggregated totals
            smith_file = output_dir / "123_justice_smith.json"
            with smith_file.open() as f:
                smith_data = json.load(f)

            assert smith_data["totals"]["recordings"] == 2
            assert smith_data["totals"]["cases"] == 2
            assert smith_data["totals"]["turns"] == 2


class TestProcessSpeakersTermFilter:
    """Tests for term filtering."""

    def test_filters_by_term(self) -> None:
        """Only processes specified terms."""
        with tempfile.TemporaryDirectory() as tmpdir:
            data_dir = Path(tmpdir)
            transcripts_dir = data_dir / "transcripts"
            cases_dir = data_dir / "cases"
            output_dir = data_dir / "speakers"

            # Create transcripts for two terms
            for term in ["2023", "2024"]:
                t_dir = transcripts_dir / term / "docket"
                t_dir.mkdir(parents=True)
                transcript = _create_transcript(term, "docket")
                (t_dir / "oral_argument.json").write_text(json.dumps(transcript))

                c_dir = cases_dir / term
                c_dir.mkdir(parents=True)
                case = _create_case(term, "docket")
                (c_dir / "docket.json").write_text(json.dumps(case))

            result = runner.invoke(
                app,
                [
                    "process",
                    "speakers",
                    "--transcripts-dir",
                    str(transcripts_dir),
                    "--cases-dir",
                    str(cases_dir),
                    "--output-dir",
                    str(output_dir),
                    "--term",
                    "2024",
                ],
            )

            assert result.exit_code == 0

            # Check only 2024 data was processed
            smith_file = output_dir / "123_justice_smith.json"
            with smith_file.open() as f:
                smith_data = json.load(f)

            assert "2024" in smith_data["by_term"]
            assert "2023" not in smith_data["by_term"]
