# Generated by Claude
"""TDD tests for process audio subcommand."""

import json
import math
import re
import tempfile
from pathlib import Path

import numpy as np
from typer.testing import CliRunner

from oyez_sa_asr.audio_utils import save_audio
from oyez_sa_asr.cli import app

runner = CliRunner()


def strip_ansi(text: str) -> str:
    """Remove ANSI escape codes from text."""
    return re.sub(r"\x1b\[[0-9;]*m", "", text)


def make_sine(sr: int = 16000, dur: float = 0.5) -> np.ndarray:
    """Generate a sine wave."""
    t = np.linspace(0, dur, int(sr * dur), dtype=np.float32)
    return np.sin(2 * math.pi * 440 * t)


class TestProcessAudioHelp:
    """Test process audio help."""

    def test_help(self) -> None:
        """Should show help for process audio."""
        result = runner.invoke(app, ["process", "audio", "--help"])
        assert result.exit_code == 0
        output = strip_ansi(result.output)
        assert "--cache-dir" in output
        assert "--output-dir" in output


class TestProcessAudioExecution:
    """Test process audio command execution."""

    def test_empty_cache(self) -> None:
        """Should handle empty cache gracefully."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cache_dir = Path(tmpdir) / "cache"
            output_dir = Path(tmpdir) / "data"
            result = runner.invoke(
                app,
                ["process", "audio", "-c", str(cache_dir), "-o", str(output_dir)],
            )
            assert result.exit_code == 0
            output = strip_ansi(result.output)
            assert "0" in output or "No" in output

    def test_processes_mp3_to_flac(self) -> None:
        """Should convert MP3 to FLAC and save metadata."""
        with tempfile.TemporaryDirectory() as tmpdir:
            # Setup: create cache structure like real audio cache
            cache_dir = Path(tmpdir) / "cache"
            output_dir = Path(tmpdir) / "data"
            mp3_dir = (
                cache_dir / "oyez.case-media.mp3" / "case_data" / "2020" / "19-123"
            )
            mp3_dir.mkdir(parents=True)

            # Create test MP3 file
            samples = make_sine(sr=44100, dur=0.3)
            mp3_path = mp3_dir / "19-123_20201001-argument.mp3"
            save_audio(samples, 44100, mp3_path)

            # Run command
            result = runner.invoke(
                app,
                ["process", "audio", "-c", str(cache_dir), "-o", str(output_dir)],
            )
            assert result.exit_code == 0

            # Check output files
            flac_path = output_dir / "2020" / "19-123" / "19-123_20201001-argument.flac"
            meta_path = (
                output_dir
                / "2020"
                / "19-123"
                / "19-123_20201001-argument.metadata.json"
            )
            assert flac_path.exists(), f"FLAC not found: {flac_path}"
            assert meta_path.exists(), f"Metadata not found: {meta_path}"

            # Verify metadata content
            with meta_path.open() as f:
                meta = json.load(f)
            assert meta["format"] == "mp3"
            assert meta["sample_rate"] == 44100
            assert meta["channels"] == 1
            assert meta["file_size"] > 0
            # Provenance: source_path must point to original cache file
            assert "source_path" in meta, "Metadata must include source_path"
            assert str(mp3_path) in meta["source_path"]

    def test_processes_ogg_to_flac(self) -> None:
        """Should convert OGG to FLAC."""
        with tempfile.TemporaryDirectory() as tmpdir:
            cache_dir = Path(tmpdir) / "cache"
            output_dir = Path(tmpdir) / "data"
            ogg_dir = (
                cache_dir / "oyez.case-media.ogg" / "case_data" / "2021" / "20-456"
            )
            ogg_dir.mkdir(parents=True)

            # Create test OGG file
            samples = make_sine(sr=44100, dur=0.2)
            ogg_path = ogg_dir / "20-456_20210501-opinion.ogg"
            save_audio(samples, 44100, ogg_path)

            result = runner.invoke(
                app,
                ["process", "audio", "-c", str(cache_dir), "-o", str(output_dir)],
            )
            assert result.exit_code == 0

            flac_path = output_dir / "2021" / "20-456" / "20-456_20210501-opinion.flac"
            assert flac_path.exists()
