# Generated by Claude
"""Tests for SpeakerProfile dataclass."""

import tempfile
from pathlib import Path

from oyez_sa_asr.speaker_models import SpeakerProfile


class TestSpeakerProfile:
    """Tests for SpeakerProfile dataclass."""

    def test_create_empty(self) -> None:
        """Create empty profile."""
        profile = SpeakerProfile(id=123, name="John Smith")
        assert profile.id == 123
        assert profile.name == "John Smith"
        assert profile.name_slug == "john_smith"
        assert profile.role == "other"  # Default before finalize
        assert profile.recordings == []
        assert profile.cases == set()

    def test_add_appearance(self) -> None:
        """Add recording appearance."""
        profile = SpeakerProfile(id=123, name="John Smith")
        profile.add_appearance(
            term="2024",
            docket="23-1234",
            case_name="Smith v. Jones",
            transcript_type="oral_argument",
            turns=10,
            duration_seconds=120.5,
            word_count=500,
        )
        assert len(profile.recordings) == 1
        assert profile.recordings[0].term == "2024"
        assert "2024/23-1234" in profile.cases

    def test_totals_aggregation(self) -> None:
        """Aggregate totals correctly."""
        profile = SpeakerProfile(id=123, name="John Smith")
        profile.add_appearance(
            term="2024",
            docket="23-1234",
            case_name="Case 1",
            transcript_type="oral_argument",
            turns=10,
            duration_seconds=100.0,
            word_count=500,
        )
        profile.add_appearance(
            term="2024",
            docket="23-5678",
            case_name="Case 2",
            transcript_type="oral_argument",
            turns=20,
            duration_seconds=200.0,
            word_count=1000,
        )
        totals = profile.get_totals()
        assert totals["recordings"] == 2
        assert totals["cases"] == 2
        assert totals["turns"] == 30
        assert totals["duration_seconds"] == 300.0
        assert totals["word_count"] == 1500
        assert totals["avg_words_per_turn"] == 50.0

    def test_by_term_aggregation(self) -> None:
        """Aggregate by term correctly."""
        profile = SpeakerProfile(id=123, name="John Smith")
        profile.add_appearance(
            term="2023",
            docket="22-1234",
            case_name="Case 1",
            transcript_type="oral_argument",
            turns=10,
            duration_seconds=100.0,
            word_count=500,
        )
        profile.add_appearance(
            term="2024",
            docket="23-5678",
            case_name="Case 2",
            transcript_type="oral_argument",
            turns=20,
            duration_seconds=200.0,
            word_count=1000,
        )
        by_term = profile.get_by_term()
        assert "2023" in by_term
        assert "2024" in by_term
        assert by_term["2023"]["turns"] == 10
        assert by_term["2024"]["turns"] == 20

    def test_first_last_appearance(self) -> None:
        """Track first and last appearance dates."""
        profile = SpeakerProfile(id=123, name="John Smith")
        profile.update_appearance_dates("2020-10-05")
        profile.update_appearance_dates("2024-01-15")
        profile.update_appearance_dates("2022-06-20")

        assert profile.first_appearance == "2020-10-05"
        assert profile.last_appearance == "2024-01-15"

    def test_to_dict(self) -> None:
        """Convert to full dictionary."""
        profile = SpeakerProfile(id=123, name="Test Speaker")
        profile.add_appearance(
            term="2024",
            docket="23-1234",
            case_name="Test Case",
            transcript_type="oral_argument",
            turns=10,
            duration_seconds=100.0,
            word_count=500,
        )
        profile.update_appearance_dates("2024-01-15")
        profile.finalize()

        result = profile.to_dict()
        assert result["id"] == 123
        assert result["name"] == "Test Speaker"
        assert result["name_slug"] == "test_speaker"
        assert result["role"] == "other"
        assert result["first_appearance"] == "2024-01-15"
        assert result["last_appearance"] == "2024-01-15"
        assert "totals" in result
        assert "by_term" in result
        assert "recordings" in result
        assert "cases" in result

    def test_save_to_other_subdir(self) -> None:
        """Save non-justice to other subdirectory."""
        profile = SpeakerProfile(id=123, name="Test Speaker")
        profile.add_appearance(
            term="2024",
            docket="23-1234",
            case_name="Test Case",
            transcript_type="oral_argument",
            turns=10,
            duration_seconds=100.0,
            word_count=500,
        )

        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir)
            saved_path = profile.save(output_dir)

            assert saved_path.exists()
            assert saved_path.parent.name == "other"
            assert saved_path.name == "123_test_speaker.json"

    def test_save_to_justices_subdir(self) -> None:
        """Save justice to justices subdirectory."""
        profile = SpeakerProfile(id=456, name="Justice Test")

        # Add enough appearances to be detected as justice (200+ cases, 5+ terms)
        for term in ["2018", "2019", "2020", "2021", "2022", "2023"]:
            for i in range(40):
                profile.add_appearance(
                    term=term,
                    docket=f"{term[-2:]}-{i}",
                    case_name=f"Case {i}",
                    transcript_type="oral_argument",
                    turns=5,
                    duration_seconds=100.0,
                    word_count=500,
                )

        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir)
            saved_path = profile.save(output_dir)

            assert saved_path.exists()
            assert saved_path.parent.name == "justices"
            assert profile.role == "justice"

    def test_get_filename(self) -> None:
        """Generate correct filename."""
        profile = SpeakerProfile(id=15049, name="John G. Roberts, Jr.")
        assert profile.get_filename() == "15049_john_g_roberts_jr.json"
