# Generated by Cursor
# Edited by Cursor (single_letter_parens, number_parens, dash)
"""Normalization helpers for rule candidates: span -> spoken corrections (ASR)."""

import re
import subprocess
import unicodedata

from scripts.rule_normalizations._number_words import (
    digit_to_word,
    number_to_ordinal,
    number_to_words,
    roman_to_int,
)

# Literal pronunciation of single letter (a->ay, b->bee, ...). Used by single_letter_parens rule.
LETTER_PRONUNCIATION: dict[str, str] = {
    "a": "ay",
    "b": "bee",
    "c": "cee",
    "d": "dee",
    "e": "ee",
    "f": "eff",
    "g": "gee",
    "h": "aych",
    "i": "eye",
    "j": "jay",
    "k": "kay",
    "l": "ell",
    "m": "em",
    "n": "en",
    "o": "oh",
    "p": "pee",
    "q": "cue",
    "r": "ar",
    "s": "ess",
    "t": "tee",
    "u": "you",
    "v": "vee",
    "w": "double-u",
    "x": "ex",
    "y": "wy",
    "z": "zee",
}
STANDARD_DASH = "-"

# Non-speech bracket content (case-insensitive, after strip/rstrip dot). Edited by Cursor.
NON_SPEECH_BRACKET_CONTENT = frozenset(
    {
        "inaudible",
        "voice overlap",
        "laughter",
        "laughs",
        "coughing",
        "audio cut",
        "recess",
        "indiscernible",
        "mirth",
        "sneezes",
        "sighs",
        "applause",
        "break",
        "luncheon",
        "lunch",
        "interruption",
        "banging",
        "attempt to laughter",
    }
)
# Unbracketed non-speech phrases (case-insensitive, strip trailing period). Edited by Cursor.
UNBRACKETED_NON_SPEECH_PHRASES = frozenset({"generallaughter", "general laughter"})
ORDINAL_SUFFIX_RE = re.compile(r"^(\d+)(st|nd|rd|th)$", re.IGNORECASE)


def _digits_to_spoken(digit_str: str) -> list[str]:
    """Spoken form of digit string for codes: 640->six forty, 707->seven oh seven. Edited by Cursor."""
    result: list[str] = []
    if not digit_str or not digit_str.isdigit():
        return result
    n = int(digit_str)
    if len(digit_str) == 1:
        result = [digit_to_word(n)]
    elif len(digit_str) == 2:
        result = [number_to_words(n)]
    elif len(digit_str) == 3:
        if 10 <= n % 100 <= 99 and n % 10 == 0:
            result = [number_to_words(n // 100), number_to_words(n % 100)]
        else:
            result = [digit_to_word(int(d)) if d != "0" else "oh" for d in digit_str]
    elif len(digit_str) == 4:
        result = [
            number_to_words(int(digit_str[:2])),
            number_to_words(int(digit_str[2:])),
        ]
    else:
        result = [digit_to_word(int(d)) if d != "0" else "oh" for d in digit_str]
    return result


def normalize_digit_letter_mixed(span: str) -> list[str]:
    """Digit-letter mixed (2d, A2, 640L, 707{b}, 1392(d)) -> spoken form. Edited by Cursor."""
    s = span.strip()
    if not s:
        return [span]
    parts: list[str] = []
    i = 0
    while i < len(s):
        if s[i].isdigit():
            j = i
            while j < len(s) and s[j].isdigit():
                j += 1
            parts.append(("digits", s[i:j]))
            i = j
        elif s[i] in "({" and i + 1 < len(s):
            close = ")" if s[i] == "(" else "}"
            k = s.find(close, i + 1)
            if k != -1:
                inner = s[i + 1 : k].strip()
                if len(inner) == 1 and inner.isalpha():
                    parts.append(("letter", inner))
                    i = k + 1
                    continue
            i += 1
        elif s[i].isalpha():
            j = i
            while j < len(s) and s[j].isalpha():
                j += 1
            parts.append(("letter", s[i:j]))
            i = j
        else:
            i += 1
    out_tokens: list[str] = []
    for kind, val in parts:
        if kind == "digits":
            out_tokens.extend(_digits_to_spoken(val))
        elif kind == "letter":
            for c in val:
                out_tokens.append(LETTER_PRONUNCIATION.get(c.lower(), c))
        # skip "raw" (bracket we didn't parse as single letter)
    if not out_tokens:
        return [span]
    return [" ".join(out_tokens)]


def normalize_single_letter_parens(span: str) -> list[str]:
    """Single letter in parentheses (with optional spaces) -> letter pronunciation."""
    s = span.strip()
    if len(s) < 3 or s[0] != "(" or s[-1] != ")":
        return [span]
    inner = s[1:-1].strip()
    if len(inner) != 1 or not inner.isalpha():
        return [span]
    letter = inner.lower()
    if letter in LETTER_PRONUNCIATION:
        return [LETTER_PRONUNCIATION[letter]]
    return [span]


def normalize_number_parens(span: str) -> list[str]:
    """Return spoken number for number in parentheses (e.g. (32)->thirty two)."""
    s = span.strip()
    if len(s) < 3 or s[0] != "(" or s[-1] != ")":
        return [span]
    inner = s[1:-1].strip()
    if not inner.isdigit():
        return [span]
    try:
        n = int(inner)
        if 0 <= n <= 999:
            return [number_to_words(n)]
    except (ValueError, KeyError):
        pass
    return [span]


def normalize_dash(span: str) -> list[str]:  # noqa: ARG001
    """Return single standard dash for non-standard dash or dash sequence."""
    return [STANDARD_DASH]


def normalize_known_names(span: str) -> list[str]:
    """Known name patterns (McLaughlin, FitzGerald): no correction, mark as handled. Edited by Cursor."""
    return [span]


def normalize_numbered_list_marker(span: str) -> list[str]:
    """Numbered list marker 1) -> one, 5) -> five. Edited by Cursor."""
    s = span.strip()
    if not s.endswith(")"):
        return [span]
    num_part = s[:-1].strip()
    if not num_part.isdigit():
        return [span]
    try:
        n = int(num_part)
        if 1 <= n <= 99:
            return [number_to_words(n)]
    except (ValueError, KeyError):
        pass
    return [span]


def normalize_non_speech_brackets(span: str) -> list[str]:
    """Return empty string for (Inaudible), [Laughter], Generallaughter., etc.; else identity. Edited by Cursor."""
    s = span.strip().rstrip(".").strip()
    phrase_norm = " ".join(s.lower().split())
    if phrase_norm in UNBRACKETED_NON_SPEECH_PHRASES:
        return [""]
    if len(s) < 3 or s[0] not in "([{" or s[-1] not in ")]}":
        return [span]
    content = s[1:-1].strip().rstrip(".").strip()
    content_norm = " ".join(content.lower().split())
    if content_norm in NON_SPEECH_BRACKET_CONTENT:
        return [""]
    return [span]


def normalize_ordinal(span: str) -> list[str]:
    """Return spoken ordinal for 37th, 3rd, etc. (e.g. thirty seventh, third)."""
    s = span.strip()
    m = ORDINAL_SUFFIX_RE.fullmatch(s)
    if not m:
        return [span]
    try:
        n = int(m.group(1))
        if 1 <= n <= 99:
            return [number_to_ordinal(n)]
    except (ValueError, KeyError, IndexError):
        pass
    return [span]


def normalize_vote_tally(span: str) -> list[str]:
    """Normalize vote tally '9-0' -> ['nine to zero']."""
    parts = span.strip().split("-")
    if len(parts) != 2 or len(parts[0]) != 1 or len(parts[1]) != 1:
        return [span]
    try:
        a, b = int(parts[0]), int(parts[1])
        if 0 <= a <= 9 and 0 <= b <= 9:
            return [f"{digit_to_word(a)} to {digit_to_word(b)}"]
    except ValueError:
        pass
    return [span]


def normalize_year(span: str) -> list[str]:
    """Normalize four-digit year -> spoken form (e.g. 1999 -> nineteen ninety nine)."""
    s = span.strip()
    if len(s) != 4 or not s.isdigit():
        return [span]
    try:
        n = int(s)
        if 1900 <= n <= 2099:
            c, d = divmod(n, 100)
            if d == 0:
                return [f"{number_to_words(c)} hundred"]
            return [f"{number_to_words(c)} {number_to_words(d)}"]
    except (ValueError, KeyError):
        pass
    return [span]


def normalize_roman_numeral(span: str) -> list[str]:
    """Normalize Roman numeral (II-XII) -> spoken number."""
    val = roman_to_int(span.strip().upper())
    if val is None:
        return [span]
    return [number_to_words(val)]


def normalize_percentage(span: str) -> list[str]:
    """Normalize percentage (50% or 25 percent) -> spoken form."""
    s = span.strip().replace(" ", "")
    num_str = s.rstrip("%").replace("percent", "").strip()
    if not num_str.isdigit():
        return [span]
    try:
        n = int(num_str)
        return [f"{number_to_words(n)} percent"]
    except (ValueError, KeyError):
        return [span]


def normalize_double_quote(span: str) -> list[str]:  # noqa: ARG001
    """Double-quote (open/close): same 10 spoken options for both. Span ignored."""
    return [
        "",
        "quote",
        "start quote",
        "open quote",
        "open the quote",
        "I quote",
        "and I quote",
        "end quote",
        "close quote",
        "close the quote",
    ]


# Abbreviated decade 00s-90s -> spoken. Edited by Cursor.
ABBREV_DECADE_WORDS = (
    "hundreds",  # 00s
    "tens",  # 10s
    "twenties",
    "thirties",
    "forties",
    "fifties",
    "sixties",
    "seventies",
    "eighties",
    "nineties",
)


def normalize_decade(span: str) -> list[str]:
    """Normalize decade (1980s, 20s) -> spoken form (nineteen eighties, twenties). Edited by Cursor."""
    s = span.strip()
    result: list[str] = [span]
    if not s.endswith("s"):
        return result
    base = s[:-1]
    if not base.isdigit():
        return result
    try:
        n = int(base)
        if len(s) == 3:
            # Abbreviated: 20s -> twenties, 50s -> fifties, 10s -> tens
            if 0 <= n <= 99:
                tens = n // 10
                result = [ABBREV_DECADE_WORDS[tens]]
        elif len(s) == 5 and 1800 <= n <= 2099:
            c, d = divmod(n, 100)
            if d == 0:
                result = [f"{number_to_words(c)} hundreds"]
            else:
                tens = d // 10
                if tens in {0, 1}:
                    result = [f"{number_to_words(c)} {number_to_words(d)}s"]
                else:
                    tens_word = (
                        "twenties",
                        "thirties",
                        "forties",
                        "fifties",
                        "sixties",
                        "seventies",
                        "eighties",
                        "nineties",
                    )[tens - 2]
                    result = [f"{number_to_words(c)} {tens_word}"]
    except (ValueError, KeyError, IndexError):
        pass
    return result


# Latin extended: multiple correction strategies (simple_map, uroman, uroman -l <lcode>).
# Edited by Cursor.
LATIN_UROMAN_LANGS = (
    "pol",
    "spa",
    "fra",
    "por",
    "tur",
    "cat",
    "deu",
    "hun",
    "ita",
    "nld",
    "glg",
)


def latin_simple_map(span: str) -> str:
    """Map Latin accented characters to ASCII (e.g. à->a, é->e) via NFD + strip combining."""
    s = span.strip()
    nfd = unicodedata.normalize("NFD", s)
    return "".join(c for c in nfd if unicodedata.category(c) != "Mn")


def _uroman_romanize(text: str, lang: str | None = None) -> str | None:
    """Romanize text via uroman (Python package or CLI). Returns None if uroman unavailable or fails."""
    try:
        import uroman  # noqa: PLC0415

        if lang is not None:
            return uroman.romanize(text, lang=lang)
        return uroman.romanize(text)
    except Exception:  # noqa: S110
        pass
    try:
        cmd = ["uroman", "-l", lang] if lang else ["uroman"]
        result = subprocess.run(  # noqa: S603
            cmd,
            input=text,
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
        if result.returncode == 0 and result.stdout:
            return result.stdout.strip()
    except (FileNotFoundError, subprocess.TimeoutExpired, Exception):  # noqa: S110
        pass
    return None


def normalize_latin(span: str) -> list[dict]:
    """Latin extended: multiple corrections (simple_map, uroman, uroman_<lcode>). Returns list of {text, method}."""
    out: list[dict] = []
    simple = latin_simple_map(span)
    out.append({"text": simple, "method": "simple_map"})
    seen: set[str] = set()
    seen.add(simple)

    def add(text: str | None, method: str) -> None:
        if text is None or not text.strip():
            return
        t = text.strip()
        if t not in seen:
            seen.add(t)
            out.append({"text": t, "method": method})

    uroman_default = _uroman_romanize(span)
    add(uroman_default, "uroman")
    for lc in LATIN_UROMAN_LANGS:
        u = _uroman_romanize(span, lc)
        add(u, f"uroman_{lc}")
    return out
