# Generated by Cursor (plan item 8: all-caps 6+ letters, no correction)
"""Scan for all-caps words 6+ letters — identity (handled, no correction)."""

import re

ALL_CAPS_ACCEPT_RE = re.compile(r"\b[A-Z]{6,}\b")


def scan_turn_all_caps_accept(
    text: str,
    path_str: str = "",
) -> list[tuple[str, int, str, str]]:
    """Emit (all_caps_accept, start_index, span, path_str) for each match."""
    result: list[tuple[str, int, str, str]] = []
    for m in ALL_CAPS_ACCEPT_RE.finditer(text):
        result.append(("all_caps_accept", m.start(), m.group(0), path_str))
    return result
