# Generated by Cursor (plan: bracket sentence 4+ words unwrap)
"""Scan for bracketed content with 4+ words; unwrap (return inner text only). Excludes non-speech."""

import re

from scripts.rule_normalizations import is_non_speech_content

PAREN_RE = re.compile(r"\(([^)]+)\)")
SQUARE_RE = re.compile(r"\[([^\]]+)\]")
MIN_WORDS = 4


def _word_count(content: str) -> int:
    return len(content.strip().split())


def _content_normalized(content: str) -> str:
    return " ".join(content.strip().rstrip(".").strip().lower().split())


def scan_turn_bracket_sentence(
    text: str,
    path_str: str = "",
) -> list[tuple[str, int, str, str]]:
    """Emit (bracket_sentence_unwrap, start_index, full_span, path_str) for (..) or [..] with 4+ words."""
    result: list[tuple[str, int, str, str]] = []
    for pattern, open_c, close_c in (
        (PAREN_RE, "(", ")"),
        (SQUARE_RE, "[", "]"),
    ):
        for m in pattern.finditer(text):
            content = m.group(1)
            if _word_count(content) < MIN_WORDS:
                continue
            if is_non_speech_content(_content_normalized(content)):
                continue
            full_span = open_c + content + close_c
            result.append(("bracket_sentence_unwrap", m.start(), full_span, path_str))
    return result
