# Generated by Cursor
"""Scan for dash-like runs; emit only when span is not a single standard hyphen."""

import re

from scripts.rule_normalizations import STANDARD_DASH

# Hyphen U+002D, nbsp hyphen U+2011, en U+2013, em U+2014, horizontal bar U+2015, ellipsis U+2026, dot operator U+22C5 (⋅). Edited by Cursor (TDD item 3).
DASH_LIKE_RE = re.compile(r"[-\u2011\u2013\u2014\u2015\u2026\u22c5]+")
# ASCII dot ellipsis (.., ..., ....) -> same rule as dash. Edited by Cursor.
DOT_ELLIPSIS_RE = re.compile(r"\.{2,}")
# Parenthesized single dot (.) or ( . ) -> dash. Edited by Cursor.
PAREN_DOT_RE = re.compile(r"\(\s*\.\s*\)")


def scan_turn_dashes(
    text: str,
    path_str: str = "",
) -> list[tuple[str, int, str, str]]:
    """
    Scan text for dash-like runs and dot ellipsis; emit (rule_id, start_index, span, path_str).

    Skip when span is exactly one standard hyphen (no normalization needed).
    """
    result: list[tuple[str, int, str, str]] = []
    for m in DASH_LIKE_RE.finditer(text):
        span = m.group(0)
        if span == STANDARD_DASH:
            continue
        result.append(("dash", m.start(), span, path_str))
    for m in DOT_ELLIPSIS_RE.finditer(text):
        result.append(("dash", m.start(), m.group(0), path_str))
    for m in PAREN_DOT_RE.finditer(text):
        result.append(("dash", m.start(), m.group(0), path_str))
    return result
