# Generated by Cursor (plan item 6: dual notation)
# Edited by Cursor (variants: [<X>], <X> [= Y], <X> [citation])
"""Scan for dual notation <X> [= Y], <X> [citation], [<X>]; emit (rule_id, start, full span, path_str)."""

import re

# <...> [= ...] with optional spaces around =
DUAL_NOTATION_EQUALS_RE = re.compile(r"<[^>]+>\s*\[\s*=[^\]]*\]")
# <...> [citation] e.g. [81-523] (no equals)
DUAL_NOTATION_CITATION_RE = re.compile(r"<[^>]+>\s*\[[^\]=][^\]]*\]")
# [<...>] square bracket wrapping angle
DUAL_NOTATION_BRACKET_WRAPPED_RE = re.compile(r"\[\s*<[^>]+>\s*\]")


def scan_turn_dual_notation(
    text: str,
    path_str: str = "",
) -> list[tuple[str, int, str, str]]:
    """Emit (dual_notation, start_index, span, path_str) for each dual-notation match."""
    result: list[tuple[str, int, str, str]] = []
    seen: set[tuple[int, str]] = set()
    for pattern in (
        DUAL_NOTATION_BRACKET_WRAPPED_RE,
        DUAL_NOTATION_EQUALS_RE,
        DUAL_NOTATION_CITATION_RE,
    ):
        for m in pattern.finditer(text):
            key = (m.start(), m.group(0))
            if key not in seen:
                seen.add(key)
                result.append(("dual_notation", m.start(), m.group(0), path_str))
    return result
