# Generated by Cursor (plan item 7: half symbol ½)
"""Scan for half-integer patterns: N½%, N ½ years, etc. U+00BD = ½."""

import re

# N½ or N ½ followed by % or space and unit (years, percent, or generic word). Edited by Cursor.
HALF_PERCENT_RE = re.compile(r"\d+\s*\u00bd\s*%")
HALF_YEARS_RE = re.compile(r"\d+\s*\u00bd\s+(?:years|percent)")
HALF_UNIT_RE = re.compile(r"\d+\s*\u00bd\s+\w+")


def scan_turn_half_number(
    text: str,
    path_str: str = "",
) -> list[tuple[str, int, str, str]]:
    """Emit (half_number, start_index, span, path_str) for each match."""
    result: list[tuple[str, int, str, str]] = []
    seen_spans: set[tuple[int, str]] = set()
    for m in HALF_PERCENT_RE.finditer(text):
        key = (m.start(), m.group(0))
        if key not in seen_spans:
            seen_spans.add(key)
            result.append(("half_number", m.start(), m.group(0), path_str))
    for m in HALF_YEARS_RE.finditer(text):
        key = (m.start(), m.group(0))
        if key not in seen_spans:
            seen_spans.add(key)
            result.append(("half_number", m.start(), m.group(0), path_str))
    for m in HALF_UNIT_RE.finditer(text):
        key = (m.start(), m.group(0))
        if key not in seen_spans:
            seen_spans.add(key)
            result.append(("half_number", m.start(), m.group(0), path_str))
    return result
