# Generated by Cursor (plan: known mixed-case entities TikTok, YouTube, LinkedIn)
"""Scan for known mixed-case entities (TikTok, YouTube, LinkedIn, etc.) — identity, no correction."""

import re

# Edited by Cursor: extensible allowlist
KNOWN_MIXED_CASE_ENTITIES = frozenset(
    {
        "TikTok",
        "YouTube",
        "LinkedIn",
        "eBay",
        "iPhone",
        "FedEx",
        "iTunes",
        "PayPal",
        "McDonald",
        "iPad",
        "iMac",
    }
)


def _build_regex() -> re.Pattern[str]:
    """Build word-boundary regex from allowlist (escape special regex chars)."""
    escaped = sorted(re.escape(s) for s in KNOWN_MIXED_CASE_ENTITIES)
    return re.compile(r"\b(" + "|".join(escaped) + r")\b")


KNOWN_MIXED_CASE_RE = _build_regex()


def scan_turn_known_mixed_case(
    text: str,
    path_str: str = "",
) -> list[tuple[str, int, str, str]]:
    """Emit (known_mixed_case_entities, start_index, span, path_str) for each match."""
    result: list[tuple[str, int, str, str]] = []
    for m in KNOWN_MIXED_CASE_RE.finditer(text):
        result.append(("known_mixed_case_entities", m.start(), m.group(0), path_str))
    return result
