# Generated by Cursor (plan: letter-dash (R-5) -> "ar five")
"""Scan for letter-dash-digit: (R-5) or R-5; emit (rule_id, start, span, path_str)."""

import re

# Optional parens, single letter, dash, one or more digits, optional closing paren
LETTER_DASH_PAREN_RE = re.compile(r"\(\s*[A-Za-z]\s*-\s*\d+\s*\)")
LETTER_DASH_RE = re.compile(r"\b[A-Za-z]-\d+\b")


def scan_turn_letter_dash(
    text: str,
    path_str: str = "",
) -> list[tuple[str, int, str, str]]:
    """Emit (letter_dash_sequence, start_index, span, path_str) for (R-5) and R-5."""
    result: list[tuple[str, int, str, str]] = []
    for m in LETTER_DASH_PAREN_RE.finditer(text):
        result.append(("letter_dash_sequence", m.start(), m.group(0), path_str))
    for m in LETTER_DASH_RE.finditer(text):
        # Avoid double-emitting (R-5) (paren regex already emitted it)
        if m.start() > 0 and text[m.start() - 1] == "(":
            continue
        result.append(("letter_dash_sequence", m.start(), m.group(0), path_str))
    return result
