# Generated by Cursor (plan: letter-Roman clause (C)(iii) -> "cee three")
"""Scan for (single letter)(roman i-xii) as one span; emit (rule_id, start, span, path_str)."""

import re

LETTER_ROMAN_CLAUSE_RE = re.compile(
    r"\(\s*[A-Za-z]\s*\)\s*\(\s*(i|ii|iii|iv|v|vi|vii|viii|ix|x|xi|xii)\s*\)",
    re.IGNORECASE,
)


def scan_turn_letter_roman_clause(
    text: str,
    path_str: str = "",
) -> list[tuple[str, int, str, str]]:
    """Emit (letter_roman_clause, start_index, span, path_str) for each (C)(iii)-style match."""
    result: list[tuple[str, int, str, str]] = []
    for m in LETTER_ROMAN_CLAUSE_RE.finditer(text):
        result.append(("letter_roman_clause", m.start(), m.group(0), path_str))
    return result
