# Generated by Cursor (plan: mixed case 6+ letters accept)
"""Scan for mixed-case tokens 6+ letters; accept (identity). Broader than pascal_case_accept."""

import re

MIXED_CASE_6PLUS_RE = re.compile(r"\b([A-Za-z]{6,})\b")


def _is_mixed_case_6plus(token: str) -> bool:
    """Return True if 6+ letters and has both upper and lower. Edited by Cursor."""
    if len(token) < 6 or not token.isalpha():
        return False
    return token != token.lower() and token != token.upper()


def scan_turn_mixed_case_accept_6plus(
    text: str,
    path_str: str = "",
) -> list[tuple[str, int, str, str]]:
    """Emit (mixed_case_accept_6plus, start_index, span, path_str) for each match."""
    result: list[tuple[str, int, str, str]] = []
    for m in MIXED_CASE_6PLUS_RE.finditer(text):
        token = m.group(1)
        if _is_mixed_case_6plus(token):
            result.append(("mixed_case_accept_6plus", m.start(), token, path_str))
    return result
