# Generated by Cursor (plan: name patterns DiBona, DiMaria, DiCenso)
"""Scan for Di + capitalized word (DiBona, DiMaria, DiCenso); accept (identity)."""

import re

NAME_PATTERN_DI_RE = re.compile(r"\b(Di[A-Z][a-z]+)\b")


def scan_turn_name_pattern_di(
    text: str,
    path_str: str = "",
) -> list[tuple[str, int, str, str]]:
    """Emit (name_pattern_di, start_index, span, path_str) for each match."""
    result: list[tuple[str, int, str, str]] = []
    for m in NAME_PATTERN_DI_RE.finditer(text):
        result.append(("name_pattern_di", m.start(), m.group(1), path_str))
    return result
