# Generated by Cursor (plan: Roman numerals in parentheses)
"""Scan for Roman numerals in parentheses (i) through (xii); emit (rule_id, start, span, path_str)."""

import re

ROMAN_PARENS_RE = re.compile(
    r"\(\s*(i|ii|iii|iv|v|vi|vii|viii|ix|x|xi|xii)\s*\)",
    re.IGNORECASE,
)


def scan_turn_roman_parens(
    text: str,
    path_str: str = "",
) -> list[tuple[str, int, str, str]]:
    """Emit (roman_parens, start_index, span, path_str) for each (i)-(xii) match."""
    result: list[tuple[str, int, str, str]] = []
    for m in ROMAN_PARENS_RE.finditer(text):
        result.append(("roman_parens", m.start(), m.group(0), path_str))
    return result
