# Generated by Cursor (plan: section headers at start/end of turn)
"""Scan for all-caps section headers at start or end of turn; emit span to remove."""

import re

# At end of turn: period or colon then optional space then run to end (allow mixed case e.g. McGILL)
SECTION_HEADER_END_RE = re.compile(r"(?:\.|:)\s*([A-Za-z][A-Za-z0-9.\s]*)$")
# At start of turn: run then period or colon
SECTION_HEADER_START_RE = re.compile(r"^([A-Za-z][A-Za-z0-9.\s]*?)(?:\.|:)\s*")

# Minimum number of uppercase letters to consider a section header
MIN_CAPS = 5


def _is_section_header(s: str) -> bool:
    """Return True if s has enough all-caps character to be a section header."""
    caps = sum(1 for c in s if c.isupper())
    return caps >= MIN_CAPS and (caps >= len(s.replace(" ", "").replace(".", "")) * 0.5)


def scan_turn_section_header(
    text: str,
    path_str: str = "",
) -> list[tuple[str, int, str, str]]:
    """Emit (section_header, start_index, span, path_str) for header at start or end of turn."""
    result: list[tuple[str, int, str, str]] = []
    text_stripped = text.strip()
    if not text_stripped:
        return result
    # End of turn: "... something. REBUTTAL ARGUMENT OF ..."
    end_m = SECTION_HEADER_END_RE.search(text_stripped)
    if end_m:
        span = end_m.group(1).strip()
        if span and _is_section_header(span):
            start_idx = text_stripped.find(span)
            if start_idx >= 0:
                result.append(("section_header", start_idx, span, path_str))
    # Start of turn: "REBUTTAL ARGUMENT OF ... :" or "... ."
    start_m = SECTION_HEADER_START_RE.match(text_stripped)
    if start_m:
        span = start_m.group(1).strip()
        if span and _is_section_header(span):
            result.append(("section_header", 0, span, path_str))
    return result
