# Generated by Cursor (plan: short mixed-case acronym 2-5 letters, half+ caps)
"""Scan for mixed-case tokens 2-5 letters with half or more caps; spell as acronym. Excludes common_acronym allowlist."""

import re

from scripts.rule_normalizations.common_acronym_scan import COMMON_ACRONYM_WORDS

WORD_RE = re.compile(r"\b([A-Za-z]{2,5})\b")


def _is_short_mixed_acronym(token: str) -> bool:
    """Return True if 2-5 letters and at least half are uppercase. Exclude common_acronym allowlist. Edited by Cursor."""
    if len(token) < 2 or len(token) > 5:
        return False
    if not token.isalpha():
        return False
    if token in COMMON_ACRONYM_WORDS:
        return False
    caps = sum(1 for c in token if c.isupper())
    return caps >= (len(token) + 1) // 2


def scan_turn_short_mixed_acronym(
    text: str,
    path_str: str = "",
) -> list[tuple[str, int, str, str]]:
    """Emit (short_mixed_acronym, start_index, span, path_str) for each match."""
    result: list[tuple[str, int, str, str]] = []
    for m in WORD_RE.finditer(text):
        token = m.group(1)
        if _is_short_mixed_acronym(token):
            result.append(("short_mixed_acronym", m.start(), token, path_str))
    return result
