# Generated by Cursor (plan item 5: special currency; plan item 7: [$] N raw)
"""Scan for special currency: [$] N billion/million/... and [$] N raw number."""

import re

# [$] or $ followed by optional space, digits, optional space, multiplier word
SPECIAL_CURRENCY_BRACKET_RE = re.compile(
    r"\[\$\]\s*[\d,]+\s*(?:billion|million|thousand|hundred)\b"
)
SPECIAL_CURRENCY_DOLLAR_RE = re.compile(
    r"\$\s*[\d,]+\s*(?:billion|million|thousand|hundred)\b"
)
# Plan item 7: [$] N or $ N with no multiplier word (raw number)
SPECIAL_CURRENCY_RAW_BRACKET_RE = re.compile(r"\[\$\]\s*[\d,]+")
SPECIAL_CURRENCY_RAW_DOLLAR_RE = re.compile(
    r"\$\s*[\d,]+(?!\s*(?:billion|million|thousand|hundred)\b)"
)
# Plan: [dollars] N
SPECIAL_CURRENCY_DOLLARS_BRACKET_RE = re.compile(r"\[dollars\]\s*[\d,]+", re.IGNORECASE)


def scan_turn_special_currency(
    text: str,
    path_str: str = "",
) -> list[tuple[str, int, str, str]]:
    """Emit (special_currency, start_index, span, path_str) for each match."""
    result: list[tuple[str, int, str, str]] = []
    for m in SPECIAL_CURRENCY_BRACKET_RE.finditer(text):
        result.append(("special_currency", m.start(), m.group(0), path_str))
    for m in SPECIAL_CURRENCY_DOLLAR_RE.finditer(text):
        result.append(("special_currency", m.start(), m.group(0), path_str))
    for m in SPECIAL_CURRENCY_RAW_BRACKET_RE.finditer(text):
        result.append(("special_currency", m.start(), m.group(0), path_str))
    for m in SPECIAL_CURRENCY_RAW_DOLLAR_RE.finditer(text):
        result.append(("special_currency", m.start(), m.group(0), path_str))
    for m in SPECIAL_CURRENCY_DOLLARS_BRACKET_RE.finditer(text):
        result.append(("special_currency", m.start(), m.group(0), path_str))
    return result
