# Generated by Claude
"""Process audio subcommand for oyez_sa_asr CLI."""

import json
from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console
from tqdm import tqdm

from .audio_utils import get_audio_metadata, load_audio, save_audio

console = Console(force_terminal=True)


def _find_audio_files(cache_dir: Path) -> list[Path]:
    """Find all audio files in cache directory."""
    audio_files = []
    for fmt in ("mp3", "ogg"):
        pattern = f"oyez.case-media.{fmt}/case_data/**/*.{fmt}"
        audio_files.extend(cache_dir.glob(pattern))
    return audio_files


def _extract_term_docket(path: Path) -> tuple[str, str] | None:
    """Extract term and docket from audio path."""
    # Path like: .../case_data/{term}/{docket}/{file}.mp3
    parts = path.parts
    try:
        case_data_idx = parts.index("case_data")
        term = parts[case_data_idx + 1]
        docket = parts[case_data_idx + 2]
        return term, docket
    except (ValueError, IndexError):
        return None


def add_audio_command(app: typer.Typer) -> None:
    """Add the audio command to the process app."""

    @app.command(name="audio")
    def process_audio(
        cache_dir: Annotated[
            Path,
            typer.Option("--cache-dir", "-c", help="Directory with cached audio"),
        ] = Path(".cache/audio"),
        output_dir: Annotated[
            Path,
            typer.Option("--output-dir", "-o", help="Output directory for audio"),
        ] = Path("data/audio"),
        bits: Annotated[
            int,
            typer.Option("--bits", "-b", help="FLAC bit depth (16 or 24)"),
        ] = 24,
    ) -> None:
        """Process cached audio into standardized FLAC format with metadata.

        Reads audio files from cache, extracts metadata, and saves:
        - Re-encoded FLAC files at data/audio/{term}/{docket}/{file}.flac
        - Metadata JSON at data/audio/{term}/{docket}/{file}.metadata.json
        """
        console.print("[bold]Processing cached audio files[/bold]")
        console.print(f"  Cache dir: {cache_dir}")
        console.print(f"  Output dir: {output_dir}")
        console.print(f"  FLAC bit depth: {bits}")
        console.print()

        audio_files = _find_audio_files(cache_dir)

        if not audio_files:
            console.print("[yellow]No audio files found in cache.[/yellow]")
            console.print("Run 'scrape audio' first to download audio files.")
            return

        console.print(f"Found {len(audio_files)} audio files")

        processed, errors = 0, 0

        with tqdm(audio_files, desc="Processing", unit="file") as pbar:
            for audio_path in pbar:
                try:
                    info = _extract_term_docket(audio_path)
                    if info is None:
                        errors += 1
                        continue

                    term, docket = info
                    stem = audio_path.stem
                    out_dir = output_dir / term / docket
                    out_dir.mkdir(parents=True, exist_ok=True)

                    # Extract metadata, load, re-encode, save
                    meta = get_audio_metadata(audio_path)
                    meta["source_path"] = str(audio_path)
                    samples, sr = load_audio(audio_path)
                    flac_path = out_dir / f"{stem}.flac"
                    save_audio(
                        samples, sr, flac_path, format="flac", bits_per_sample=bits
                    )
                    meta_path = out_dir / f"{stem}.metadata.json"
                    with meta_path.open("w") as f:
                        json.dump(meta, f, indent=2)

                    processed += 1
                    pbar.set_postfix(ok=processed, err=errors)

                except Exception:
                    errors += 1
                    pbar.set_postfix(ok=processed, err=errors)

        console.print()
        console.print(f"[bold green]Done![/bold green] Processed {processed} files.")
        if errors > 0:
            console.print(f"[yellow]Errors:[/yellow] {errors} files failed")
        console.print(f"Output: {output_dir}")
