# Generated by Claude
"""Publish commands for uploading datasets to HuggingFace Hub."""

from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console

publish_app = typer.Typer(help="Publish datasets to HuggingFace Hub")
console = Console(force_terminal=True)


def _upload_to_hub(
    dataset_dir: Path,
    repo_id: str,
    private: bool,
    dataset_type: str,
) -> None:
    """Upload dataset directory to HuggingFace Hub."""
    try:
        from huggingface_hub import HfApi  # noqa: PLC0415
    except ImportError:
        console.print("[red]Error:[/red] huggingface-hub not installed.")
        console.print("Run: uv add huggingface-hub")
        raise typer.Exit(1) from None

    if not dataset_dir.exists():
        console.print(f"[red]Error:[/red] {dataset_dir} not found.")
        console.print(f"Run 'oyez dataset {dataset_type}' first.")
        raise typer.Exit(1)

    console.print(f"Uploading to {repo_id}...")
    api = HfApi()

    # Create repo if needed
    api.create_repo(
        repo_id=repo_id,
        repo_type="dataset",
        private=private,
        exist_ok=True,
    )

    # Upload folder
    api.upload_folder(
        folder_path=str(dataset_dir),
        repo_id=repo_id,
        repo_type="dataset",
    )

    console.print()
    console.print("[bold green]Done![/bold green]")
    console.print(f"Dataset: https://huggingface.co/datasets/{repo_id}")


@publish_app.command(name="raw")
def publish_raw(
    dataset_dir: Annotated[
        Path,
        typer.Option("--dataset-dir", "-d", help="Raw dataset directory"),
    ] = Path("datasets/raw"),
    repo_id: Annotated[
        str,
        typer.Option("--repo-id", "-r", help="HuggingFace repo ID"),
    ] = "oyez-sa-asr-raw",
    private: Annotated[
        bool,
        typer.Option("--private", "-p", help="Make repository private"),
    ] = False,
) -> None:
    """Upload oyez-sa-asr-raw dataset to HuggingFace Hub.

    The raw dataset contains original MP3/OGG audio and raw JSON files.
    """
    console.print("[bold]Publishing oyez-sa-asr-raw[/bold]")
    console.print(f"  Dataset dir: {dataset_dir}")
    console.print(f"  Repo ID: {repo_id}")
    console.print(f"  Private: {private}")
    console.print()

    _upload_to_hub(dataset_dir, repo_id, private, "raw")


@publish_app.command(name="flex")
def publish_flex(
    dataset_dir: Annotated[
        Path,
        typer.Option("--dataset-dir", "-d", help="Flex dataset directory"),
    ] = Path("datasets/flex"),
    repo_id: Annotated[
        str,
        typer.Option("--repo-id", "-r", help="HuggingFace repo ID"),
    ] = "oyez-sa-asr-flex",
    private: Annotated[
        bool,
        typer.Option("--private", "-p", help="Make repository private"),
    ] = False,
) -> None:
    """Upload oyez-sa-asr-flex dataset to HuggingFace Hub.

    The flex dataset contains FLAC audio and parquet metadata references.
    """
    console.print("[bold]Publishing oyez-sa-asr-flex[/bold]")
    console.print(f"  Dataset dir: {dataset_dir}")
    console.print(f"  Repo ID: {repo_id}")
    console.print(f"  Private: {private}")
    console.print()

    _upload_to_hub(dataset_dir, repo_id, private, "flex")


@publish_app.command(name="simple")
def publish_simple(
    dataset_dir: Annotated[
        Path,
        typer.Option("--dataset-dir", "-d", help="Simple dataset directory"),
    ] = Path("datasets/simple"),
    repo_id: Annotated[
        str,
        typer.Option("--repo-id", "-r", help="HuggingFace repo ID"),
    ] = "oyez-sa-asr-simple",
    private: Annotated[
        bool,
        typer.Option("--private", "-p", help="Make repository private"),
    ] = False,
) -> None:
    """Upload oyez-sa-asr-simple dataset to HuggingFace Hub.

    The simple dataset contains embedded audio in parquet for streaming.
    """
    console.print("[bold]Publishing oyez-sa-asr-simple[/bold]")
    console.print(f"  Dataset dir: {dataset_dir}")
    console.print(f"  Repo ID: {repo_id}")
    console.print(f"  Private: {private}")
    console.print()

    _upload_to_hub(dataset_dir, repo_id, private, "simple")
