# Generated by Claude
"""Stats cases command."""

import json
from collections import Counter
from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console

from .term_filter import filter_dirs

console = Console(force_terminal=True)


def register_cases_command(app: typer.Typer) -> None:
    """Register the cases command on the given app."""
    app.command(name="cases")(stats_cases)


def stats_cases(
    data_dir: Annotated[
        Path,
        typer.Option("--data-dir", "-d", help="Processed data directory"),
    ] = Path("data"),
    terms: Annotated[
        list[str] | None,
        typer.Option("--term", "-T", help="Filter to specific term(s)"),
    ] = None,
) -> None:
    """Display case statistics."""
    cases_dir = data_dir / "cases"

    if not cases_dir.exists():
        console.print(f"[red]Error:[/red] {cases_dir} not found.")
        console.print("Run 'oyez process cases' first.")
        raise typer.Exit(1)

    # Collect stats
    total_cases = 0
    with_oral_arguments = 0
    with_opinion_announcements = 0
    term_counts: Counter[str] = Counter()
    all_terms: list[str] = []

    term_dirs = filter_dirs(list(cases_dir.iterdir()), terms)

    for term_dir in term_dirs:
        if not term_dir.is_dir():
            continue

        term_name = term_dir.name
        all_terms.append(term_name)

        for case_file in term_dir.glob("*.json"):
            try:
                with case_file.open() as f:
                    data = json.load(f)

                total_cases += 1
                term_counts[term_name] += 1

                oral_args = data.get("oral_arguments", [])
                if oral_args:
                    with_oral_arguments += 1

                opinions = data.get("opinion_announcements", [])
                if opinions:
                    with_opinion_announcements += 1

            except (json.JSONDecodeError, KeyError):
                continue

    if total_cases == 0:
        console.print("[yellow]No cases found.[/yellow]")
        return

    # Calculate term range
    sorted_terms = sorted(all_terms)
    term_range = f"{sorted_terms[0]}-{sorted_terms[-1]}" if sorted_terms else "N/A"

    # Output
    console.print()
    console.print("[bold]Case Statistics[/bold]")
    console.print("=" * 40)
    console.print(f"Total cases: {total_cases:,}")
    console.print(f"Total with oral arguments: {with_oral_arguments:,}")
    console.print(f"Total with opinion announcements: {with_opinion_announcements:,}")
    console.print()

    console.print("[bold]By term (range):[/bold]")
    console.print(f"  {term_range} ({len(all_terms)} terms)")
    console.print()

    console.print("[bold]Recent terms:[/bold]")
    for term in sorted(term_counts.keys(), reverse=True)[:5]:
        console.print(f"  {term}: {term_counts[term]:,} cases")
