# Generated by Claude
"""HuggingFace datasets compatibility helpers.

Provides version detection to support both datasets v3.x (with loading scripts)
and v4.x (parquet auto-discovery only).
"""

from importlib.metadata import version as get_version

from packaging.version import parse as version_parse

_V4_THRESHOLD = version_parse("4.0.0")


def datasets_version() -> str:
    """Get the installed HuggingFace datasets version.

    Returns
    -------
        Version string (e.g., "4.5.0")
    """
    return get_version("datasets")


def supports_loading_scripts() -> bool:
    """Check if datasets version supports trust_remote_code loading scripts.

    Returns
    -------
        True if datasets < 4.0.0, False otherwise
    """
    return version_parse(datasets_version()) < _V4_THRESHOLD


def is_v4() -> bool:
    """Check if datasets version is 4.x or higher.

    Returns
    -------
        True if datasets >= 4.0.0, False otherwise
    """
    return version_parse(datasets_version()) >= _V4_THRESHOLD
