#!/usr/bin/env python3
# Generated by Cursor
# Edited by Cursor (uncovered-only: exclude awareness occurrences covered by any rule)
"""
Build a report with 3 examples + context per awareness category.

Reads data/awareness_*_candidates.json, randomly samples up to 3 occurrences per
category, loads transcript context from data/transcripts, writes
docs/awareness_examples_report.md. Use --seed for reproducible sampling.
When --uncovered-only (default), only includes awareness occurrences that do not
overlap any span from rule candidate files (data/<rule_id>_candidates.json,
excluding awareness_* and transcription_typo).
"""

import argparse
import json
import random
from pathlib import Path

CONTEXT_CHARS = 60
EXAMPLES_PER_CATEGORY = 3


def _load_rule_covered_intervals(
    data_dir: Path,
) -> dict[tuple[str, int], list[tuple[int, int]]]:
    """Build (path_str, line_num) -> [(start, end), ...] from all rule candidate JSONs.

    Excludes awareness_* and transcription_typo_candidates.json.
    """
    covered: dict[tuple[str, int], list[tuple[int, int]]] = {}
    for path in sorted(data_dir.glob("*_candidates.json")):
        if (
            path.name.startswith("awareness_")
            or path.name == "transcription_typo_candidates.json"
        ):
            continue
        try:
            data = json.loads(path.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        for c in data.get("candidates", []):
            span = c.get("span", "")
            end_offset = len(span)
            for occ in c.get("occurrences", []):
                path_str = occ.get("path", "")
                line_num = occ.get("line_num", -1)
                start_index = occ.get("start_index", 0)
                key = (path_str, line_num)
                if key not in covered:
                    covered[key] = []
                covered[key].append((start_index, start_index + end_offset))
    return covered


def _is_covered(
    path_str: str,
    line_num: int,
    start: int,
    end: int,
    covered: dict[tuple[str, int], list[tuple[int, int]]],
) -> bool:
    """Return True if [start, end) overlaps any rule interval at (path_str, line_num)."""
    intervals = covered.get((path_str, line_num), [])
    for other_start, other_end in intervals:
        if not (end <= other_start or other_end <= start):
            return True
    return False


def _get_turn_text(transcripts_dir: Path, path_str: str, turn_index: int) -> str | None:
    """Load transcript and return text of turn with index turn_index."""
    path = transcripts_dir / path_str
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        return None
    for turn in data.get("turns") or []:
        if isinstance(turn, dict) and turn.get("index") == turn_index:
            return turn.get("text") or ""
    return None


def _snippet(
    text: str, start: int, span: str, context_chars: int = CONTEXT_CHARS
) -> str:
    """Return a snippet of text around the span with context_chars on each side."""
    end = start + len(span)
    lo = max(0, start - context_chars)
    hi = min(len(text), end + context_chars)
    snippet_str = text[lo:hi]
    if lo > 0:
        snippet_str = "…" + snippet_str
    if hi < len(text):
        snippet_str = snippet_str + "…"
    return snippet_str


def main() -> None:
    """Build awareness examples report; default is uncovered-only."""
    parser = argparse.ArgumentParser(
        description="Build awareness examples report (3 examples + context per category)."
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Include all awareness occurrences; default is --uncovered-only",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("docs/awareness_examples_report.md"),
        help="Output markdown path",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="Random seed for sampling examples (reproducible run)",
    )
    args = parser.parse_args()
    uncovered_only = not args.all
    if args.seed is not None:
        random.seed(args.seed)

    data_dir = Path("data")
    transcripts_dir = data_dir / "transcripts"
    out_path = args.output
    if not transcripts_dir.is_dir():
        print(f"Transcripts dir not found: {transcripts_dir}")
        raise SystemExit(1)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    covered = _load_rule_covered_intervals(data_dir) if uncovered_only else {}

    awareness_files = sorted(data_dir.glob("awareness_*_candidates.json"))
    header = [
        "# Awareness categories: 3 examples + context per category",
        "",
        "Categories have no normalization rule (awareness/review only).",
    ]
    if uncovered_only:
        header.append(
            "Only occurrences **not covered** by any normalization rule (no overlapping rule span)."
        )
    header.extend(["", "Context is transcript turn text around the matched span.", ""])
    lines: list[str] = header

    # Load all categories with total/uncovered count and examples; sort by display count descending
    categories: list[
        tuple[str, str, list[dict], int, list[tuple[str, str, int, int]]]
    ] = []  # rule_id, rule_name, candidates, display_count (uncovered or total), examples
    for af in awareness_files:
        try:
            payload = json.loads(af.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        rule_id = payload.get("rule_id", af.stem.replace("_candidates", ""))
        rule_name = payload.get("rule_name", rule_id)
        candidates = payload.get("candidates", [])
        all_uncovered: list[
            tuple[str, str, int, int]
        ] = []  # path, span, line_num, start_index
        for c in candidates:
            span = c.get("span", "")
            for occ in c.get("occurrences", []):
                path_str = occ.get("path", "")
                line_num = occ.get("line_num", -1)
                start_index = occ.get("start_index", 0)
                if uncovered_only and _is_covered(
                    path_str, line_num, start_index, start_index + len(span), covered
                ):
                    continue
                all_uncovered.append((path_str, span, line_num, start_index))
        uncovered_count = len(all_uncovered)
        examples = (
            random.sample(all_uncovered, min(EXAMPLES_PER_CATEGORY, len(all_uncovered)))
            if all_uncovered
            else []
        )
        display_count = (
            uncovered_count
            if uncovered_only
            else sum(c.get("count", 0) for c in candidates)
        )
        categories.append((rule_id, rule_name, candidates, display_count, examples))

    for rule_id, rule_name, _candidates, display_count, examples in sorted(
        categories, key=lambda x: -x[3]
    ):
        lines.append(f"## {rule_name} (`{rule_id}`)")
        lines.append("")
        lines.append(f"**Total:** {display_count:,} occurrences.")
        lines.append("")
        if not examples:
            lines.append("*No occurrences.*")
            lines.append("")
            continue
        for i, (path_str, span, line_num, start_index) in enumerate(examples, 1):
            text = _get_turn_text(transcripts_dir, path_str, line_num)
            context = (
                _snippet(text, start_index, span)
                if text
                else "*[turn text not loaded]*"
            )
            span_repr = repr(span)
            lines.append(f"**Example {i}** — span: {span_repr}")
            lines.append("")
            lines.append(
                f"- Path: `{path_str}` turn index {line_num}, start_index {start_index}"
            )
            lines.append(f"- Context: `{context}`")
            lines.append("")
        lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    mode = "uncovered-only" if uncovered_only else "all"
    print(f"Wrote {out_path} ({mode})")


if __name__ == "__main__":
    main()
