# Edited by Cursor: SCANNER_NAME_TO_RULE_IDS (lintok; no new exclusions).
"""Scanner name -> rule ids map."""

from scripts.build_rule_candidates_registry_regex import RULE_REGEX

SCANNER_NAME_TO_RULE_IDS: dict[str, list[str]] = {
    "scan_turn": list(RULE_REGEX),
    "scan_turn_latin": ["latin_extended"],
    "quotes": ["open_double_quote", "close_double_quote"],
    "dashes": ["dash"],
    "non_speech_brackets": ["non_speech_brackets"],
    "digit_letter": ["digit_letter_mixed"],
    "known_names": ["known_names"],
    "known_mixed_case": ["known_mixed_case_entities"],
    "all_caps_accept": ["all_caps_accept"],
    "numbered_list": ["numbered_list_marker"],
    "symbols": [
        "currency",
        "symbol_section_ref",
        "symbol_section",
        "symbol_copyright",
        "symbol_pound",
    ],
    "title_abbreviation": ["title_abbreviation"],
    "short_mixed_acronym": ["short_mixed_acronym"],
    "pascal_case_accept": ["pascal_case_accept"],
    "trailing_dash_accept": ["trailing_dash_accept"],
    "mixed_case_accept_6plus": ["mixed_case_accept_6plus"],
    "name_pattern_di": ["name_pattern_di"],
    "bracket_sentence_unwrap": ["bracket_sentence_unwrap"],
    "website_dot": ["website_dot"],
    "concatenated_word_split": ["concatenated_word_split"],
    "split_word_merge": ["split_word_merge"],
    "repeated_word_accept": ["repeated_word_accept"],
    "global_repeated_word_accept": ["global_repeated_word_accept"],
    "replacement_char_fix": ["replacement_char_fix"],
    "invalid_question_mark_fix": ["invalid_question_mark_fix"],
    "common_acronym": ["common_acronym"],
    "special_currency": ["special_currency"],
    "dual_notation": ["dual_notation"],
    "fraction": ["fraction"],
    "half_number": ["half_number"],
    "section_header": ["section_header"],
    "letter_dash": ["letter_dash_sequence"],
    "letter_roman_clause": ["letter_roman_clause"],
    "roman_parens": ["roman_parens"],
    "bracket_acronym": ["bracket_acronym"],
    "single_digit_valid_word": ["single_digit_valid_word"],
    "editorial_dollar": ["editorial_dollar"],
    "inline_typo": ["inline_typo"],
    "typo_levenshtein": ["typo_levenshtein"],
}
