# Generated by Cursor (plan: legal dict cascade). Edited by Cursor.
"""Build data/legal_words.txt from LexPredict, Open Legal Dictionary, and Wikipedia Latin legal terms."""

from __future__ import annotations

import csv
import json
import logging
import re
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urlparse

import httpx

logger = logging.getLogger(__name__)

# Wikipedia List of Latin legal terms — HTML via REST API. Edited by Cursor.
WIKIPEDIA_LATIN_LEGAL_URL = (
    "https://en.wikipedia.org/w/rest.php/v1/page/List_of_Latin_legal_terms/html"
)
WIKIPEDIA_USER_AGENT = (
    "oyez_sa_asr legal dict builder (https://github.com/AlonKellner/oyez_sa_asr)"
)

# Tokenize: lowercase, split on non-alpha (keep apostrophe).
_WORD_RE = re.compile(r"[a-z']+", re.IGNORECASE)


def _tokenize(text: str) -> list[str]:
    return _WORD_RE.findall(text.lower())


def _collect_words_from_lexpredict_csv(path: Path) -> set[str]:
    """Extract words from a single LexPredict CSV (any string columns). Edited by Cursor."""
    words: set[str] = set()
    with open(path, encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            for val in row.values():
                if isinstance(val, str) and val.strip():
                    for w in _tokenize(val):
                        if w:
                            words.add(w)
    return words


def _collect_words_from_old_json(path: Path) -> set[str]:
    """Extract words from Open Legal Dictionary JSON (title field). Edited by Cursor."""
    words: set[str] = set()
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        return words
    for item in data:
        if isinstance(item, dict) and "title" in item:
            title = item["title"]
            if isinstance(title, str):
                for w in _tokenize(title):
                    if w:
                        words.add(w)
    return words


class _WikipediaLatinTableParser(HTMLParser):
    """Extract text from first column of first table (Term or phrase). Edited by Cursor."""

    def __init__(self) -> None:
        super().__init__()
        self.words: set[str] = set()
        self._in_table = False
        self._in_tbody = False
        self._in_tr = False
        self._td_index = 0
        self._collecting = False
        self._current_text: list[str] = []

    def handle_starttag(self, tag: str, _attrs: list[tuple[str, str | None]]) -> None:
        tag = tag.lower()
        if tag == "table" and not self._in_table:
            self._in_table = True
        elif tag == "tbody" and self._in_table:
            self._in_tbody = True
        elif tag == "tr" and self._in_tbody:
            self._in_tr = True
            self._td_index = 0
        elif tag == "td" and self._in_tr:
            self._td_index += 1
            self._collecting = self._td_index == 1
            if self._collecting:
                self._current_text = []

    def handle_endtag(self, tag: str) -> None:
        tag = tag.lower()
        if tag == "td" and self._collecting:
            text = "".join(self._current_text).strip()
            for w in _tokenize(text):
                if w:
                    self.words.add(w)
            self._collecting = False
        elif tag == "tr":
            self._in_tr = False
        elif tag == "tbody":
            self._in_tbody = False
        elif tag == "table":
            self._in_table = False

    def handle_data(self, data: str) -> None:
        if self._collecting:
            self._current_text.append(data)


def _collect_words_from_wikipedia_latin_legal(html: str) -> set[str]:
    """Parse Wikipedia List of Latin legal terms HTML; return tokenized words from first column. Edited by Cursor."""
    parser = _WikipediaLatinTableParser()
    parser.feed(html)
    return parser.words


def _fetch_wikipedia_latin_legal(timeout: float = 30.0) -> str | None:
    """Fetch Wikipedia List of Latin legal terms HTML. Returns None on failure. Edited by Cursor."""
    parsed = urlparse(WIKIPEDIA_LATIN_LEGAL_URL)
    if parsed.scheme not in ("http", "https"):
        logger.error("Invalid URL scheme: %s", parsed.scheme)
        return None
    try:
        r = httpx.get(
            WIKIPEDIA_LATIN_LEGAL_URL,
            headers={"User-Agent": WIKIPEDIA_USER_AGENT},
            timeout=timeout,
            follow_redirects=False,
        )
        r.raise_for_status()
        return r.text
    except (httpx.HTTPError, httpx.RequestError) as e:
        logger.warning("Failed to fetch Wikipedia Latin legal terms: %s", e)
        return None


def build_legal_set(
    *,
    lexpredict_paths: list[Path] | None = None,
    old_json_paths: list[Path] | None = None,
    wikipedia_latin_legal_html_path: Path | None = None,
    wikipedia_latin_legal_html_content: str | None = None,
) -> frozenset[str]:
    """Build a single frozenset of legal words from the given paths. Edited by Cursor."""
    all_words: set[str] = set()
    for p in lexpredict_paths or []:
        if p.exists():
            all_words |= _collect_words_from_lexpredict_csv(p)
    for p in old_json_paths or []:
        if p.exists():
            all_words |= _collect_words_from_old_json(p)
    if wikipedia_latin_legal_html_content is not None:
        all_words |= _collect_words_from_wikipedia_latin_legal(
            wikipedia_latin_legal_html_content
        )
    elif (
        wikipedia_latin_legal_html_path is not None
        and wikipedia_latin_legal_html_path.exists()
    ):
        html = wikipedia_latin_legal_html_path.read_text(encoding="utf-8")
        all_words |= _collect_words_from_wikipedia_latin_legal(html)
    return frozenset(all_words)


def write_legal_words_file(
    words: frozenset[str],
    out_path: Path,
    *,
    header_comment: str | None = None,
) -> None:
    """Write one word per line (sorted), optional header comment. Edited by Cursor."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        if header_comment:
            for line in header_comment.strip().split("\n"):
                f.write(f"# {line}\n")
        for w in sorted(words):
            f.write(f"{w}\n")


def main() -> None:
    """Default: read data/legal_sources/*, write data/legal_words.txt. Edited by Cursor."""
    root = Path(__file__).resolve().parent.parent
    lex_dir = root / "data" / "legal_sources" / "lexpredict-legal-dictionary" / "en"
    old_data_dir = root / "data" / "legal_sources" / "openlegaldictionary" / "_data"
    out_path = root / "data" / "legal_words.txt"

    lexpredict_paths: list[Path] = []
    if lex_dir.exists():
        lexpredict_paths = list(lex_dir.rglob("*.csv"))
    old_json_paths: list[Path] = []
    for name in ("bld.json", "usc.json"):
        p = old_data_dir / name
        if p.exists():
            old_json_paths.append(p)

    wikipedia_html = _fetch_wikipedia_latin_legal()
    words = build_legal_set(
        lexpredict_paths=lexpredict_paths or None,
        old_json_paths=old_json_paths or None,
        wikipedia_latin_legal_html_path=None,
        wikipedia_latin_legal_html_content=wikipedia_html,
    )
    header = (
        "Legal words from LexPredict (CC-BY-SA 4.0), Open Legal Dictionary (MIT), "
        "and Wikipedia List of Latin legal terms."
    )
    write_legal_words_file(words, out_path, header_comment=header)
    print(f"Wrote {len(words)} words to {out_path}")


if __name__ == "__main__":
    main()
