#!/usr/bin/env python3
# Generated by Cursor
"""
Scan transcripts for rule categories (vote_tally, years, roman_numerals, etc.).

Group by (rule_id, span), apply normalization, write per-rule JSON in unified schema.
"""

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path

from scripts.collect_asr_artifacts import (
    DECADE_RE,
    PERCENTAGE_RE,
    ROMAN_NUMERAL_RE,
    VOTE_TALLY_RE,
    YEAR_RE,
)
from scripts.rule_normalizations import (
    normalize_decade,
    normalize_latin,
    normalize_percentage,
    normalize_roman_numeral,
    normalize_vote_tally,
    normalize_year,
)

# rule_id -> (regex, group_ix for span), and normalizer (span -> list[str] or list[dict])
RULE_REGEX: dict[str, tuple[re.Pattern[str], int]] = {
    "vote_tally": (VOTE_TALLY_RE, 1),
    "years": (YEAR_RE, 1),
    "roman_numerals": (ROMAN_NUMERAL_RE, 1),
    "percentages": (PERCENTAGE_RE, 0),
    "decades": (DECADE_RE, 0),
}
# Latin extended: word-based scan (no regex entry)
LATIN_EXTENDED_RANGE = range(0x00C0, 0x0250)
WORD_RE = re.compile(r"\S+")

RULE_NORMALIZER: dict[str, callable] = {
    "vote_tally": normalize_vote_tally,
    "years": normalize_year,
    "roman_numerals": normalize_roman_numeral,
    "percentages": normalize_percentage,
    "decades": normalize_decade,
    "latin_extended": normalize_latin,
}
RULE_LABELS: dict[str, str] = {
    "vote_tally": "Vote tally (9-0, 7-2)",
    "years": "Year (19xx, 20xx)",
    "roman_numerals": "Roman numeral (VII, IV)",
    "percentages": "Percentage (50%, 25 percent)",
    "decades": "Decade (1980s, 1930s)",
    "latin_extended": "Latin extended (accented characters)",
}
ALL_RULE_IDS: list[str] = [*list(RULE_REGEX), "latin_extended"]


def _scan_turn(text: str, path_str: str) -> list[tuple[str, int, str, str]]:
    """Emit (rule_id, start_index, span, path_str) for each match."""
    out: list[tuple[str, int, str, str]] = []
    for rule_id, (pattern, group_ix) in RULE_REGEX.items():
        for m in pattern.finditer(text):
            span = m.group(0) if group_ix == 0 else m.group(group_ix)
            out.append((rule_id, m.start(), span, path_str))
    return out


def _scan_turn_latin(text: str, path_str: str) -> list[tuple[str, int, str, str]]:
    """Emit (latin_extended, start_index, word, path_str) for words containing Latin extended chars."""
    out: list[tuple[str, int, str, str]] = []
    for m in WORD_RE.finditer(text):
        word = m.group(0)
        if any(ord(c) in LATIN_EXTENDED_RANGE for c in word):
            out.append(("latin_extended", m.start(), word, path_str))
    return out


def main() -> None:
    """Build rule candidate JSON files from transcripts (unified schema)."""
    parser = argparse.ArgumentParser(
        description="Build rule correction candidates from transcripts (unified schema)."
    )
    parser.add_argument(
        "-i",
        "--input",
        type=Path,
        default=Path("data/transcripts"),
        help="Transcripts directory (recursive *.json)",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("data"),
        help="Output directory for <rule_id>_candidates.json",
    )
    args = parser.parse_args()
    transcripts_dir = args.input
    out_dir = args.output
    if not transcripts_dir.is_dir():
        print(f"Input directory not found: {transcripts_dir}")
        raise SystemExit(1)
    out_dir.mkdir(parents=True, exist_ok=True)

    # (rule_id, span) -> list of (path, line_num, start_index)
    groups: dict[tuple[str, str], list[tuple[str, int, int]]] = defaultdict(list)
    for path in sorted(transcripts_dir.rglob("*.json")):
        try:
            data = json.loads(path.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        try:
            rel = path.relative_to(transcripts_dir)
        except ValueError:
            rel = path
        path_str = str(rel).replace("\\", "/")
        for turn in data.get("turns") or []:
            if not isinstance(turn, dict):
                continue
            text = turn.get("text") or ""
            turn_index = turn.get("index", -1)
            if turn_index < 0:
                continue
            for rule_id, start_index, span, _ in _scan_turn(text, path_str):
                groups[(rule_id, span)].append((path_str, turn_index, start_index))
            for rule_id, start_index, span, _ in _scan_turn_latin(text, path_str):
                groups[(rule_id, span)].append((path_str, turn_index, start_index))

    for rule_id in ALL_RULE_IDS:
        candidates: list[dict] = []
        for (rid, span), occurrences_raw in groups.items():
            if rid != rule_id:
                continue
            normalizer = RULE_NORMALIZER.get(rule_id)
            raw = normalizer(span) if normalizer else [span]
            if raw and isinstance(raw[0], dict) and "text" in raw[0]:
                corrections = list(raw)
            else:
                corrections = [{"text": t} for t in raw]
            occurrences = [
                {"path": p, "line_num": ln, "start_index": si}
                for p, ln, si in occurrences_raw
            ]
            candidates.append(
                {
                    "span": span,
                    "corrections": corrections,
                    "count": len(occurrences),
                    "occurrences": occurrences,
                    "occurrences_truncated": False,
                }
            )
        payload = {
            "rule_id": rule_id,
            "rule_name": RULE_LABELS.get(rule_id, rule_id),
            "candidates": candidates,
            "filter_note": None,
        }
        out_path = out_dir / f"{rule_id}_candidates.json"
        out_path.write_text(json.dumps(payload, indent=2))
    print(f"Wrote {len(ALL_RULE_IDS)} rule candidate files to {out_dir}")


if __name__ == "__main__":
    main()
