# Edited by Cursor: RULE_NORMALIZER map (lintok; no new exclusions).
"""Rule id -> normalizer function map."""

from scripts.rule_normalizations import (
    normalize_all_caps_accept,
    normalize_bracket_acronym,
    normalize_bracket_sentence_unwrap,
    normalize_common_acronym,
    normalize_concatenated_word_split,
    normalize_currency,
    normalize_dash,
    normalize_decade,
    normalize_digit_letter_mixed,
    normalize_double_letter_parens,
    normalize_double_quote,
    normalize_dual_notation,
    normalize_editorial_dollar,
    normalize_fraction,
    normalize_global_repeated_word_accept,
    normalize_half_number,
    normalize_inline_typo,
    normalize_invalid_question_mark_fix,
    normalize_known_mixed_case_entities,
    normalize_known_names,
    normalize_latin,
    normalize_leading_decimal,
    normalize_letter_dash_sequence,
    normalize_letter_roman_clause,
    normalize_mixed_case_accept_6plus,
    normalize_name_pattern_di,
    normalize_non_speech_brackets,
    normalize_number_parens,
    normalize_numbered_list_marker,
    normalize_ordinal,
    normalize_pascal_case_accept,
    normalize_percentage,
    normalize_repeated_word_accept,
    normalize_replacement_char_fix,
    normalize_roman_numeral,
    normalize_roman_parens,
    normalize_section_header,
    normalize_short_mixed_acronym,
    normalize_single_digit_valid_word,
    normalize_single_letter_parens,
    normalize_special_currency,
    normalize_split_word_merge,
    normalize_symbol_copyright,
    normalize_symbol_pound,
    normalize_symbol_section,
    normalize_symbol_section_ref,
    normalize_time_of_day,
    normalize_title_abbreviation,
    normalize_trailing_dash_accept,
    normalize_typo_levenshtein,
    normalize_vote_tally,
    normalize_website_dot,
    normalize_year,
)

RULE_NORMALIZER: dict[str, callable] = {
    "vote_tally": normalize_vote_tally,
    "years": normalize_year,
    "roman_numerals": normalize_roman_numeral,
    "percentages": normalize_percentage,
    "decades": normalize_decade,
    "digit_letter_mixed": normalize_digit_letter_mixed,
    "known_names": normalize_known_names,
    "known_mixed_case_entities": normalize_known_mixed_case_entities,
    "all_caps_accept": normalize_all_caps_accept,
    "latin_extended": normalize_latin,
    "open_double_quote": normalize_double_quote,
    "close_double_quote": normalize_double_quote,
    "single_letter_parens": normalize_single_letter_parens,
    "double_letter_parens": normalize_double_letter_parens,
    "number_parens": normalize_number_parens,
    "dash": normalize_dash,
    "non_speech_brackets": normalize_non_speech_brackets,
    "numbered_list_marker": normalize_numbered_list_marker,
    "ordinals": normalize_ordinal,
    "leading_decimal": normalize_leading_decimal,
    "currency": normalize_currency,
    "symbol_section": normalize_symbol_section,
    "symbol_section_ref": normalize_symbol_section_ref,
    "symbol_copyright": normalize_symbol_copyright,
    "symbol_pound": normalize_symbol_pound,
    "editorial_dollar": normalize_editorial_dollar,
    "inline_typo": normalize_inline_typo,
    "title_abbreviation": normalize_title_abbreviation,
    "bracket_acronym": normalize_bracket_acronym,
    "common_acronym": normalize_common_acronym,
    "time_of_day": normalize_time_of_day,
    "special_currency": normalize_special_currency,
    "dual_notation": normalize_dual_notation,
    "fraction": normalize_fraction,
    "half_number": normalize_half_number,
    "section_header": normalize_section_header,
    "mixed_case_accept_6plus": normalize_mixed_case_accept_6plus,
    "name_pattern_di": normalize_name_pattern_di,
    "bracket_sentence_unwrap": normalize_bracket_sentence_unwrap,
    "website_dot": normalize_website_dot,
    "concatenated_word_split": normalize_concatenated_word_split,
    "split_word_merge": normalize_split_word_merge,
    "repeated_word_accept": normalize_repeated_word_accept,
    "global_repeated_word_accept": normalize_global_repeated_word_accept,
    "replacement_char_fix": normalize_replacement_char_fix,
    "invalid_question_mark_fix": normalize_invalid_question_mark_fix,
    "pascal_case_accept": normalize_pascal_case_accept,
    "trailing_dash_accept": normalize_trailing_dash_accept,
    "short_mixed_acronym": normalize_short_mixed_acronym,
    "letter_dash_sequence": normalize_letter_dash_sequence,
    "letter_roman_clause": normalize_letter_roman_clause,
    "roman_parens": normalize_roman_parens,
    "single_digit_valid_word": normalize_single_digit_valid_word,
    "typo_levenshtein": normalize_typo_levenshtein,
}
