# Edited by Cursor: normalizers registry for build_rule_candidates (lintok split).
"""Rule normalizers and labels."""

from scripts.build_rule_candidates_registry_regex import RULE_REGEX
from scripts.rule_normalizations import (
    normalize_all_caps_accept,
    normalize_bracket_acronym,
    normalize_bracket_sentence_unwrap,
    normalize_common_acronym,
    normalize_concatenated_word_split,
    normalize_currency,
    normalize_dash,
    normalize_decade,
    normalize_digit_letter_mixed,
    normalize_double_letter_parens,
    normalize_double_quote,
    normalize_dual_notation,
    normalize_editorial_dollar,
    normalize_fraction,
    normalize_global_repeated_word_accept,
    normalize_half_number,
    normalize_inline_typo,
    normalize_invalid_question_mark_fix,
    normalize_known_mixed_case_entities,
    normalize_known_names,
    normalize_latin,
    normalize_leading_decimal,
    normalize_letter_dash_sequence,
    normalize_letter_roman_clause,
    normalize_mixed_case_accept_6plus,
    normalize_name_pattern_di,
    normalize_non_speech_brackets,
    normalize_number_parens,
    normalize_numbered_list_marker,
    normalize_ordinal,
    normalize_pascal_case_accept,
    normalize_percentage,
    normalize_repeated_word_accept,
    normalize_replacement_char_fix,
    normalize_roman_numeral,
    normalize_roman_parens,
    normalize_section_header,
    normalize_short_mixed_acronym,
    normalize_single_digit_valid_word,
    normalize_single_letter_parens,
    normalize_special_currency,
    normalize_split_word_merge,
    normalize_symbol_copyright,
    normalize_symbol_pound,
    normalize_symbol_section,
    normalize_symbol_section_ref,
    normalize_time_of_day,
    normalize_title_abbreviation,
    normalize_trailing_dash_accept,
    normalize_typo_levenshtein,
    normalize_vote_tally,
    normalize_website_dot,
    normalize_year,
)

RULE_NORMALIZER: dict[str, callable] = {
    "vote_tally": normalize_vote_tally,
    "years": normalize_year,
    "roman_numerals": normalize_roman_numeral,
    "percentages": normalize_percentage,
    "decades": normalize_decade,
    "digit_letter_mixed": normalize_digit_letter_mixed,
    "known_names": normalize_known_names,
    "known_mixed_case_entities": normalize_known_mixed_case_entities,
    "all_caps_accept": normalize_all_caps_accept,
    "latin_extended": normalize_latin,
    "open_double_quote": normalize_double_quote,
    "close_double_quote": normalize_double_quote,
    "single_letter_parens": normalize_single_letter_parens,
    "double_letter_parens": normalize_double_letter_parens,
    "number_parens": normalize_number_parens,
    "dash": normalize_dash,
    "non_speech_brackets": normalize_non_speech_brackets,
    "numbered_list_marker": normalize_numbered_list_marker,
    "ordinals": normalize_ordinal,
    "leading_decimal": normalize_leading_decimal,
    "currency": normalize_currency,
    "symbol_section": normalize_symbol_section,
    "symbol_section_ref": normalize_symbol_section_ref,
    "symbol_copyright": normalize_symbol_copyright,
    "symbol_pound": normalize_symbol_pound,
    "editorial_dollar": normalize_editorial_dollar,
    "inline_typo": normalize_inline_typo,
    "title_abbreviation": normalize_title_abbreviation,
    "bracket_acronym": normalize_bracket_acronym,
    "common_acronym": normalize_common_acronym,
    "time_of_day": normalize_time_of_day,
    "special_currency": normalize_special_currency,
    "dual_notation": normalize_dual_notation,
    "fraction": normalize_fraction,
    "half_number": normalize_half_number,
    "section_header": normalize_section_header,
    "mixed_case_accept_6plus": normalize_mixed_case_accept_6plus,
    "name_pattern_di": normalize_name_pattern_di,
    "bracket_sentence_unwrap": normalize_bracket_sentence_unwrap,
    "website_dot": normalize_website_dot,
    "concatenated_word_split": normalize_concatenated_word_split,
    "split_word_merge": normalize_split_word_merge,
    "repeated_word_accept": normalize_repeated_word_accept,
    "global_repeated_word_accept": normalize_global_repeated_word_accept,
    "replacement_char_fix": normalize_replacement_char_fix,
    "invalid_question_mark_fix": normalize_invalid_question_mark_fix,
    "pascal_case_accept": normalize_pascal_case_accept,
    "trailing_dash_accept": normalize_trailing_dash_accept,
    "short_mixed_acronym": normalize_short_mixed_acronym,
    "letter_dash_sequence": normalize_letter_dash_sequence,
    "letter_roman_clause": normalize_letter_roman_clause,
    "roman_parens": normalize_roman_parens,
    "single_digit_valid_word": normalize_single_digit_valid_word,
    "typo_levenshtein": normalize_typo_levenshtein,
}

RULE_LABELS: dict[str, str] = {
    "vote_tally": "Vote tally (9-0, 7-2)",
    "years": "Year (19xx, 20xx)",
    "roman_numerals": "Roman numeral (VII, IV)",
    "percentages": "Percentage (50%, 25 percent)",
    "decades": "Decade (1980s, 1930s)",
    "digit_letter_mixed": "Digit-letter mixed (2d, A2, 640L, 707{b}) -> spoken",
    "known_names": "Known names (McLaughlin, FitzGerald) - handled, no correction",
    "known_mixed_case_entities": "Known mixed-case (TikTok, YouTube, LinkedIn) - handled, no correction",
    "all_caps_accept": "All-caps 6+ letters (CERCLA, ASARCO) - handled, no correction",
    "latin_extended": "Latin extended (accented characters)",
    "open_double_quote": "Open double quote",
    "close_double_quote": "Close double quote",
    "single_letter_parens": "Single letter in parentheses (a)->ay",
    "double_letter_parens": "Two letters in parentheses (ph)->pee aych",
    "number_parens": "Number in parentheses (1)->one",
    "dash": "Non-standard dash -> standard dash",
    "non_speech_brackets": "Non-speech brackets (Inaudible, Laughter) -> empty",
    "numbered_list_marker": "Numbered list marker (1) -> one, only when unmatched)",
    "ordinals": "Ordinal (37th -> thirty seventh)",
    "leading_decimal": "Leading decimal (.06 -> point oh six)",
    "currency": "Currency (£40, $50) -> pounds/dollars",
    "symbol_section": "Section symbol (§) -> section",
    "symbol_section_ref": "Section ref (§1519) -> section fifteen nineteen",
    "symbol_copyright": "Copyright (©) -> copyright",
    "symbol_pound": "Pound symbol (£) -> pound",
    "editorial_dollar": "$<X> [= N] / £<X> [= N] -> X dollars/dollar",
    "title_abbreviation": "Title (Mr.->Mister, Dr.->Doctor, Mrs.->Misses, Jr.->Junior)",
    "bracket_acronym": "Bracket acronym (MPSC), (NRDC) -> letter-by-letter",
    "common_acronym": "Common acronym (PhD->pee aych dee)",
    "mixed_case_accept_6plus": "Mixed case 6+ letters -> accept (PowerEx, RadLAX)",
    "name_pattern_di": "Di + name (DiBona, DiMaria) -> accept",
    "bracket_sentence_unwrap": "Bracket 4+ words -> unwrap (inner text only)",
    "website_dot": "[xxxDOTyyy] -> xxx dot yyy",
    "concatenated_word_split": "Token split into two valid words -> 'left right'",
    "split_word_merge": "Two invalid tokens whose merge is valid -> merged word",
    "repeated_word_accept": "Word appearing 2+ times in same transcript -> accept (no correction)",
    "global_repeated_word_accept": "Invalid 3+ letter word appearing globally 3+ times -> accept (no correction)",
    "replacement_char_fix": "U+FFFD -> Condé Nast etc.",
    "invalid_question_mark_fix": "\ufffd? -> ?",
    "pascal_case_accept": "PascalCase 6+ letters each segment 3+ -> accept (CattleAnd, ByteDance)",
    "trailing_dash_accept": "Word + trailing dash (interruption) -> accept (no correction)",
    "short_mixed_acronym": "Short mixed-case 2-5 letters half+ caps -> spell (DoD, DiRe)",
    "time_of_day": "Time of day (8:40->eight forty)",
    "special_currency": "[$] N billion / $ N hundred -> dollars/dollar",
    "dual_notation": "<X> [= Y] -> normalize content X",
    "fraction": "Fraction (1/3, 2/5, ½) -> spoken",
    "half_number": "N½% / N ½ years -> N and a half percent/years",
    "section_header": "All-caps header at start/end of turn -> remove",
    "letter_dash_sequence": "(R-5) / R-5 -> ar five",
    "letter_roman_clause": "(C)(iii) -> cee three",
    "roman_parens": "Roman numeral in parentheses (i)-(xii) -> spoken",
    "single_digit_valid_word": "Word with one digit -> remove digit when remainder valid word",
    "inline_typo": "word[: correction] -> replace with correction",
    "typo_levenshtein": "Word with one digit, 1 Levenshtein from same-transcript word",
}

ALL_RULE_IDS: list[str] = [
    *list(RULE_REGEX),
    "digit_letter_mixed",
    "known_names",
    "known_mixed_case_entities",
    "all_caps_accept",
    "bracket_acronym",
    "latin_extended",
    "open_double_quote",
    "close_double_quote",
    "dash",
    "non_speech_brackets",
    "numbered_list_marker",
    "ordinals",
    "currency",
    "symbol_section",
    "symbol_section_ref",
    "symbol_copyright",
    "symbol_pound",
    "editorial_dollar",
    "title_abbreviation",
    "common_acronym",
    "special_currency",
    "dual_notation",
    "fraction",
    "half_number",
    "section_header",
    "mixed_case_accept_6plus",
    "name_pattern_di",
    "bracket_sentence_unwrap",
    "website_dot",
    "concatenated_word_split",
    "split_word_merge",
    "repeated_word_accept",
    "global_repeated_word_accept",
    "replacement_char_fix",
    "invalid_question_mark_fix",
    "pascal_case_accept",
    "trailing_dash_accept",
    "short_mixed_acronym",
    "letter_dash_sequence",
    "letter_roman_clause",
    "roman_parens",
    "single_digit_valid_word",
    "inline_typo",
    "typo_levenshtein",
]
