#!/usr/bin/env python3
# Generated by Cursor
# Edited by Cursor (unified schema, start_index from byte_offset, -i/-o)
"""
Rebuild typo candidates from raw typos report with ALL suggested corrections.

Unified schema: rule_id, rule_name, candidates (span, corrections, count,
occurrences with path, line_num, start_index). start_index derived from
byte_offset (or fallback: span in line). Filters: total count>=5, all caps,
same-transcript 2+ then drop; distances per (typo, correction).
"""

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

# Allow importing from scripts when run as script
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from scripts.typo_distances import keyboard_distance, levenshtein_distance


def _byte_offset_to_start_index(
    lines: list[str], line_num: int, byte_offset: int
) -> int:
    """Convert byte_offset (from start of file) to character offset in line.

    line_num is 1-based. byte_offset is from start of file.
    """
    line_start_byte = 0
    for i in range(line_num - 1):
        if i < len(lines):
            line_start_byte += len(lines[i].encode("utf-8")) + 1  # +1 for newline
    byte_in_line = byte_offset - line_start_byte
    segment = lines[line_num - 1] if line_num <= len(lines) else ""
    # Largest character index i such that len(segment[:i].encode()) <= byte_in_line
    start_index = 0
    for i in range(len(segment) + 1):
        if len(segment[:i].encode("utf-8")) <= byte_in_line:
            start_index = i
    return start_index


def _resolve_start_index_fallback(segment: str, span: str) -> int:
    """Find first occurrence of span in segment; return start index or 0."""
    idx = segment.find(span)
    return idx if idx >= 0 else 0


def main() -> None:
    """Rebuild candidates from raw typos report; output unified schema."""
    parser = argparse.ArgumentParser(
        description="Rebuild typo candidates with unified schema and start_index."
    )
    parser.add_argument(
        "-i",
        "--input",
        type=Path,
        default=Path("data/typos_transcripts_report.json"),
        help="Input JSONL report from typos CLI",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("data/transcription_typo_candidates.json"),
        help="Output candidate JSON (unified schema)",
    )
    args = parser.parse_args()
    report_path = args.input
    out_path = args.output
    if not report_path.exists():
        raise SystemExit(f"{report_path} not found")

    with report_path.open() as f:
        raw_lines = [line.strip() for line in f if line.strip()]

    # typo -> set of all corrections
    typo_to_corrections: dict[str, set[str]] = defaultdict(set)
    # typo -> list of occurrence dicts (path, line_num, byte_offset or None, typo)
    typo_to_occurrences: dict[str, list[dict]] = defaultdict(list)

    for line in raw_lines:
        try:
            obj = json.loads(line)
        except json.JSONDecodeError:
            continue
        if obj.get("type") != "typo":
            continue
        typo = obj.get("typo")
        corrections = obj.get("corrections") or []
        path_str = obj.get("path")
        line_num = obj.get("line_num")
        byte_offset = obj.get("byte_offset")
        if typo is None or path_str is None:
            continue
        for c in corrections:
            typo_to_corrections[typo].add(c)
        typo_to_occurrences[typo].append(
            {
                "path": path_str,
                "line_num": line_num or 0,
                "byte_offset": byte_offset,
                "typo": typo,
            }
        )

    def keep_occurrences(occs: list[dict]) -> list[dict]:
        by_path = defaultdict(list)
        for o in occs:
            by_path[o["path"]].append(o)
        kept = []
        for p in sorted(by_path):
            arr = by_path[p]
            if len(arr) == 1:
                kept.append(arr[0])
        return kept

    # Resolve start_index for each occurrence: group by path, read file once
    def resolve_occurrences(occs: list[dict]) -> list[dict]:
        by_path: dict[str, list[dict]] = defaultdict(list)
        for o in occs:
            by_path[o["path"]].append(o)
        result = []
        for path_str in sorted(by_path):
            path = Path(path_str)
            if not path.is_absolute():
                # Relative to cwd (e.g. repo root)
                path = Path.cwd() / path_str
            try:
                content = path.read_text(encoding="utf-8")
            except OSError:
                for o in by_path[path_str]:
                    result.append(
                        {
                            "path": o["path"],
                            "line_num": o["line_num"],
                            "start_index": 0,
                        }
                    )
                continue
            lines = content.split("\n")
            for o in by_path[path_str]:
                line_num = o["line_num"]
                typo = o["typo"]
                segment = lines[line_num - 1] if 1 <= line_num <= len(lines) else ""
                if o.get("byte_offset") is not None:
                    start_index = _byte_offset_to_start_index(
                        lines, line_num, o["byte_offset"]
                    )
                else:
                    start_index = _resolve_start_index_fallback(segment, typo)
                result.append(
                    {
                        "path": o["path"],
                        "line_num": o["line_num"],
                        "start_index": start_index,
                    }
                )
        return result

    candidates = []
    for typo in sorted(typo_to_corrections.keys()):
        occs = typo_to_occurrences[typo]
        total_count = len(occs)
        if total_count >= 5:
            continue
        if typo.isupper():
            continue
        kept_raw = keep_occurrences(occs)
        if len(kept_raw) == 0:
            continue
        resolved = resolve_occurrences(kept_raw)
        corrections_list = sorted(typo_to_corrections[typo])
        correction_objs = []
        for corr in corrections_list:
            correction_objs.append(
                {
                    "text": corr,
                    "keyboard_dist": keyboard_distance(typo, corr),
                    "levenshtein_dist": levenshtein_distance(typo, corr),
                }
            )
        candidates.append(
            {
                "span": typo,
                "corrections": correction_objs,
                "count": len(resolved),
                "occurrences": resolved[:100],
                "occurrences_truncated": len(resolved) > 100,
            }
        )

    data = {
        "rule_id": "transcription_typos",
        "rule_name": "Transcription typos (Rule 0)",
        "candidates": candidates,
        "filter_note": (
            "Excluded: total occurrences>=5 (before same-transcript filter), or typo all caps; "
            "then drop occurrences where typo appears 2+ in same transcript; drop if 0 remain. "
            "Unified schema with required start_index. Generated by Cursor."
        ),
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w") as f:
        json.dump(data, f, indent=2)
    print(f"Wrote {len(candidates)} candidates to {out_path}")
    multi = sum(1 for c in candidates if len(c["corrections"]) > 1)
    print(f"Typos with multiple corrections: {multi}")


if __name__ == "__main__":
    main()
