#!/usr/bin/env python3
# Generated by Cursor. Edited by Cursor: split to typo_distances_keyboard and typo_distances_levenshtein (lintok; plan).
"""Compute keyboard and Levenshtein distance for typo candidates. Thin CLI."""

import argparse
import json
import sys
from collections.abc import Iterator
from pathlib import Path

# Ensure scripts/ is on path when run as python scripts/typo_distances.py from repo root
_scripts_dir = Path(__file__).resolve().parent
if str(_scripts_dir) not in sys.path:
    sys.path.insert(0, str(_scripts_dir))

from typo_distances_keyboard import keyboard_distance  # noqa: E402
from typo_distances_levenshtein import levenshtein_distance  # noqa: E402


def main() -> None:
    """Load candidates, compute/fill distances, print stats and write back."""
    parser = argparse.ArgumentParser(
        description="Compute keyboard and Levenshtein distances for typo candidates."
    )
    parser.add_argument(
        "-i",
        "--input",
        type=Path,
        default=Path("data/transcription_typo_candidates.json"),
        help="Input candidate JSON (unified or legacy)",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=None,
        help="Output JSON (default: overwrite input)",
    )
    args = parser.parse_args()
    path = args.input
    out_path = args.output or path
    with path.open() as f:
        data = json.load(f)

    candidates = data["candidates"]
    for c in candidates:
        span = c.get("span") or c.get("typo")
        if not span:
            continue
        if "corrections" in c:
            for corr_obj in c["corrections"]:
                if "keyboard_dist" not in corr_obj:
                    corr_obj["keyboard_dist"] = keyboard_distance(
                        span, corr_obj["text"]
                    )
                if "levenshtein_dist" not in corr_obj:
                    corr_obj["levenshtein_dist"] = levenshtein_distance(
                        span, corr_obj["text"]
                    )
        else:
            corr = c.get("correction")
            if corr is None:
                continue
            c["keyboard_dist"] = keyboard_distance(span, corr)
            c["levenshtein_dist"] = levenshtein_distance(span, corr)

    def pairs() -> Iterator[tuple[str, str, int, int]]:
        for c in candidates:
            span = c.get("span") or c.get("typo")
            if not span:
                continue
            if "corrections" in c:
                for corr in c["corrections"]:
                    yield (
                        span,
                        corr["text"],
                        corr["keyboard_dist"],
                        corr["levenshtein_dist"],
                    )
            else:
                corr = c.get("correction")
                if corr is not None:
                    yield span, corr, c["keyboard_dist"], c["levenshtein_dist"]

    pairs_list = list(pairs())
    kd = [p[2] for p in pairs_list]
    ld = [p[3] for p in pairs_list]
    n = len(pairs_list)
    if n == 0:
        print("No candidate pairs found.")
        sys.exit(0)

    def bins_hist(vals: list[int], bins: list[tuple[int, int]]) -> list[int]:
        return [sum(1 for v in vals if lo <= v <= hi) for lo, hi in bins]

    kbins = [(1, 1), (2, 2), (3, 3), (4, 5), (6, 10), (11, 100)]
    lbins = [(1, 1), (2, 2), (3, 3), (4, 5), (6, 10), (11, 100)]

    k_counts = bins_hist(kd, kbins)
    l_counts = bins_hist(ld, lbins)

    by_kbin: dict[tuple[int, int], list[tuple[str, str, int, int]]] = {
        b: [] for b in kbins
    }
    for typo, corr, k, lev in pairs_list:
        for lo, hi in kbins:
            if lo <= k <= hi:
                by_kbin[(lo, hi)].append((typo, corr, k, lev))
                break
    by_lbin: dict[tuple[int, int], list[tuple[str, str, int, int]]] = {
        b: [] for b in lbins
    }
    for typo, corr, k, lev in pairs_list:
        for lo, hi in lbins:
            if lo <= lev <= hi:
                by_lbin[(lo, hi)].append((typo, corr, k, lev))
                break

    anomalies = []
    for typo, corr, k, lev in pairs_list:
        if k >= 2 * lev and lev >= 2:
            anomalies.append((typo, corr, k, lev, "keyboard >> lev"))
        elif lev >= 2 * k and k >= 2:
            anomalies.append((typo, corr, k, lev, "lev >> keyboard"))

    if "rule_id" not in data:
        data["rule_id"] = "transcription_typos"
    if "rule_name" not in data:
        data["rule_name"] = "Transcription typos (Rule 0)"
    for c in candidates:
        if "span" not in c and "typo" in c:
            c["span"] = c["typo"]
        for occ in c.get("occurrences", []):
            if "start_index" not in occ:
                occ["start_index"] = 0
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w") as f:
        json.dump(data, f, indent=2)

    print("=== Keyboard distance ===\n")
    print(f"  Min: {min(kd)}, Max: {max(kd)}, Mean: {sum(kd) / n:.2f}")
    print("  Bins:")
    for (lo, hi), cnt in zip(kbins, k_counts, strict=False):
        print(f"    {lo}-{hi}: {cnt}")
    print("  Examples per bin (keyboard):")
    for lo, hi in kbins:
        arr = by_kbin[(lo, hi)][:3]
        for typo, corr, k, _ in arr:
            print(f'    {lo}-{hi}: "{typo}" -> "{corr}" (k={k})')
    print("\n=== Levenshtein distance ===\n")
    print(f"  Min: {min(ld)}, Max: {max(ld)}, Mean: {sum(ld) / n:.2f}")
    print("  Bins:")
    for (lo, hi), cnt in zip(lbins, l_counts, strict=False):
        print(f"    {lo}-{hi}: {cnt}")
    print("  Examples per bin (lev):")
    for lo, hi in lbins:
        arr = by_lbin[(lo, hi)][:3]
        for typo, corr, _, lev in arr:
            print(f'    {lo}-{hi}: "{typo}" -> "{corr}" (lev={lev})')

    print("\n=== Anomalies (keyboard vs lev disparity) ===\n")
    for typo, corr, k, lev, tag in anomalies[:20]:
        print(f'  {tag}: "{typo}" -> "{corr}" (keyboard={k}, lev={lev})')
    if len(anomalies) > 20:
        print(f"  ... and {len(anomalies) - 20} more")

    print(f"\nDistances written to {out_path}")
    sys.exit(0)


if __name__ == "__main__":
    main()
